++ ls caseresult/ -ltr
++ wc -l
+ filename=case78
+ mkdir caseresult/case78
+ ssh hadoop@master mkdir /home/hadoop/git/physical_design/caseresult/case78
+ RESULT_DIR=/home/hadoop/git/physical_design/caseresult/case78
+ TEN=10
+ SIXTY=60
+ SLEEP_TIME=300
+ YCSB_DIR=/home/hadoop/ycsb-0.1.4
+ number_of_operations=10000000
+ number_of_threads=20
+ number_of_records=10000000
+ output_file_suffix=.dat
+ experiment_list_file=/home/hadoop/git/physical_design/case78.list
+ clean=false
+ create=false
+ load=false
+ random_read=false
+ workloada=false
+ workloadb=false
+ workloadc=false
+ scan=false
+ all=false
+ for i in '$@'
+ '[' clean == all ']'
+ '[' clean == clean ']'
+ clean=true
+ for i in '$@'
+ '[' create == all ']'
+ '[' create == clean ']'
+ '[' create == create ']'
+ create=true
+ for i in '$@'
+ '[' load == all ']'
+ '[' load == clean ']'
+ '[' load == create ']'
+ '[' load == load ']'
+ load=true
+ let counter=1
+ cd /home/hadoop/ycsb-0.1.4
++ pwd
+ echo /home/hadoop/ycsb-0.1.4
/home/hadoop/ycsb-0.1.4
+ read line
+ false
+ true
+ echo 'sleeping for 60 ...'
sleeping for 60 ...
+ sleep 60
+ echo 'droping usertable...'
droping usertable...
+ ssh hadoop@master /home/hadoop/hbase/bin/hbase shell /home/hadoop/git/physical_design/delete_table
0 row(s) in 3.4920 seconds

0 row(s) in 0.7420 seconds

0 row(s) in 0.0580 seconds

+ echo 'sleeping for 300 ...'
sleeping for 300 ...
+ sleep 300
+ false
+ true
+ echo 'creating usertable...'
creating usertable...
+ create_statement='create '\''usertable'\'', { NAME=>'\''family'\'', COMPRESSION=>'\''GZ'\'', CONFIGURATION =>  { '\''hbase.hregion.majorcompaction'\'' => '\''0'\'', '\''hbase.hstore.compactionThreshold'\'' => '\''100000000000000'\'', '\''hbase.server.compactchecker.interval.multiplier'\'' => '\''100000000'\'', '\''hbase.hstore.compaction.max.size'\'' => '\''128'\'' } }, SPLITS => ['\''user1'\'', '\''user2'\'', '\''user3'\'', '\''user4'\'', '\''user5'\'', '\''user6'\'', '\''user7'\'', '\''user8'\'', '\''user9'\'']'
+ echo create ''\''usertable'\'',' '{' 'NAME=>'\''family'\'',' 'COMPRESSION=>'\''GZ'\'',' CONFIGURATION '=>' '{' ''\''hbase.hregion.majorcompaction'\''' '=>' ''\''0'\'',' ''\''hbase.hstore.compactionThreshold'\''' '=>' ''\''100000000000000'\'',' ''\''hbase.server.compactchecker.interval.multiplier'\''' '=>' ''\''100000000'\'',' ''\''hbase.hstore.compaction.max.size'\''' '=>' ''\''128'\''' '}' '},' SPLITS '=>' '['\''user1'\'',' ''\''user2'\'',' ''\''user3'\'',' ''\''user4'\'',' ''\''user5'\'',' ''\''user6'\'',' ''\''user7'\'',' ''\''user8'\'',' ''\''user9'\'']'
+ echo 'exit '
+ scp /home/hadoop/git/physical_design/caseresult/case78/create_1.script hadoop@master:/home/hadoop/git/physical_design/caseresult/case78/create_1.script
+ create_table /home/hadoop/git/physical_design/caseresult/case78/create_1.script
+ echo 'creating table...'
creating table...
+ echo /home/hadoop/git/physical_design/caseresult/case78/create_1.script
/home/hadoop/git/physical_design/caseresult/case78/create_1.script
+ ssh hadoop@master /home/hadoop/hbase/bin/hbase shell /home/hadoop/git/physical_design/caseresult/case78/create_1.script
0 row(s) in 1.7200 seconds

+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ false
+ true
+ echo 'loading data...'
loading data...
+ echo 'starting time: '
starting time: 
++ date +%s
+ echo 1405040362
1405040362
++ echo /home/hadoop/git/physical_design/caseresult/case78/load_1.dat
+ ./ld 10000000 20 /home/hadoop/git/physical_design/caseresult/case78/load_1.dat
Loading workload...
Starting test.
2014-07-10 17:59:22:456 0 sec: 0 operations; 
14/07/10 17:59:22 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/10 17:59:22 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm43.almaden.ibm.com
14/07/10 17:59:22 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/10 17:59:22 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/10 17:59:22 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/10 17:59:22 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf
14/07/10 17:59:22 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/10 17:59:22 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/10 17:59:22 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/10 17:59:22 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/10 17:59:22 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/10 17:59:22 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/10 17:59:22 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/10 17:59:22 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/10 17:59:22 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/10 17:59:22 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x3588d364, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/10 17:59:22 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x3588d364 connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/10 17:59:22 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/10 17:59:22 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/10 17:59:22 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x147249aa629000e, negotiated timeout = 90000
2014-07-10 17:59:32:458 10 sec: 324004 operations; 32390.68 current ops/sec; [INSERT AverageLatency(us)=429.67] 
2014-07-10 17:59:42:458 20 sec: 394444 operations; 7043.3 current ops/sec; [INSERT AverageLatency(us)=290.38] 
2014-07-10 17:59:52:459 30 sec: 394444 operations; 0 current ops/sec;  
2014-07-10 18:00:02:459 40 sec: 394444 operations; 0 current ops/sec;  
2014-07-10 18:00:12:460 50 sec: 394444 operations; 0 current ops/sec;  
14/07/10 18:00:21 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2258 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=568, waitTime=2308, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:24 PDT 2014, retrying after 10003 ms, replay 2258 ops.
2014-07-10 18:00:22:460 60 sec: 452947 operations; 5850.3 current ops/sec; [INSERT AverageLatency(us)=5386.94] 
14/07/10 18:00:25 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2319 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=614, waitTime=2183, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:31 PDT 2014, retrying after 10095 ms, replay 2319 ops.
14/07/10 18:00:25 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2275 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=614, waitTime=2183, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:33 PDT 2014, retrying after 10091 ms, replay 2275 ops.
14/07/10 18:00:25 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2269 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=614, waitTime=2183, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:34 PDT 2014, retrying after 10028 ms, replay 2269 ops.
14/07/10 18:00:25 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2271 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=614, waitTime=2183, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:29 PDT 2014, retrying after 10067 ms, replay 2271 ops.
14/07/10 18:00:25 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2269 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=614, waitTime=2183, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:29 PDT 2014, retrying after 10041 ms, replay 2269 ops.
14/07/10 18:00:25 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2255 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=614, waitTime=2183, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:32 PDT 2014, retrying after 10004 ms, replay 2255 ops.
14/07/10 18:00:25 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2275 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=614, waitTime=2183, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:30 PDT 2014, retrying after 10048 ms, replay 2275 ops.
14/07/10 18:00:25 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2282 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=614, waitTime=2183, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:31 PDT 2014, retrying after 10000 ms, replay 2282 ops.
14/07/10 18:00:25 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2245 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=614, waitTime=2183, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:32 PDT 2014, retrying after 10011 ms, replay 2245 ops.
14/07/10 18:00:25 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2286 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=614, waitTime=2183, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:29 PDT 2014, retrying after 10009 ms, replay 2286 ops.
14/07/10 18:00:25 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2263 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=614, waitTime=2183, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:32 PDT 2014, retrying after 10043 ms, replay 2263 ops.
14/07/10 18:00:27 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2205 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=636, waitTime=2372, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:31 PDT 2014, retrying after 10005 ms, replay 2205 ops.
14/07/10 18:00:27 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2278 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=636, waitTime=2372, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:34 PDT 2014, retrying after 10078 ms, replay 2278 ops.
14/07/10 18:00:27 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2248 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=636, waitTime=2372, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:33 PDT 2014, retrying after 10022 ms, replay 2248 ops.
14/07/10 18:00:27 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2214 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=636, waitTime=2372, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:33 PDT 2014, retrying after 10084 ms, replay 2214 ops.
14/07/10 18:00:27 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2217 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=636, waitTime=2372, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:33 PDT 2014, retrying after 10093 ms, replay 2217 ops.
14/07/10 18:00:27 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2250 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=636, waitTime=2372, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:30 PDT 2014, retrying after 10040 ms, replay 2250 ops.
14/07/10 18:00:27 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2247 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=636, waitTime=2372, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:31 PDT 2014, retrying after 10019 ms, replay 2247 ops.
14/07/10 18:00:27 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2286 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=636, waitTime=2372, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:29 PDT 2014, retrying after 10003 ms, replay 2286 ops.
14/07/10 18:00:27 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2246 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=636, waitTime=2372, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:34 PDT 2014, retrying after 10078 ms, replay 2246 ops.
14/07/10 18:00:27 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2286 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=636, waitTime=2372, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:32 PDT 2014, retrying after 10038 ms, replay 2286 ops.
14/07/10 18:00:27 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2271 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=636, waitTime=2372, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:34 PDT 2014, retrying after 10072 ms, replay 2271 ops.
14/07/10 18:00:27 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2283 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=636, waitTime=2372, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:34 PDT 2014, retrying after 10018 ms, replay 2283 ops.
14/07/10 18:00:27 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2302 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=636, waitTime=2372, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:31 PDT 2014, retrying after 10089 ms, replay 2302 ops.
14/07/10 18:00:28 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2262 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=655, waitTime=2003, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:35 PDT 2014, retrying after 10053 ms, replay 2262 ops.
14/07/10 18:00:28 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2256 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=656, waitTime=2000, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:34 PDT 2014, retrying after 10091 ms, replay 2256 ops.
2014-07-10 18:00:32:460 70 sec: 590607 operations; 13766 current ops/sec; [INSERT AverageLatency(us)=418.72] 
14/07/10 18:00:32 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:24 PDT 2014
14/07/10 18:00:37 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:31 PDT 2014
14/07/10 18:00:37 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:32 PDT 2014
14/07/10 18:00:37 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:32 PDT 2014
14/07/10 18:00:37 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:29 PDT 2014
14/07/10 18:00:37 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:33 PDT 2014
14/07/10 18:00:37 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:31 PDT 2014
14/07/10 18:00:37 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:29 PDT 2014
14/07/10 18:00:37 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:32 PDT 2014
14/07/10 18:00:37 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:34 PDT 2014
14/07/10 18:00:37 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:30 PDT 2014
14/07/10 18:00:37 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:29 PDT 2014
14/07/10 18:00:39 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2247 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=799, waitTime=2421, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:31 PDT 2014, retrying after 10028 ms, replay 2247 ops.
14/07/10 18:00:39 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2283 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=799, waitTime=2421, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:34 PDT 2014, retrying after 10016 ms, replay 2283 ops.
14/07/10 18:00:39 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2250 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=799, waitTime=2421, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:30 PDT 2014, retrying after 10001 ms, replay 2250 ops.
14/07/10 18:00:39 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2214 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=799, waitTime=2421, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:33 PDT 2014, retrying after 10062 ms, replay 2214 ops.
14/07/10 18:00:39 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2286 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=799, waitTime=2421, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:32 PDT 2014, retrying after 10072 ms, replay 2286 ops.
14/07/10 18:00:39 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2278 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=799, waitTime=2421, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:34 PDT 2014, retrying after 10087 ms, replay 2278 ops.
14/07/10 18:00:39 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2248 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=799, waitTime=2421, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:33 PDT 2014, retrying after 10036 ms, replay 2248 ops.
14/07/10 18:00:39 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2205 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=799, waitTime=2421, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:31 PDT 2014, retrying after 10032 ms, replay 2205 ops.
14/07/10 18:00:39 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2271 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=799, waitTime=2421, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:34 PDT 2014, retrying after 10094 ms, replay 2271 ops.
14/07/10 18:00:39 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2286 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=799, waitTime=2421, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:29 PDT 2014, retrying after 10033 ms, replay 2286 ops.
14/07/10 18:00:39 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2246 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=799, waitTime=2421, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:34 PDT 2014, retrying after 10051 ms, replay 2246 ops.
14/07/10 18:00:40 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2302 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=820, waitTime=3150, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:31 PDT 2014, retrying after 10040 ms, replay 2302 ops.
14/07/10 18:00:40 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2217 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=820, waitTime=3150, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:33 PDT 2014, retrying after 10013 ms, replay 2217 ops.
14/07/10 18:00:40 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2262 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=820, waitTime=3150, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:35 PDT 2014, retrying after 10079 ms, replay 2262 ops.
14/07/10 18:00:40 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2256 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=820, waitTime=3150, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:34 PDT 2014, retrying after 10021 ms, replay 2256 ops.
2014-07-10 18:00:42:461 80 sec: 826476 operations; 23584.54 current ops/sec; [INSERT AverageLatency(us)=1639.72] 
14/07/10 18:00:50 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:29 PDT 2014
14/07/10 18:00:50 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:31 PDT 2014
14/07/10 18:00:50 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:30 PDT 2014
14/07/10 18:00:51 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:34 PDT 2014
14/07/10 18:00:51 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:34 PDT 2014
14/07/10 18:00:51 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:31 PDT 2014
14/07/10 18:00:51 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:32 PDT 2014
14/07/10 18:00:51 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:33 PDT 2014
14/07/10 18:00:51 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:34 PDT 2014
14/07/10 18:00:52 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:33 PDT 2014
14/07/10 18:00:52 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 failed 2246 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1019, waitTime=2552, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:34 PDT 2014, retrying after 20034 ms, replay 2246 ops.
2014-07-10 18:00:52:461 90 sec: 1220940 operations; 39446.4 current ops/sec; [INSERT AverageLatency(us)=1314.97] 
14/07/10 18:00:53 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 2262 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1046, waitTime=2064, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:35 PDT 2014, retrying after 20121 ms, replay 2262 ops.
14/07/10 18:00:53 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 2302 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1043, waitTime=2046, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:31 PDT 2014, retrying after 20098 ms, replay 2302 ops.
14/07/10 18:00:53 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 2256 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1043, waitTime=2046, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:34 PDT 2014, retrying after 20030 ms, replay 2256 ops.
14/07/10 18:00:53 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 failed 2217 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1043, waitTime=2046, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:33 PDT 2014, retrying after 20002 ms, replay 2217 ops.
2014-07-10 18:01:02:462 100 sec: 1432260 operations; 21129.89 current ops/sec; [INSERT AverageLatency(us)=405.34] 
2014-07-10 18:01:12:462 110 sec: 1432260 operations; 0 current ops/sec;  
2014-07-10 18:01:22:463 120 sec: 1432260 operations; 0 current ops/sec;  
14/07/10 18:01:28 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 failed 2262 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:35 PDT 2014, retrying after 20181 ms, replay 2262 ops.
14/07/10 18:01:28 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 failed 2256 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:34 PDT 2014, retrying after 20000 ms, replay 2256 ops.
14/07/10 18:01:28 INFO client.AsyncProcess: #18, table=usertable, attempt=13/35 failed 2217 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:33 PDT 2014, retrying after 20054 ms, replay 2217 ops.
14/07/10 18:01:28 INFO client.AsyncProcess: #16, table=usertable, attempt=13/35 failed 2246 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:34 PDT 2014, retrying after 20188 ms, replay 2246 ops.
14/07/10 18:01:28 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 failed 2302 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:31 PDT 2014, retrying after 20176 ms, replay 2302 ops.
2014-07-10 18:01:32:463 130 sec: 1432260 operations; 0 current ops/sec;  
2014-07-10 18:01:42:463 140 sec: 1436956 operations; 469.6 current ops/sec; [INSERT AverageLatency(us)=8650.98] 
14/07/10 18:01:49 INFO client.AsyncProcess: #6, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:34 PDT 2014
14/07/10 18:01:49 INFO client.AsyncProcess: #16, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:34 PDT 2014
14/07/10 18:01:49 INFO client.AsyncProcess: #6, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:35 PDT 2014
14/07/10 18:01:50 INFO client.AsyncProcess: #10, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:31 PDT 2014
14/07/10 18:01:50 INFO client.AsyncProcess: #18, table=usertable, attempt=14/35 failed 2217 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1559, waitTime=2138, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:33 PDT 2014, retrying after 20065 ms, replay 2217 ops.
14/07/10 18:01:52 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2258 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1590, waitTime=2430, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:49 PDT 2014, retrying after 10027 ms, replay 2258 ops.
2014-07-10 18:01:52:464 150 sec: 1620100 operations; 18312.57 current ops/sec; [INSERT AverageLatency(us)=4132.06] 
2014-07-10 18:02:02:464 160 sec: 1685844 operations; 6574.4 current ops/sec; [INSERT AverageLatency(us)=301.78] 
14/07/10 18:02:04 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 2258 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:49 PDT 2014, retrying after 10035 ms, replay 2258 ops.
14/07/10 18:02:04 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2220 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 10041 ms, replay 2220 ops.
14/07/10 18:02:06 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2262 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 10097 ms, replay 2262 ops.
14/07/10 18:02:06 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2250 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:57 PDT 2014, retrying after 10014 ms, replay 2250 ops.
14/07/10 18:02:07 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2306 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 10094 ms, replay 2306 ops.
14/07/10 18:02:07 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2259 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 10054 ms, replay 2259 ops.
14/07/10 18:02:07 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2203 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 10044 ms, replay 2203 ops.
14/07/10 18:02:07 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2336 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:57 PDT 2014, retrying after 10064 ms, replay 2336 ops.
14/07/10 18:02:07 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2242 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 10092 ms, replay 2242 ops.
14/07/10 18:02:07 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2289 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:56 PDT 2014, retrying after 10072 ms, replay 2289 ops.
14/07/10 18:02:07 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2194 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:57 PDT 2014, retrying after 10037 ms, replay 2194 ops.
14/07/10 18:02:08 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2249 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 10037 ms, replay 2249 ops.
14/07/10 18:02:08 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2295 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 10083 ms, replay 2295 ops.
14/07/10 18:02:08 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2331 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:56 PDT 2014, retrying after 10017 ms, replay 2331 ops.
14/07/10 18:02:08 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2234 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:57 PDT 2014, retrying after 10057 ms, replay 2234 ops.
2014-07-10 18:02:12:465 170 sec: 1685844 operations; 0 current ops/sec;  
14/07/10 18:02:12 INFO client.AsyncProcess: #18, table=usertable, attempt=15/35 failed 2217 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1827, waitTime=2620, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:33 PDT 2014, retrying after 20003 ms, replay 2217 ops.
14/07/10 18:02:16 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 failed 2258 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1898, waitTime=2006, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:49 PDT 2014, retrying after 20085 ms, replay 2258 ops.
14/07/10 18:02:16 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2220 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1898, waitTime=2006, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 10093 ms, replay 2220 ops.
14/07/10 18:02:18 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2262 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1924, waitTime=2068, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 10096 ms, replay 2262 ops.
14/07/10 18:02:18 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2250 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1928, waitTime=2135, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:57 PDT 2014, retrying after 10006 ms, replay 2250 ops.
14/07/10 18:02:19 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2203 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1932, waitTime=2303, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 10059 ms, replay 2203 ops.
14/07/10 18:02:19 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2259 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1932, waitTime=2303, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 10079 ms, replay 2259 ops.
14/07/10 18:02:19 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2306 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1932, waitTime=2303, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 10004 ms, replay 2306 ops.
14/07/10 18:02:21 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2336 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:57 PDT 2014, retrying after 10003 ms, replay 2336 ops.
14/07/10 18:02:21 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2194 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:57 PDT 2014, retrying after 10042 ms, replay 2194 ops.
14/07/10 18:02:21 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2249 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 10083 ms, replay 2249 ops.
14/07/10 18:02:21 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2289 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:56 PDT 2014, retrying after 10069 ms, replay 2289 ops.
14/07/10 18:02:21 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 2242 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 10047 ms, replay 2242 ops.
14/07/10 18:02:21 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2331 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:56 PDT 2014, retrying after 10027 ms, replay 2331 ops.
14/07/10 18:02:21 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2295 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 10071 ms, replay 2295 ops.
14/07/10 18:02:21 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2234 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45060 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:57 PDT 2014, retrying after 10085 ms, replay 2234 ops.
2014-07-10 18:02:22:465 180 sec: 1685844 operations; 0 current ops/sec;  
14/07/10 18:02:27 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 failed 2220 ops, last exception: java.io.IOException: Unexpected closed connection on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 20170 ms, replay 2220 ops.
14/07/10 18:02:28 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 2262 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45061 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 20030 ms, replay 2262 ops.
14/07/10 18:02:29 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2250 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45061 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:57 PDT 2014, retrying after 20001 ms, replay 2250 ops.
14/07/10 18:02:29 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 2203 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45061 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 20104 ms, replay 2203 ops.
14/07/10 18:02:31 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2259 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45062 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 20175 ms, replay 2259 ops.
14/07/10 18:02:32 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2234 ops, last exception: java.io.IOException: Unexpected closed connection on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:57 PDT 2014, retrying after 20104 ms, replay 2234 ops.
14/07/10 18:02:32 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 failed 2249 ops, last exception: java.io.IOException: Unexpected closed connection on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 20159 ms, replay 2249 ops.
14/07/10 18:02:32 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 2295 ops, last exception: java.io.IOException: Unexpected closed connection on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 20138 ms, replay 2295 ops.
14/07/10 18:02:32 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 failed 2289 ops, last exception: java.io.IOException: Unexpected closed connection on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:56 PDT 2014, retrying after 20111 ms, replay 2289 ops.
14/07/10 18:02:32 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 2242 ops, last exception: java.io.IOException: Unexpected closed connection on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 20058 ms, replay 2242 ops.
14/07/10 18:02:32 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 failed 2194 ops, last exception: java.io.IOException: Unexpected closed connection on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:57 PDT 2014, retrying after 20118 ms, replay 2194 ops.
14/07/10 18:02:32 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2331 ops, last exception: java.io.IOException: Unexpected closed connection on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:56 PDT 2014, retrying after 20155 ms, replay 2331 ops.
14/07/10 18:02:32 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2336 ops, last exception: java.io.IOException: Unexpected closed connection on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:57 PDT 2014, retrying after 20190 ms, replay 2336 ops.
14/07/10 18:02:32 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2306 ops, last exception: java.io.IOException: Unexpected closed connection on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 20070 ms, replay 2306 ops.
2014-07-10 18:02:32:466 190 sec: 1685844 operations; 0 current ops/sec;  
14/07/10 18:02:32 INFO client.AsyncProcess: #18, table=usertable, attempt=16/35 failed 2217 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45062 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:33 PDT 2014, retrying after 20016 ms, replay 2217 ops.
14/07/10 18:02:36 INFO client.AsyncProcess: #12, table=usertable, attempt=13/35 failed 2258 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:45063 remote=slave1/9.1.143.59:60020] on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:49 PDT 2014, retrying after 20020 ms, replay 2258 ops.
2014-07-10 18:02:42:466 200 sec: 1685844 operations; 0 current ops/sec;  
14/07/10 18:02:49 INFO client.AsyncProcess: #17, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014
14/07/10 18:02:50 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:57 PDT 2014
14/07/10 18:02:50 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 failed 2262 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2164, waitTime=2301, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 20122 ms, replay 2262 ops.
14/07/10 18:02:51 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 failed 2203 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2181, waitTime=2095, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 20048 ms, replay 2203 ops.
2014-07-10 18:02:52:469 210 sec: 1845508 operations; 15961.61 current ops/sec; [INSERT AverageLatency(us)=4420.89] 
14/07/10 18:02:54 INFO client.AsyncProcess: #3, table=usertable, attempt=13/35 failed 2194 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2233, waitTime=2690, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:57 PDT 2014, retrying after 20095 ms, replay 2194 ops.
14/07/10 18:02:54 INFO client.AsyncProcess: #14, table=usertable, attempt=13/35 failed 2249 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2233, waitTime=2690, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 20183 ms, replay 2249 ops.
14/07/10 18:02:54 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 failed 2242 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2233, waitTime=2690, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 20103 ms, replay 2242 ops.
14/07/10 18:02:54 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 failed 2259 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2233, waitTime=2690, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 20131 ms, replay 2259 ops.
14/07/10 18:02:54 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 failed 2295 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2233, waitTime=2690, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 20167 ms, replay 2295 ops.
14/07/10 18:02:54 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 failed 2306 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2233, waitTime=2690, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 20143 ms, replay 2306 ops.
14/07/10 18:02:54 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 failed 2336 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2233, waitTime=2690, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:57 PDT 2014, retrying after 20151 ms, replay 2336 ops.
14/07/10 18:02:54 INFO client.AsyncProcess: #13, table=usertable, attempt=13/35 failed 2289 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2233, waitTime=2690, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:56 PDT 2014, retrying after 20083 ms, replay 2289 ops.
14/07/10 18:02:54 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 failed 2234 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2233, waitTime=2690, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:57 PDT 2014, retrying after 20069 ms, replay 2234 ops.
14/07/10 18:02:54 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 failed 2331 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2233, waitTime=2690, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:56 PDT 2014, retrying after 20176 ms, replay 2331 ops.
14/07/10 18:02:55 INFO client.AsyncProcess: #18, table=usertable, attempt=17/35 failed 2217 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2258, waitTime=2435, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:33 PDT 2014, retrying after 20120 ms, replay 2217 ops.
14/07/10 18:02:58 INFO client.AsyncProcess: #12, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:49 PDT 2014
2014-07-10 18:03:02:469 220 sec: 2089700 operations; 24419.2 current ops/sec; [INSERT AverageLatency(us)=925.35] 
14/07/10 18:03:11 INFO client.AsyncProcess: #20, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014
14/07/10 18:03:12 INFO client.AsyncProcess: #9, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014
2014-07-10 18:03:12:470 230 sec: 2409028 operations; 31929.61 current ops/sec; [INSERT AverageLatency(us)=850.99] 
14/07/10 18:03:15 INFO client.AsyncProcess: #2, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:57 PDT 2014
14/07/10 18:03:15 INFO client.AsyncProcess: #13, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:56 PDT 2014
14/07/10 18:03:16 INFO client.AsyncProcess: #2, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:56 PDT 2014
14/07/10 18:03:16 INFO client.AsyncProcess: #14, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014
14/07/10 18:03:16 INFO client.AsyncProcess: #20, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014
14/07/10 18:03:16 INFO client.AsyncProcess: #2, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:57 PDT 2014
14/07/10 18:03:16 INFO client.AsyncProcess: #3, table=usertable, attempt=14/35 failed 2194 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2600, waitTime=2027, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:57 PDT 2014, retrying after 20013 ms, replay 2194 ops.
14/07/10 18:03:16 INFO client.AsyncProcess: #1, table=usertable, attempt=14/35 failed 2242 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2600, waitTime=2027, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014, retrying after 20119 ms, replay 2242 ops.
14/07/10 18:03:16 INFO client.AsyncProcess: #2, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014
14/07/10 18:03:16 INFO client.AsyncProcess: #2, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014
14/07/10 18:03:17 INFO client.AsyncProcess: #18, table=usertable, attempt=18/35 failed 2217 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2617, waitTime=2096, rpcTimetout=2000 on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:33 PDT 2014, retrying after 20197 ms, replay 2217 ops.
2014-07-10 18:03:22:470 240 sec: 2751836 operations; 34280.8 current ops/sec; [INSERT AverageLatency(us)=2017.24] 
2014-07-10 18:03:32:470 250 sec: 3045612 operations; 29377.6 current ops/sec; [INSERT AverageLatency(us)=591.07] 
14/07/10 18:03:37 INFO client.AsyncProcess: #3, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:57 PDT 2014
14/07/10 18:03:37 INFO client.AsyncProcess: #1, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 18:00:58 PDT 2014
14/07/10 18:03:38 INFO client.AsyncProcess: #18, table=usertable, attempt=19/35 SUCCEEDED on slave1,60020,1405068420563, tracking started Thu Jul 10 17:59:33 PDT 2014
2014-07-10 18:03:42:471 260 sec: 3362316 operations; 31667.23 current ops/sec; [INSERT AverageLatency(us)=2109.05] 
2014-07-10 18:03:52:471 270 sec: 3662860 operations; 30054.4 current ops/sec; [INSERT AverageLatency(us)=719.56] 
2014-07-10 18:04:02:718 280 sec: 4007029 operations; 33590.57 current ops/sec; [INSERT AverageLatency(us)=612.39] 
2014-07-10 18:04:12:718 290 sec: 4301516 operations; 29445.76 current ops/sec; [INSERT AverageLatency(us)=843.3] 
2014-07-10 18:04:22:718 300 sec: 4677196 operations; 37568 current ops/sec; [INSERT AverageLatency(us)=464.84] 
2014-07-10 18:04:32:719 310 sec: 5048180 operations; 37094.69 current ops/sec; [INSERT AverageLatency(us)=528.43] 
2014-07-10 18:04:42:719 320 sec: 5246447 operations; 19826.7 current ops/sec; [INSERT AverageLatency(us)=767.72] 
2014-07-10 18:04:52:720 330 sec: 5513084 operations; 26661.03 current ops/sec; [INSERT AverageLatency(us)=766.37] 
2014-07-10 18:05:02:720 340 sec: 5733796 operations; 22071.2 current ops/sec; [INSERT AverageLatency(us)=598.28] 
2014-07-10 18:05:12:721 350 sec: 5733796 operations; 0 current ops/sec;  
2014-07-10 18:05:22:721 360 sec: 5733796 operations; 0 current ops/sec;  
2014-07-10 18:05:32:722 370 sec: 5890426 operations; 15661.43 current ops/sec; [INSERT AverageLatency(us)=3833.85] 
2014-07-10 18:05:42:722 380 sec: 5940420 operations; 4999.4 current ops/sec; [INSERT AverageLatency(us)=2232.93] 
2014-07-10 18:05:52:723 390 sec: 5940420 operations; 0 current ops/sec;  
2014-07-10 18:06:02:723 400 sec: 6316100 operations; 37568 current ops/sec; [INSERT AverageLatency(us)=1592.31] 
2014-07-10 18:06:12:724 410 sec: 6528095 operations; 21197.38 current ops/sec; [INSERT AverageLatency(us)=603.26] 
2014-07-10 18:06:22:724 420 sec: 6546204 operations; 1810.9 current ops/sec; [INSERT AverageLatency(us)=146.64] 
2014-07-10 18:06:32:724 430 sec: 6546204 operations; 0 current ops/sec;  
2014-07-10 18:06:42:725 440 sec: 6672996 operations; 12677.93 current ops/sec; [INSERT AverageLatency(us)=1726.87] 
2014-07-10 18:06:52:729 450 sec: 7139464 operations; 46628.15 current ops/sec; [INSERT AverageLatency(us)=1380.16] 
2014-07-10 18:07:02:729 460 sec: 7297564 operations; 15810 current ops/sec; [INSERT AverageLatency(us)=316.87] 
2014-07-10 18:07:12:730 470 sec: 7306956 operations; 939.11 current ops/sec; [INSERT AverageLatency(us)=1243.03] 
2014-07-10 18:07:22:730 480 sec: 7587107 operations; 28015.1 current ops/sec; [INSERT AverageLatency(us)=1608.22] 
2014-07-10 18:07:32:731 490 sec: 8047264 operations; 46011.1 current ops/sec; [UPDATE AverageLatency(us)=2783873] [INSERT AverageLatency(us)=623.1] [CLEANUP AverageLatency(us)=2784030] 
2014-07-10 18:07:42:732 500 sec: 8527031 operations; 47971.9 current ops/sec;  [INSERT AverageLatency(us)=362.3]  
2014-07-10 18:07:52:732 510 sec: 8940672 operations; 41364.1 current ops/sec; [UPDATE AverageLatency(us)=5363124] [INSERT AverageLatency(us)=436.04] [CLEANUP AverageLatency(us)=5363706.5] 
2014-07-10 18:08:02:733 520 sec: 9362820 operations; 42210.58 current ops/sec; [UPDATE AverageLatency(us)=4025899] [INSERT AverageLatency(us)=379.26] [CLEANUP AverageLatency(us)=4025912] 
2014-07-10 18:08:12:733 530 sec: 9791643 operations; 42882.3 current ops/sec; [UPDATE AverageLatency(us)=2337879.91] [INSERT AverageLatency(us)=192.65] [CLEANUP AverageLatency(us)=2337891.73] 
2014-07-10 18:08:21:296 538 sec: 10000000 operations; 24335.09 current ops/sec; [UPDATE AverageLatency(us)=725363.2] [INSERT AverageLatency(us)=95.03] [CLEANUP AverageLatency(us)=725374.4] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1405040901
1405040901
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ false
+ false
+ false
+ false
+ false
+ false
+ false
+ false
+ let counter=1+1
+ read line
+ set +x
