++ ls caseresult/ -ltr
++ wc -l
+ filename=case18
+ mkdir caseresult/case18
+ RESULT_DIR=/home/hadoop/git/physical_design/caseresult/case18
+ TEN=10
+ SLEEP_TIME=300
+ YCSB_DIR=/home/hadoop/ycsb-0.1.4
+ number_of_operations=5000000
+ number_of_threads=20
+ number_of_records=5000000
+ output_file_suffix=.dat
+ experiment_list_file=/home/hadoop/git/physical_design/case18.list
+ clean=false
+ create=false
+ load=false
+ random_read=false
+ scan=false
+ all=false
+ for i in '$@'
+ '[' all == all ']'
+ all=true
+ let counter=1
+ cd /home/hadoop/ycsb-0.1.4
++ pwd
+ echo /home/hadoop/ycsb-0.1.4
/home/hadoop/ycsb-0.1.4
+ read line
+ true
+ echo 'droping usertable...'
droping usertable...
+ hbase shell /home/hadoop/git/physical_design/delete_table
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/hadoop/hbase-0.98.3-hadoop1/lib/slf4j-log4j12-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/hadoop/hadoop-1.2.1/lib/slf4j-log4j12-1.4.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
0 row(s) in 37.0880 seconds

0 row(s) in 0.7770 seconds

0 row(s) in 0.0650 seconds

+ echo 'sleeping for 300 ...'
sleeping for 300 ...
+ sleep 300
+ true
+ echo 'creating usertable...'
creating usertable...
+ create_statement='create '\''usertable'\'', { NAME=>'\''family'\'', DATA_BLOCK_ENCODING=>'\''FAST_DIFF'\''}, SPLITS => ['\''user1'\'', '\''user2'\'', '\''user3'\'', '\''user4'\'', '\''user5'\'', '\''user6'\'', '\''user7'\'', '\''user8'\'', '\''user9'\'']'
+ echo create ''\''usertable'\'',' '{' 'NAME=>'\''family'\'',' 'DATA_BLOCK_ENCODING=>'\''FAST_DIFF'\''},' SPLITS '=>' '['\''user1'\'',' ''\''user2'\'',' ''\''user3'\'',' ''\''user4'\'',' ''\''user5'\'',' ''\''user6'\'',' ''\''user7'\'',' ''\''user8'\'',' ''\''user9'\'']'
+ echo 'exit '
+ create_table /home/hadoop/git/physical_design/caseresult/case18/create_1.script
+ echo 'creating table...'
creating table...
+ echo /home/hadoop/git/physical_design/caseresult/case18/create_1.script
/home/hadoop/git/physical_design/caseresult/case18/create_1.script
+ hbase shell /home/hadoop/git/physical_design/caseresult/case18/create_1.script
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/hadoop/hbase-0.98.3-hadoop1/lib/slf4j-log4j12-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/hadoop/hadoop-1.2.1/lib/slf4j-log4j12-1.4.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
0 row(s) in 1.6380 seconds

+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo 'loading data...'
loading data...
+ echo 'starting time: '
starting time: 
++ date +%s
+ echo 1404658478
1404658478
++ echo /home/hadoop/git/physical_design/caseresult/case18/load_1.dat
+ ./ld 5000000 20 /home/hadoop/git/physical_design/caseresult/case18/load_1.dat
Loading workload...
Starting test.
2014-07-06 07:54:39:536 0 sec: 0 operations; 
14/07/06 07:54:39 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/06 07:54:40 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/06 07:54:40 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/06 07:54:40 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/06 07:54:40 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/06 07:54:40 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/06 07:54:40 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/06 07:54:40 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/06 07:54:40 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/06 07:54:40 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/06 07:54:40 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/06 07:54:40 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/06 07:54:40 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/06 07:54:40 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/06 07:54:40 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/06 07:54:40 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0xc2c915f, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/06 07:54:40 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0xc2c915f connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/06 07:54:40 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/06 07:54:40 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/06 07:54:40 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x1470c25ee7b000f, negotiated timeout = 90000
2014-07-06 07:54:49:539 10 sec: 286436 operations; 28580.72 current ops/sec; [INSERT AverageLatency(us)=381.8] 
2014-07-06 07:54:59:541 20 sec: 300524 operations; 1408.52 current ops/sec; [INSERT AverageLatency(us)=185.19] 
2014-07-06 07:55:09:541 30 sec: 300524 operations; 0 current ops/sec;  
2014-07-06 07:55:19:542 40 sec: 300524 operations; 0 current ops/sec;  
2014-07-06 07:55:29:543 50 sec: 615156 operations; 31460.05 current ops/sec; [INSERT AverageLatency(us)=2106.03] 
2014-07-06 07:55:39:544 60 sec: 943876 operations; 32872 current ops/sec; [INSERT AverageLatency(us)=1054.67] 
2014-07-06 07:55:49:544 70 sec: 1202156 operations; 25825.42 current ops/sec; [INSERT AverageLatency(us)=726.55] 
2014-07-06 07:55:59:545 80 sec: 1202156 operations; 0 current ops/sec;  
2014-07-06 07:56:09:546 90 sec: 1347732 operations; 14556.14 current ops/sec; [INSERT AverageLatency(us)=1880] 
2014-07-06 07:56:19:546 100 sec: 1347732 operations; 0 current ops/sec;  
2014-07-06 07:56:29:547 110 sec: 1347732 operations; 0 current ops/sec;  
2014-07-06 07:56:39:548 120 sec: 1347732 operations; 0 current ops/sec;  
2014-07-06 07:56:49:548 130 sec: 1347732 operations; 0 current ops/sec;  
2014-07-06 07:56:59:549 140 sec: 1347732 operations; 0 current ops/sec;  
14/07/06 07:57:07 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 1860 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:45 PDT 2014, retrying after 10048 ms, replay 1860 ops.
14/07/06 07:57:07 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 1870 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014, retrying after 10092 ms, replay 1870 ops.
14/07/06 07:57:07 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 1872 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014, retrying after 10022 ms, replay 1872 ops.
14/07/06 07:57:07 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 1832 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014, retrying after 10041 ms, replay 1832 ops.
14/07/06 07:57:07 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 1877 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014, retrying after 10085 ms, replay 1877 ops.
14/07/06 07:57:07 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 1869 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:45 PDT 2014, retrying after 10005 ms, replay 1869 ops.
14/07/06 07:57:09 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 1853 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014, retrying after 10042 ms, replay 1853 ops.
14/07/06 07:57:09 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 1847 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 10073 ms, replay 1847 ops.
14/07/06 07:57:09 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 1821 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 10006 ms, replay 1821 ops.
14/07/06 07:57:09 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 1819 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 10022 ms, replay 1819 ops.
14/07/06 07:57:09 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 1874 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 10078 ms, replay 1874 ops.
14/07/06 07:57:09 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 1895 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014, retrying after 10095 ms, replay 1895 ops.
14/07/06 07:57:09 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 1902 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014, retrying after 10042 ms, replay 1902 ops.
14/07/06 07:57:09 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 1857 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014, retrying after 10029 ms, replay 1857 ops.
14/07/06 07:57:09 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 1896 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014, retrying after 10090 ms, replay 1896 ops.
14/07/06 07:57:09 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 1774 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 10073 ms, replay 1774 ops.
2014-07-06 07:57:09:549 150 sec: 1347732 operations; 0 current ops/sec;  
14/07/06 07:57:13 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 1878 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1291, waitTime=2538, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 10051 ms, replay 1878 ops.
14/07/06 07:57:13 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 1875 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1291, waitTime=2538, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 10023 ms, replay 1875 ops.
14/07/06 07:57:13 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 1866 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1291, waitTime=2538, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:06 PDT 2014, retrying after 10073 ms, replay 1866 ops.
14/07/06 07:57:13 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 1872 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1291, waitTime=2538, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 10074 ms, replay 1872 ops.
14/07/06 07:57:13 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 1875 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1291, waitTime=2538, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 10031 ms, replay 1875 ops.
14/07/06 07:57:13 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 1889 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1291, waitTime=2538, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:05 PDT 2014, retrying after 10062 ms, replay 1889 ops.
14/07/06 07:57:13 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 1870 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1291, waitTime=2538, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 10097 ms, replay 1870 ops.
14/07/06 07:57:13 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 1890 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1291, waitTime=2538, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 10009 ms, replay 1890 ops.
14/07/06 07:57:13 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 1890 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1291, waitTime=2538, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:06 PDT 2014, retrying after 10094 ms, replay 1890 ops.
14/07/06 07:57:13 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 1861 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1291, waitTime=2538, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 10038 ms, replay 1861 ops.
14/07/06 07:57:13 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 1834 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1291, waitTime=2538, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:06 PDT 2014, retrying after 10019 ms, replay 1834 ops.
14/07/06 07:57:13 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 1843 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1291, waitTime=2538, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:05 PDT 2014, retrying after 10010 ms, replay 1843 ops.
14/07/06 07:57:13 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 1853 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1291, waitTime=2538, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:06 PDT 2014, retrying after 10079 ms, replay 1853 ops.
14/07/06 07:57:13 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 1843 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1291, waitTime=2538, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:06 PDT 2014, retrying after 10035 ms, replay 1843 ops.
14/07/06 07:57:13 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 1891 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1291, waitTime=2538, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:06 PDT 2014, retrying after 10052 ms, replay 1891 ops.
14/07/06 07:57:13 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 1863 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1291, waitTime=2538, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:06 PDT 2014, retrying after 10086 ms, replay 1863 ops.
2014-07-06 07:57:19:550 160 sec: 1347732 operations; 0 current ops/sec;  
14/07/06 07:57:20 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 1878 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1309, waitTime=3171, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:08 PDT 2014, retrying after 10052 ms, replay 1878 ops.
14/07/06 07:57:20 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 1832 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1309, waitTime=3171, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014, retrying after 10032 ms, replay 1832 ops.
14/07/06 07:57:20 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 1866 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1309, waitTime=3171, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:08 PDT 2014, retrying after 10073 ms, replay 1866 ops.
14/07/06 07:57:20 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 1860 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1309, waitTime=3171, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:45 PDT 2014, retrying after 10010 ms, replay 1860 ops.
14/07/06 07:57:20 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 1847 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1309, waitTime=3171, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:07 PDT 2014, retrying after 10038 ms, replay 1847 ops.
14/07/06 07:57:20 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 1872 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1309, waitTime=3171, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014, retrying after 10046 ms, replay 1872 ops.
14/07/06 07:57:20 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 1878 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1309, waitTime=3171, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:08 PDT 2014, retrying after 10004 ms, replay 1878 ops.
14/07/06 07:57:20 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 1853 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1309, waitTime=3171, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:08 PDT 2014, retrying after 10012 ms, replay 1853 ops.
14/07/06 07:57:20 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 1869 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1309, waitTime=3171, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:45 PDT 2014, retrying after 10072 ms, replay 1869 ops.
14/07/06 07:57:20 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 1880 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1309, waitTime=3171, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:07 PDT 2014, retrying after 10063 ms, replay 1880 ops.
14/07/06 07:57:20 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 1877 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1309, waitTime=3171, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014, retrying after 10009 ms, replay 1877 ops.
14/07/06 07:57:20 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 1870 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1309, waitTime=3171, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014, retrying after 10043 ms, replay 1870 ops.
14/07/06 07:57:20 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 1859 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1309, waitTime=3171, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:07 PDT 2014, retrying after 10074 ms, replay 1859 ops.
14/07/06 07:57:21 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 1821 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1322, waitTime=2068, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 10098 ms, replay 1821 ops.
14/07/06 07:57:21 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 1819 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1322, waitTime=2068, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 10023 ms, replay 1819 ops.
14/07/06 07:57:21 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 1853 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1322, waitTime=2068, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014, retrying after 10023 ms, replay 1853 ops.
14/07/06 07:57:21 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 1857 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1322, waitTime=2068, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014, retrying after 10048 ms, replay 1857 ops.
14/07/06 07:57:21 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 1902 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1322, waitTime=2068, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014, retrying after 10047 ms, replay 1902 ops.
14/07/06 07:57:21 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 1847 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1322, waitTime=2068, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 10079 ms, replay 1847 ops.
14/07/06 07:57:21 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 1874 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1328, waitTime=2001, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 10083 ms, replay 1874 ops.
14/07/06 07:57:21 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014
14/07/06 07:57:21 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 1774 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1329, waitTime=2532, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 10034 ms, replay 1774 ops.
14/07/06 07:57:21 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 1896 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1329, waitTime=2532, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014, retrying after 10014 ms, replay 1896 ops.
14/07/06 07:57:25 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:06 PDT 2014
14/07/06 07:57:25 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014
14/07/06 07:57:25 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:05 PDT 2014
14/07/06 07:57:25 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:05 PDT 2014
14/07/06 07:57:25 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014
14/07/06 07:57:25 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014
14/07/06 07:57:25 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014
14/07/06 07:57:25 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:06 PDT 2014
14/07/06 07:57:25 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:06 PDT 2014
14/07/06 07:57:25 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:06 PDT 2014
14/07/06 07:57:25 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014
14/07/06 07:57:25 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014
14/07/06 07:57:25 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:06 PDT 2014
14/07/06 07:57:25 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014
14/07/06 07:57:25 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:06 PDT 2014
14/07/06 07:57:25 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:06 PDT 2014
2014-07-06 07:57:29:551 170 sec: 1404084 operations; 5635.2 current ops/sec; [INSERT AverageLatency(us)=5841.48] 
14/07/06 07:57:34 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 1860 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:45 PDT 2014, retrying after 20122 ms, replay 1860 ops.
14/07/06 07:57:34 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 failed 1870 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014, retrying after 20087 ms, replay 1870 ops.
14/07/06 07:57:34 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 failed 1869 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:45 PDT 2014, retrying after 20128 ms, replay 1869 ops.
14/07/06 07:57:34 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 1877 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014, retrying after 20119 ms, replay 1877 ops.
14/07/06 07:57:34 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 1878 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:08 PDT 2014, retrying after 10088 ms, replay 1878 ops.
14/07/06 07:57:34 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 failed 1819 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 20067 ms, replay 1819 ops.
14/07/06 07:57:34 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 1902 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014, retrying after 20024 ms, replay 1902 ops.
14/07/06 07:57:34 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 1859 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:07 PDT 2014, retrying after 10011 ms, replay 1859 ops.
14/07/06 07:57:34 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 1878 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:08 PDT 2014, retrying after 10041 ms, replay 1878 ops.
14/07/06 07:57:34 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 1853 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:08 PDT 2014, retrying after 10086 ms, replay 1853 ops.
14/07/06 07:57:34 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 failed 1896 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014, retrying after 20116 ms, replay 1896 ops.
14/07/06 07:57:34 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 1872 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014, retrying after 20151 ms, replay 1872 ops.
14/07/06 07:57:34 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 1866 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:08 PDT 2014, retrying after 10068 ms, replay 1866 ops.
14/07/06 07:57:34 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 1853 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014, retrying after 20181 ms, replay 1853 ops.
14/07/06 07:57:34 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 1874 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 20156 ms, replay 1874 ops.
14/07/06 07:57:34 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 1880 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:07 PDT 2014, retrying after 10078 ms, replay 1880 ops.
14/07/06 07:57:34 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 1847 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:07 PDT 2014, retrying after 10080 ms, replay 1847 ops.
14/07/06 07:57:34 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 failed 1832 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014, retrying after 20148 ms, replay 1832 ops.
14/07/06 07:57:34 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 failed 1857 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014, retrying after 20183 ms, replay 1857 ops.
14/07/06 07:57:34 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 failed 1821 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 20197 ms, replay 1821 ops.
14/07/06 07:57:34 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 failed 1774 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 20012 ms, replay 1774 ops.
14/07/06 07:57:34 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 1847 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 20058 ms, replay 1847 ops.
2014-07-06 07:57:39:551 180 sec: 1498004 operations; 9391.06 current ops/sec; [INSERT AverageLatency(us)=302.38] 
14/07/06 07:57:47 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 1859 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1509, waitTime=3493, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:07 PDT 2014, retrying after 20124 ms, replay 1859 ops.
14/07/06 07:57:47 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 1853 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1509, waitTime=3493, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:08 PDT 2014, retrying after 20134 ms, replay 1853 ops.
14/07/06 07:57:47 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 failed 1878 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1509, waitTime=3493, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:08 PDT 2014, retrying after 20132 ms, replay 1878 ops.
14/07/06 07:57:47 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 failed 1880 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1509, waitTime=3493, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:07 PDT 2014, retrying after 20038 ms, replay 1880 ops.
14/07/06 07:57:47 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 1866 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1509, waitTime=3493, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:08 PDT 2014, retrying after 20175 ms, replay 1866 ops.
14/07/06 07:57:47 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 1878 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1509, waitTime=3493, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:08 PDT 2014, retrying after 20149 ms, replay 1878 ops.
14/07/06 07:57:47 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 1847 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1509, waitTime=3493, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:07 PDT 2014, retrying after 20146 ms, replay 1847 ops.
2014-07-06 07:57:49:552 190 sec: 1498004 operations; 0 current ops/sec;  
14/07/06 07:57:56 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 failed 1902 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1580, waitTime=2139, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014, retrying after 20017 ms, replay 1902 ops.
14/07/06 07:57:56 INFO client.AsyncProcess: #17, table=usertable, attempt=13/35 failed 1774 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1580, waitTime=2139, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 20003 ms, replay 1774 ops.
14/07/06 07:57:56 INFO client.AsyncProcess: #7, table=usertable, attempt=13/35 failed 1870 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1580, waitTime=2139, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014, retrying after 20026 ms, replay 1870 ops.
14/07/06 07:57:56 INFO client.AsyncProcess: #3, table=usertable, attempt=13/35 failed 1869 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1580, waitTime=2139, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:45 PDT 2014, retrying after 20003 ms, replay 1869 ops.
14/07/06 07:57:56 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 failed 1847 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1580, waitTime=2139, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 20188 ms, replay 1847 ops.
14/07/06 07:57:56 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 failed 1874 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1580, waitTime=2139, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 20129 ms, replay 1874 ops.
14/07/06 07:57:56 INFO client.AsyncProcess: #19, table=usertable, attempt=13/35 failed 1896 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1580, waitTime=2139, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014, retrying after 20189 ms, replay 1896 ops.
14/07/06 07:57:56 INFO client.AsyncProcess: #8, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014
14/07/06 07:57:56 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 failed 1877 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1580, waitTime=2139, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014, retrying after 20100 ms, replay 1877 ops.
14/07/06 07:57:56 INFO client.AsyncProcess: #5, table=usertable, attempt=13/35 failed 1832 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1580, waitTime=2139, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014, retrying after 20130 ms, replay 1832 ops.
14/07/06 07:57:56 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 failed 1872 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1580, waitTime=2139, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014, retrying after 20099 ms, replay 1872 ops.
14/07/06 07:57:56 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 failed 1860 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1580, waitTime=2139, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:45 PDT 2014, retrying after 20040 ms, replay 1860 ops.
14/07/06 07:57:56 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014
14/07/06 07:57:56 INFO client.AsyncProcess: #12, table=usertable, attempt=13/35 failed 1821 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1593, waitTime=2270, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 20155 ms, replay 1821 ops.
14/07/06 07:57:56 INFO client.AsyncProcess: #18, table=usertable, attempt=13/35 failed 1857 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1593, waitTime=2270, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014, retrying after 20043 ms, replay 1857 ops.
2014-07-06 07:57:59:552 200 sec: 1559052 operations; 6104.8 current ops/sec; [INSERT AverageLatency(us)=3734.39] 
14/07/06 07:58:09 INFO client.AsyncProcess: #14, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:07 PDT 2014
2014-07-06 07:58:09:649 210 sec: 1730151 operations; 16945.53 current ops/sec; [INSERT AverageLatency(us)=927.12] 
14/07/06 07:58:09 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:08 PDT 2014
14/07/06 07:58:09 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:07 PDT 2014
14/07/06 07:58:09 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:07 PDT 2014
14/07/06 07:58:09 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:08 PDT 2014
14/07/06 07:58:09 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:08 PDT 2014
14/07/06 07:58:09 INFO client.AsyncProcess: #14, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:08 PDT 2014
14/07/06 07:58:18 INFO client.AsyncProcess: #17, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014
14/07/06 07:58:18 INFO client.AsyncProcess: #3, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:45 PDT 2014
14/07/06 07:58:18 INFO client.AsyncProcess: #15, table=usertable, attempt=14/35 failed 1902 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1784, waitTime=2192, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014, retrying after 20151 ms, replay 1902 ops.
14/07/06 07:58:18 INFO client.AsyncProcess: #11, table=usertable, attempt=14/35 failed 1860 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1784, waitTime=2192, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:45 PDT 2014, retrying after 20176 ms, replay 1860 ops.
14/07/06 07:58:18 INFO client.AsyncProcess: #7, table=usertable, attempt=14/35 failed 1870 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1784, waitTime=2192, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014, retrying after 20079 ms, replay 1870 ops.
14/07/06 07:58:19 INFO client.AsyncProcess: #19, table=usertable, attempt=14/35 failed 1896 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1789, waitTime=2627, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014, retrying after 20156 ms, replay 1896 ops.
14/07/06 07:58:19 INFO client.AsyncProcess: #1, table=usertable, attempt=14/35 failed 1847 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1789, waitTime=2627, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 20127 ms, replay 1847 ops.
14/07/06 07:58:19 INFO client.AsyncProcess: #9, table=usertable, attempt=14/35 failed 1877 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1789, waitTime=2627, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014, retrying after 20118 ms, replay 1877 ops.
14/07/06 07:58:19 INFO client.AsyncProcess: #12, table=usertable, attempt=14/35 failed 1821 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1789, waitTime=2627, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 20108 ms, replay 1821 ops.
14/07/06 07:58:19 INFO client.AsyncProcess: #10, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014
14/07/06 07:58:19 INFO client.AsyncProcess: #18, table=usertable, attempt=14/35 failed 1857 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1789, waitTime=2627, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014, retrying after 20119 ms, replay 1857 ops.
14/07/06 07:58:19 INFO client.AsyncProcess: #10, table=usertable, attempt=14/35 failed 1874 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1789, waitTime=2627, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 20077 ms, replay 1874 ops.
14/07/06 07:58:19 INFO client.AsyncProcess: #5, table=usertable, attempt=14/35 failed 1832 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1789, waitTime=2627, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014, retrying after 20048 ms, replay 1832 ops.
2014-07-06 07:58:19:651 220 sec: 1934414 operations; 20422.22 current ops/sec; [INSERT AverageLatency(us)=2837.55] 
2014-07-06 07:58:29:651 230 sec: 2178924 operations; 24451 current ops/sec; [INSERT AverageLatency(us)=405.73] 
2014-07-06 07:58:39:652 240 sec: 2394940 operations; 21599.44 current ops/sec; [INSERT AverageLatency(us)=442.63] 
14/07/06 07:58:42 INFO client.AsyncProcess: #11, table=usertable, attempt=15/35 failed 1860 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:45 PDT 2014, retrying after 20081 ms, replay 1860 ops.
14/07/06 07:58:42 INFO client.AsyncProcess: #9, table=usertable, attempt=15/35 failed 1877 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014, retrying after 20106 ms, replay 1877 ops.
14/07/06 07:58:42 INFO client.AsyncProcess: #7, table=usertable, attempt=15/35 failed 1870 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014, retrying after 20042 ms, replay 1870 ops.
14/07/06 07:58:42 INFO client.AsyncProcess: #5, table=usertable, attempt=15/35 failed 1832 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014, retrying after 20061 ms, replay 1832 ops.
14/07/06 07:58:42 INFO client.AsyncProcess: #15, table=usertable, attempt=15/35 failed 1902 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014, retrying after 20185 ms, replay 1902 ops.
14/07/06 07:58:42 INFO client.AsyncProcess: #18, table=usertable, attempt=15/35 failed 1857 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014, retrying after 20198 ms, replay 1857 ops.
14/07/06 07:58:42 INFO client.AsyncProcess: #12, table=usertable, attempt=15/35 failed 1821 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 20010 ms, replay 1821 ops.
14/07/06 07:58:42 INFO client.AsyncProcess: #10, table=usertable, attempt=15/35 failed 1874 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 20052 ms, replay 1874 ops.
14/07/06 07:58:42 INFO client.AsyncProcess: #19, table=usertable, attempt=15/35 failed 1896 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014, retrying after 20172 ms, replay 1896 ops.
14/07/06 07:58:42 INFO client.AsyncProcess: #1, table=usertable, attempt=15/35 failed 1847 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 20111 ms, replay 1847 ops.
2014-07-06 07:58:49:653 250 sec: 2452405 operations; 5745.93 current ops/sec; [INSERT AverageLatency(us)=249.6] 
2014-07-06 07:58:59:654 260 sec: 2452405 operations; 0 current ops/sec;  
14/07/06 07:59:04 INFO client.AsyncProcess: #12, table=usertable, attempt=16/35 failed 1821 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2292, waitTime=2031, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 20139 ms, replay 1821 ops.
14/07/06 07:59:04 INFO client.AsyncProcess: #7, table=usertable, attempt=16/35 failed 1870 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2293, waitTime=2027, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014, retrying after 20044 ms, replay 1870 ops.
14/07/06 07:59:04 INFO client.AsyncProcess: #5, table=usertable, attempt=16/35 failed 1832 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2293, waitTime=2027, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014, retrying after 20191 ms, replay 1832 ops.
14/07/06 07:59:04 INFO client.AsyncProcess: #10, table=usertable, attempt=16/35 failed 1874 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2293, waitTime=2027, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 20003 ms, replay 1874 ops.
14/07/06 07:59:04 INFO client.AsyncProcess: #9, table=usertable, attempt=16/35 failed 1877 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2296, waitTime=2113, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014, retrying after 20153 ms, replay 1877 ops.
14/07/06 07:59:04 INFO client.AsyncProcess: #11, table=usertable, attempt=16/35 failed 1860 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2296, waitTime=2113, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:45 PDT 2014, retrying after 20163 ms, replay 1860 ops.
14/07/06 07:59:04 INFO client.AsyncProcess: #1, table=usertable, attempt=16/35 failed 1847 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2296, waitTime=2113, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014, retrying after 20027 ms, replay 1847 ops.
14/07/06 07:59:04 INFO client.AsyncProcess: #15, table=usertable, attempt=16/35 failed 1902 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2296, waitTime=2113, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014, retrying after 20001 ms, replay 1902 ops.
14/07/06 07:59:04 INFO client.AsyncProcess: #19, table=usertable, attempt=16/35 failed 1896 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2296, waitTime=2113, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014, retrying after 20068 ms, replay 1896 ops.
14/07/06 07:59:04 INFO client.AsyncProcess: #18, table=usertable, attempt=16/35 failed 1857 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2301, waitTime=2002, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014, retrying after 20043 ms, replay 1857 ops.
2014-07-06 07:59:09:654 270 sec: 2452405 operations; 0 current ops/sec;  
2014-07-06 07:59:19:655 280 sec: 2594816 operations; 14239.68 current ops/sec; [UPDATE AverageLatency(us)=38774756] [INSERT AverageLatency(us)=2501.69] [CLEANUP AverageLatency(us)=38775040] 
14/07/06 07:59:25 INFO client.AsyncProcess: #12, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014
14/07/06 07:59:25 INFO client.AsyncProcess: #7, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014
14/07/06 07:59:25 INFO client.AsyncProcess: #10, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014
14/07/06 07:59:25 INFO client.AsyncProcess: #11, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:45 PDT 2014
14/07/06 07:59:25 INFO client.AsyncProcess: #1, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:56:03 PDT 2014
14/07/06 07:59:25 INFO client.AsyncProcess: #18, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014
14/07/06 07:59:25 INFO client.AsyncProcess: #5, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014
14/07/06 07:59:25 INFO client.AsyncProcess: #15, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014
14/07/06 07:59:25 INFO client.AsyncProcess: #9, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:46 PDT 2014
14/07/06 07:59:25 INFO client.AsyncProcess: #19, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 07:55:48 PDT 2014
2014-07-06 07:59:29:656 290 sec: 2898525 operations; 30367.86 current ops/sec;  [INSERT AverageLatency(us)=7182.5]  
2014-07-06 07:59:39:699 300 sec: 3068195 operations; 16894.35 current ops/sec;  [INSERT AverageLatency(us)=951.11]  
2014-07-06 07:59:49:700 310 sec: 3297441 operations; 22922.31 current ops/sec; [UPDATE AverageLatency(us)=9164534.5] [INSERT AverageLatency(us)=763.1] [CLEANUP AverageLatency(us)=9164850.5] 
2014-07-06 07:59:59:702 320 sec: 3527545 operations; 23005.8 current ops/sec; [UPDATE AverageLatency(us)=8358522.5] [INSERT AverageLatency(us)=695.01] [CLEANUP AverageLatency(us)=8365869.5] 
2014-07-06 08:00:09:703 330 sec: 3717611 operations; 19004.7 current ops/sec;  [INSERT AverageLatency(us)=664.39]  
2014-07-06 08:00:19:704 340 sec: 3959333 operations; 24172.2 current ops/sec; [UPDATE AverageLatency(us)=6436760.25] [INSERT AverageLatency(us)=573.53] [CLEANUP AverageLatency(us)=6436792] 
2014-07-06 08:00:29:704 350 sec: 4194133 operations; 23477.65 current ops/sec;  [INSERT AverageLatency(us)=402.75]  
2014-07-06 08:00:39:712 360 sec: 4227005 operations; 3284.57 current ops/sec;  [INSERT AverageLatency(us)=221.09]  
2014-07-06 08:00:49:716 370 sec: 4227005 operations; 0 current ops/sec;    
2014-07-06 08:00:59:717 380 sec: 4227005 operations; 0 current ops/sec;    
2014-07-06 08:01:09:718 390 sec: 4227005 operations; 0 current ops/sec;    
14/07/06 08:01:19 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 1864 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:47534 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:26 PDT 2014, retrying after 10037 ms, replay 1864 ops.
14/07/06 08:01:19 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 1865 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3394, waitTime=2264, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:25 PDT 2014, retrying after 10072 ms, replay 1865 ops.
14/07/06 08:01:19 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 1861 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3394, waitTime=2264, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:26 PDT 2014, retrying after 10084 ms, replay 1861 ops.
14/07/06 08:01:19 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 1866 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3394, waitTime=2264, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:26 PDT 2014, retrying after 10024 ms, replay 1866 ops.
14/07/06 08:01:19 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 1894 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3394, waitTime=2264, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:26 PDT 2014, retrying after 10043 ms, replay 1894 ops.
14/07/06 08:01:19 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 1835 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3394, waitTime=2264, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:25 PDT 2014, retrying after 10073 ms, replay 1835 ops.
14/07/06 08:01:19 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 1901 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3394, waitTime=2264, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:26 PDT 2014, retrying after 10070 ms, replay 1901 ops.
14/07/06 08:01:19 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 1873 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3394, waitTime=2264, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:26 PDT 2014, retrying after 10088 ms, replay 1873 ops.
14/07/06 08:01:19 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 1871 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3394, waitTime=2264, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:25 PDT 2014, retrying after 10064 ms, replay 1871 ops.
14/07/06 08:01:19 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 1871 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3394, waitTime=2264, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:25 PDT 2014, retrying after 10000 ms, replay 1871 ops.
14/07/06 08:01:19 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 1856 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3394, waitTime=2264, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:27 PDT 2014, retrying after 10001 ms, replay 1856 ops.
2014-07-06 08:01:19:718 400 sec: 4227005 operations; 0 current ops/sec;    
14/07/06 08:01:29 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:26 PDT 2014
2014-07-06 08:01:29:719 410 sec: 4231701 operations; 469.55 current ops/sec;  [INSERT AverageLatency(us)=12561.56]  
14/07/06 08:01:31 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 1871 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:48298 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:25 PDT 2014, retrying after 10084 ms, replay 1871 ops.
14/07/06 08:01:31 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 1866 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:48298 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:26 PDT 2014, retrying after 10034 ms, replay 1866 ops.
14/07/06 08:01:31 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 1856 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:48298 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:27 PDT 2014, retrying after 10082 ms, replay 1856 ops.
14/07/06 08:01:32 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 1873 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3410, waitTime=2658, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:26 PDT 2014, retrying after 10088 ms, replay 1873 ops.
14/07/06 08:01:32 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 1861 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3410, waitTime=2658, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:26 PDT 2014, retrying after 10090 ms, replay 1861 ops.
14/07/06 08:01:32 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 1871 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3410, waitTime=2658, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:25 PDT 2014, retrying after 10080 ms, replay 1871 ops.
14/07/06 08:01:32 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 1865 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3410, waitTime=2658, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:25 PDT 2014, retrying after 10089 ms, replay 1865 ops.
14/07/06 08:01:32 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 1894 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3410, waitTime=2658, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:26 PDT 2014, retrying after 10011 ms, replay 1894 ops.
14/07/06 08:01:32 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 1901 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3410, waitTime=2658, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:26 PDT 2014, retrying after 10084 ms, replay 1901 ops.
14/07/06 08:01:32 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 1835 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3410, waitTime=2658, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:25 PDT 2014, retrying after 10034 ms, replay 1835 ops.
2014-07-06 08:01:39:720 420 sec: 4298558 operations; 6685.03 current ops/sec; [UPDATE AverageLatency(us)=491013] [INSERT AverageLatency(us)=116.09] [CLEANUP AverageLatency(us)=491035] 
14/07/06 08:01:43 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:26 PDT 2014
14/07/06 08:01:43 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:27 PDT 2014
14/07/06 08:01:43 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 1871 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3456, waitTime=2068, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:25 PDT 2014, retrying after 20087 ms, replay 1871 ops.
14/07/06 08:01:44 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:25 PDT 2014
14/07/06 08:01:44 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:26 PDT 2014
14/07/06 08:01:46 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 failed 1871 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:48298 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:25 PDT 2014, retrying after 20118 ms, replay 1871 ops.
14/07/06 08:01:46 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 1901 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:48298 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:26 PDT 2014, retrying after 20147 ms, replay 1901 ops.
14/07/06 08:01:46 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 1865 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:48298 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:25 PDT 2014, retrying after 20002 ms, replay 1865 ops.
14/07/06 08:01:46 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 failed 1873 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:48298 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:26 PDT 2014, retrying after 20045 ms, replay 1873 ops.
14/07/06 08:01:46 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 failed 1861 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:48298 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:26 PDT 2014, retrying after 20098 ms, replay 1861 ops.
2014-07-06 08:01:49:721 430 sec: 4368998 operations; 7043.3 current ops/sec;  [INSERT AverageLatency(us)=4337.97]  
2014-07-06 08:01:59:722 440 sec: 4368998 operations; 0 current ops/sec;    
14/07/06 08:02:06 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:25 PDT 2014
14/07/06 08:02:08 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 failed 1865 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:48298 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:25 PDT 2014, retrying after 20125 ms, replay 1865 ops.
14/07/06 08:02:08 INFO client.AsyncProcess: #7, table=usertable, attempt=13/35 failed 1873 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:48298 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:26 PDT 2014, retrying after 20025 ms, replay 1873 ops.
14/07/06 08:02:08 INFO client.AsyncProcess: #3, table=usertable, attempt=13/35 failed 1861 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:48298 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:26 PDT 2014, retrying after 20022 ms, replay 1861 ops.
14/07/06 08:02:08 INFO client.AsyncProcess: #12, table=usertable, attempt=13/35 failed 1871 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3615, waitTime=2230, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:25 PDT 2014, retrying after 20094 ms, replay 1871 ops.
14/07/06 08:02:08 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 failed 1901 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3615, waitTime=2230, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:26 PDT 2014, retrying after 20186 ms, replay 1901 ops.
2014-07-06 08:02:09:722 450 sec: 4383086 operations; 1408.8 current ops/sec;  [INSERT AverageLatency(us)=7020.39]  
2014-07-06 08:02:19:723 460 sec: 4632144 operations; 24903.31 current ops/sec; [UPDATE AverageLatency(us)=990190] [INSERT AverageLatency(us)=578.77] [CLEANUP AverageLatency(us)=990217] 
14/07/06 08:02:28 INFO client.AsyncProcess: #7, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:26 PDT 2014
14/07/06 08:02:28 INFO client.AsyncProcess: #3, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:26 PDT 2014
14/07/06 08:02:28 INFO client.AsyncProcess: #1, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:25 PDT 2014
14/07/06 08:02:28 INFO client.AsyncProcess: #12, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:25 PDT 2014
14/07/06 08:02:29 INFO client.AsyncProcess: #10, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404658118727, tracking started Sun Jul 06 08:00:26 PDT 2014
2014-07-06 08:02:29:724 470 sec: 4722067 operations; 8991.4 current ops/sec; [UPDATE AverageLatency(us)=699302.25] [INSERT AverageLatency(us)=6874.05] [CLEANUP AverageLatency(us)=699322.25] 
2014-07-06 08:02:39:725 480 sec: 4994191 operations; 27209.68 current ops/sec; [UPDATE AverageLatency(us)=1059562.67] [INSERT AverageLatency(us)=137.54] [CLEANUP AverageLatency(us)=1059585.67] 
2014-07-06 08:02:41:211 481 sec: 5000000 operations; 3909.15 current ops/sec; [UPDATE AverageLatency(us)=682235.5] [INSERT AverageLatency(us)=167.88] [CLEANUP AverageLatency(us)=682259.5] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404658962
1404658962
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo 'random read...'
random read...
+ echo 'starting time: '
starting time: 
++ date +%s
+ echo 1404658972
1404658972
++ echo /home/hadoop/git/physical_design/caseresult/case18/random_read_1.dat
+ ./random_read 5000000 20 /home/hadoop/git/physical_design/caseresult/case18/random_read_1.dat
Loading workload...
Starting test.
2014-07-06 08:02:55:404 0 sec: 0 operations; 
14/07/06 08:02:55 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/06 08:02:55 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/06 08:02:55 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/06 08:02:55 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/06 08:02:55 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/06 08:02:55 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/06 08:02:55 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/06 08:02:55 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/06 08:02:55 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/06 08:02:55 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/06 08:02:55 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/06 08:02:55 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/06 08:02:55 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/06 08:02:55 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/06 08:02:55 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/06 08:02:55 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x1ee4e327, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/06 08:02:55 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x1ee4e327 connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/06 08:02:55 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/06 08:02:55 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/06 08:02:56 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x1470c25ee7b0010, negotiated timeout = 90000
2014-07-06 08:03:05:406 10 sec: 53280 operations; 5326.4 current ops/sec; [READ AverageLatency(us)=3732.39] 
2014-07-06 08:03:15:408 20 sec: 158589 operations; 10528.79 current ops/sec; [READ AverageLatency(us)=1895.55] 
2014-07-06 08:03:25:409 30 sec: 260077 operations; 10147.79 current ops/sec; [READ AverageLatency(us)=1965.44] 
2014-07-06 08:03:35:410 40 sec: 388648 operations; 12855.81 current ops/sec; [READ AverageLatency(us)=1550.12] 
2014-07-06 08:03:45:410 50 sec: 543459 operations; 15481.1 current ops/sec; [READ AverageLatency(us)=1286.82] 
2014-07-06 08:03:55:411 60 sec: 705162 operations; 16168.68 current ops/sec; [READ AverageLatency(us)=1231.88] 
2014-07-06 08:04:05:412 70 sec: 866316 operations; 16113.79 current ops/sec; [READ AverageLatency(us)=1233.72] 
2014-07-06 08:04:15:412 80 sec: 1022966 operations; 15665 current ops/sec; [READ AverageLatency(us)=1274.06] 
2014-07-06 08:04:25:413 90 sec: 1178465 operations; 15548.35 current ops/sec; [READ AverageLatency(us)=1281.1] 
2014-07-06 08:04:35:413 100 sec: 1338752 operations; 16028.7 current ops/sec; [READ AverageLatency(us)=1242.71] 
2014-07-06 08:04:45:414 110 sec: 1495847 operations; 15707.93 current ops/sec; [READ AverageLatency(us)=1267.64] 
2014-07-06 08:04:55:415 120 sec: 1655493 operations; 15963 current ops/sec; [READ AverageLatency(us)=1248.04] 
2014-07-06 08:05:05:415 130 sec: 1810951 operations; 15545.8 current ops/sec; [READ AverageLatency(us)=1281.44] 
2014-07-06 08:05:15:416 140 sec: 1965745 operations; 15477.85 current ops/sec; [READ AverageLatency(us)=1287.09] 
2014-07-06 08:05:25:417 150 sec: 2117775 operations; 15201.48 current ops/sec; [READ AverageLatency(us)=1310.47] 
2014-07-06 08:05:35:417 160 sec: 2253514 operations; 13573.9 current ops/sec; [READ AverageLatency(us)=1467.11] 
2014-07-06 08:05:45:418 170 sec: 2379129 operations; 12560.24 current ops/sec; [READ AverageLatency(us)=1588.47] 
2014-07-06 08:05:55:418 180 sec: 2509509 operations; 13038 current ops/sec; [READ AverageLatency(us)=1528.95] 
2014-07-06 08:06:05:419 190 sec: 2662186 operations; 15266.17 current ops/sec; [READ AverageLatency(us)=1304.93] 
2014-07-06 08:06:15:420 200 sec: 2818272 operations; 15607.04 current ops/sec; [READ AverageLatency(us)=1276.34] 
2014-07-06 08:06:25:420 210 sec: 2974805 operations; 15653.3 current ops/sec; [READ AverageLatency(us)=1272.59] 
2014-07-06 08:06:35:421 220 sec: 3132122 operations; 15730.13 current ops/sec; [READ AverageLatency(us)=1266.36] 
2014-07-06 08:06:45:422 230 sec: 3291097 operations; 15895.91 current ops/sec; [READ AverageLatency(us)=1253.08] 
2014-07-06 08:06:55:422 240 sec: 3451252 operations; 16015.5 current ops/sec; [READ AverageLatency(us)=1241.76] 
2014-07-06 08:07:05:423 250 sec: 3609893 operations; 15862.51 current ops/sec; [READ AverageLatency(us)=1257.81] 
2014-07-06 08:07:15:423 260 sec: 3768410 operations; 15851.7 current ops/sec; [READ AverageLatency(us)=1256.62] 
2014-07-06 08:07:25:424 270 sec: 3926161 operations; 15773.52 current ops/sec; [READ AverageLatency(us)=1262.82] 
2014-07-06 08:07:35:425 280 sec: 4083989 operations; 15782.8 current ops/sec; [READ AverageLatency(us)=1262.15] 
2014-07-06 08:07:45:426 290 sec: 4242387 operations; 15836.63 current ops/sec; [READ AverageLatency(us)=1253.59] 
2014-07-06 08:07:55:426 300 sec: 4401006 operations; 15861.9 current ops/sec; [READ AverageLatency(us)=1259.87] 
2014-07-06 08:08:05:427 310 sec: 4557409 operations; 15638.74 current ops/sec; [READ AverageLatency(us)=1273.47] 
2014-07-06 08:08:15:427 320 sec: 4713212 operations; 15580.3 current ops/sec; [READ AverageLatency(us)=1278.61] 
2014-07-06 08:08:25:428 330 sec: 4873653 operations; 16042.5 current ops/sec; [READ AverageLatency(us)=1241.49] 
2014-07-06 08:08:33:750 338 sec: 5000000 operations; 15182.29 current ops/sec; [UPDATE AverageLatency(us)=14.45] [READ AverageLatency(us)=1249.82] [CLEANUP AverageLatency(us)=512.05] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404659314
1404659314
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo workloada...
workloada...
+ echo 'start time: '
start time: 
++ date +%s
+ echo 1404659324
1404659324
++ echo /home/hadoop/git/physical_design/caseresult/case18/workloada_1.dat
+ ./workloada 5000000 20 /home/hadoop/git/physical_design/caseresult/case18/workloada_1.dat
Loading workload...
Starting test.
2014-07-06 08:08:44:771 0 sec: 0 operations; 
14/07/06 08:08:45 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/06 08:08:45 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/06 08:08:45 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/06 08:08:45 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/06 08:08:45 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/06 08:08:45 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/06 08:08:45 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/06 08:08:45 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/06 08:08:45 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/06 08:08:45 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/06 08:08:45 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/06 08:08:45 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/06 08:08:45 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/06 08:08:45 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/06 08:08:45 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/06 08:08:45 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x6b355469, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/06 08:08:45 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x6b355469 connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/06 08:08:45 INFO zookeeper.ClientCnxn: Opening socket connection to server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/06 08:08:45 INFO zookeeper.ClientCnxn: Socket connection established to sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, initiating session
14/07/06 08:08:45 INFO zookeeper.ClientCnxn: Session establishment complete on server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, sessionid = 0x470c25f02f0009, negotiated timeout = 90000
2014-07-06 08:08:54:774 10 sec: 42011 operations; 4199.42 current ops/sec; [INSERT AverageLatency(us)=526.71] [READ AverageLatency(us)=3028.93] 
2014-07-06 08:09:04:776 20 sec: 177364 operations; 13532.59 current ops/sec; [INSERT AverageLatency(us)=14.66] [READ AverageLatency(us)=1550.33] 
2014-07-06 08:09:14:777 30 sec: 323444 operations; 14606.54 current ops/sec; [INSERT AverageLatency(us)=13.93] [READ AverageLatency(us)=1499.01] 
2014-07-06 08:09:24:778 40 sec: 455175 operations; 13171.78 current ops/sec; [INSERT AverageLatency(us)=12.52] [READ AverageLatency(us)=1668.53] 
2014-07-06 08:09:34:779 50 sec: 600336 operations; 14514.65 current ops/sec; [INSERT AverageLatency(us)=15.39] [READ AverageLatency(us)=1513.84] 
2014-07-06 08:09:44:780 60 sec: 740157 operations; 13980.7 current ops/sec; [INSERT AverageLatency(us)=22.87] [READ AverageLatency(us)=1571.43] 
2014-07-06 08:09:54:783 70 sec: 873983 operations; 13378.59 current ops/sec; [INSERT AverageLatency(us)=21.35] [READ AverageLatency(us)=1647.13] 
2014-07-06 08:10:04:783 80 sec: 942719 operations; 6873.6 current ops/sec; [INSERT AverageLatency(us)=102.15] [READ AverageLatency(us)=3185.2] 
2014-07-06 08:10:14:784 90 sec: 1036044 operations; 9331.57 current ops/sec; [INSERT AverageLatency(us)=30.1] [READ AverageLatency(us)=2383.54] 
2014-07-06 08:10:24:833 100 sec: 1142481 operations; 10591.8 current ops/sec; [INSERT AverageLatency(us)=19.46] [READ AverageLatency(us)=2087.6] 
2014-07-06 08:10:34:834 110 sec: 1283757 operations; 14126.19 current ops/sec; [INSERT AverageLatency(us)=22.35] [READ AverageLatency(us)=1563.47] 
2014-07-06 08:10:44:835 120 sec: 1418128 operations; 13435.76 current ops/sec; [INSERT AverageLatency(us)=22.25] [READ AverageLatency(us)=1636.59] 
2014-07-06 08:10:54:836 130 sec: 1567855 operations; 14972.7 current ops/sec; [INSERT AverageLatency(us)=38.56] [READ AverageLatency(us)=1471.76] 
2014-07-06 08:11:04:836 140 sec: 1719890 operations; 15201.98 current ops/sec; [INSERT AverageLatency(us)=20.91] [READ AverageLatency(us)=1450.65] 
2014-07-06 08:11:14:837 150 sec: 1862983 operations; 14307.87 current ops/sec; [INSERT AverageLatency(us)=32.23] [READ AverageLatency(us)=1526.29] 
2014-07-06 08:11:24:838 160 sec: 1956328 operations; 9333.57 current ops/sec; [INSERT AverageLatency(us)=64.07] [READ AverageLatency(us)=2389.03] 
2014-07-06 08:11:34:839 170 sec: 2097593 operations; 14126.5 current ops/sec; [INSERT AverageLatency(us)=30.48] [READ AverageLatency(us)=1562.45] 
2014-07-06 08:11:44:841 180 sec: 2247604 operations; 14996.6 current ops/sec; [INSERT AverageLatency(us)=21.74] [READ AverageLatency(us)=1470.72] 
2014-07-06 08:11:54:951 190 sec: 2368449 operations; 11953.02 current ops/sec; [INSERT AverageLatency(us)=29.47] [READ AverageLatency(us)=1843.75] 
2014-07-06 08:12:05:381 200 sec: 2539292 operations; 16379.96 current ops/sec; [INSERT AverageLatency(us)=16.97] [READ AverageLatency(us)=1332.99] 
2014-07-06 08:12:15:382 210 sec: 2708399 operations; 16909.01 current ops/sec; [INSERT AverageLatency(us)=15.81] [READ AverageLatency(us)=1320.8] 
2014-07-06 08:12:25:383 220 sec: 2824913 operations; 11650.23 current ops/sec; [INSERT AverageLatency(us)=28.03] [READ AverageLatency(us)=1897.94] 
2014-07-06 08:12:35:384 230 sec: 2936794 operations; 11186.98 current ops/sec; [INSERT AverageLatency(us)=22.71] [READ AverageLatency(us)=1975.37] 
2014-07-06 08:12:45:385 240 sec: 3073905 operations; 13709.73 current ops/sec; [INSERT AverageLatency(us)=18.59] [READ AverageLatency(us)=1610.66] 
2014-07-06 08:12:55:386 250 sec: 3226598 operations; 15267.77 current ops/sec; [INSERT AverageLatency(us)=18.44] [READ AverageLatency(us)=1446.63] 
2014-07-06 08:13:05:387 260 sec: 3382515 operations; 15590.14 current ops/sec; [INSERT AverageLatency(us)=19.28] [READ AverageLatency(us)=1414.04] 
2014-07-06 08:13:15:436 270 sec: 3546823 operations; 16350.68 current ops/sec; [INSERT AverageLatency(us)=17.25] [READ AverageLatency(us)=1346.9] 
2014-07-06 08:13:25:446 280 sec: 3713771 operations; 16679.79 current ops/sec; [INSERT AverageLatency(us)=19.38] [READ AverageLatency(us)=1323.7] 
2014-07-06 08:13:35:446 290 sec: 3801099 operations; 8731.93 current ops/sec; [INSERT AverageLatency(us)=39.03] [READ AverageLatency(us)=2536.21] 
2014-07-06 08:13:45:447 300 sec: 3961598 operations; 16048.3 current ops/sec; [INSERT AverageLatency(us)=16.96] [READ AverageLatency(us)=1376.87] 
2014-07-06 08:13:55:448 310 sec: 4119678 operations; 15806.42 current ops/sec; [INSERT AverageLatency(us)=17.92] [READ AverageLatency(us)=1396.48] 
2014-07-06 08:14:05:449 320 sec: 4269065 operations; 14938.7 current ops/sec; [INSERT AverageLatency(us)=17.38] [READ AverageLatency(us)=1479.47] 
2014-07-06 08:14:15:450 330 sec: 4415235 operations; 14614.08 current ops/sec; [INSERT AverageLatency(us)=14.44] [READ AverageLatency(us)=1510.95] 
2014-07-06 08:14:25:451 340 sec: 4592060 operations; 17680.73 current ops/sec; [INSERT AverageLatency(us)=16.15] [READ AverageLatency(us)=1248.51] 
2014-07-06 08:14:35:451 350 sec: 4695804 operations; 10374.4 current ops/sec; [INSERT AverageLatency(us)=22.95] [READ AverageLatency(us)=2133.37] 
2014-07-06 08:14:45:452 360 sec: 4758429 operations; 6261.87 current ops/sec; [INSERT AverageLatency(us)=30.81] [READ AverageLatency(us)=3536.93] 
2014-07-06 08:14:55:453 370 sec: 4927933 operations; 16948.71 current ops/sec; [INSERT AverageLatency(us)=15.36] [READ AverageLatency(us)=1302.33] 
2014-07-06 08:15:01:333 376 sec: 5000000 operations; 12256.29 current ops/sec; [UPDATE AverageLatency(us)=169184.45] [INSERT AverageLatency(us)=13.67] [READ AverageLatency(us)=1368.58] [CLEANUP AverageLatency(us)=169375.2] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404659702
1404659702
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo workloadb...
workloadb...
+ echo 'start time: '
start time: 
++ date +%s
+ echo 1404659712
1404659712
++ echo /home/hadoop/git/physical_design/caseresult/case18/workloadb_1.dat
+ ./workloadb 5000000 20 /home/hadoop/git/physical_design/caseresult/case18/workloadb_1.dat
Loading workload...
Starting test.
2014-07-06 08:15:13:296 0 sec: 0 operations; 
14/07/06 08:15:13 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/06 08:15:13 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/06 08:15:13 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/06 08:15:13 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/06 08:15:13 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/06 08:15:13 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/06 08:15:13 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/06 08:15:13 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/06 08:15:13 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/06 08:15:13 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/06 08:15:13 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/06 08:15:13 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/06 08:15:13 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/06 08:15:13 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/06 08:15:13 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/06 08:15:13 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x30ea3e3c, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/06 08:15:13 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x30ea3e3c connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/06 08:15:13 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/06 08:15:13 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/06 08:15:13 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x1470c25ee7b0011, negotiated timeout = 90000
2014-07-06 08:15:23:298 10 sec: 58614 operations; 5857.3 current ops/sec; [INSERT AverageLatency(us)=313.43] [READ AverageLatency(us)=2891.47] 
2014-07-06 08:15:33:301 20 sec: 224878 operations; 16621.41 current ops/sec; [INSERT AverageLatency(us)=20.18] [READ AverageLatency(us)=2261.67] 
2014-07-06 08:15:43:303 30 sec: 376413 operations; 15151.98 current ops/sec; [INSERT AverageLatency(us)=29.12] [READ AverageLatency(us)=2572.28] 
2014-07-06 08:15:53:303 40 sec: 547043 operations; 17061.29 current ops/sec; [INSERT AverageLatency(us)=17.53] [READ AverageLatency(us)=2296.65] 
2014-07-06 08:16:03:304 50 sec: 697036 operations; 14997.8 current ops/sec; [INSERT AverageLatency(us)=20.37] [READ AverageLatency(us)=2600.5] 
2014-07-06 08:16:13:306 60 sec: 853565 operations; 15649.77 current ops/sec; [INSERT AverageLatency(us)=20.18] [READ AverageLatency(us)=2530.88] 
2014-07-06 08:16:23:306 70 sec: 1032965 operations; 17940 current ops/sec; [INSERT AverageLatency(us)=17.41] [READ AverageLatency(us)=2190.95] 
2014-07-06 08:16:33:308 80 sec: 1200909 operations; 16791.04 current ops/sec; [INSERT AverageLatency(us)=15.31] [READ AverageLatency(us)=2350.02] 
2014-07-06 08:16:43:309 90 sec: 1345898 operations; 14497.45 current ops/sec; [INSERT AverageLatency(us)=18.4] [READ AverageLatency(us)=2711.04] 
2014-07-06 08:16:53:310 100 sec: 1518753 operations; 17285.5 current ops/sec; [INSERT AverageLatency(us)=16.31] [READ AverageLatency(us)=2246.19] 
2014-07-06 08:17:03:310 110 sec: 1702645 operations; 18387.36 current ops/sec; [INSERT AverageLatency(us)=17.31] [READ AverageLatency(us)=2163.96] 
2014-07-06 08:17:13:311 120 sec: 1878540 operations; 17587.74 current ops/sec; [INSERT AverageLatency(us)=18.53] [READ AverageLatency(us)=2249.65] 
2014-07-06 08:17:23:312 130 sec: 2044213 operations; 16565.64 current ops/sec; [INSERT AverageLatency(us)=16.54] [READ AverageLatency(us)=2379.03] 
2014-07-06 08:17:33:313 140 sec: 2150433 operations; 10620.94 current ops/sec; [INSERT AverageLatency(us)=20.99] [READ AverageLatency(us)=3740.21] 
2014-07-06 08:17:43:314 150 sec: 2271914 operations; 12146.89 current ops/sec; [INSERT AverageLatency(us)=15.26] [READ AverageLatency(us)=3258.23] 
2014-07-06 08:17:53:314 160 sec: 2433777 operations; 16186.3 current ops/sec; [INSERT AverageLatency(us)=16.79] [READ AverageLatency(us)=2442.27] 
2014-07-06 08:18:03:315 170 sec: 2608035 operations; 17424.06 current ops/sec; [INSERT AverageLatency(us)=20.03] [READ AverageLatency(us)=2250.15] 
2014-07-06 08:18:13:316 180 sec: 2789521 operations; 18146.79 current ops/sec; [INSERT AverageLatency(us)=18.68] [READ AverageLatency(us)=2162.43] 
2014-07-06 08:18:23:317 190 sec: 2914527 operations; 12499.35 current ops/sec; [INSERT AverageLatency(us)=15.82] [READ AverageLatency(us)=3188.91] 
2014-07-06 08:18:33:317 200 sec: 3069469 operations; 15494.2 current ops/sec; [INSERT AverageLatency(us)=15.82] [READ AverageLatency(us)=2550.22] 
2014-07-06 08:18:43:353 210 sec: 3221672 operations; 15165.7 current ops/sec; [INSERT AverageLatency(us)=12.64] [READ AverageLatency(us)=2599.6] 
2014-07-06 08:18:53:354 220 sec: 3366078 operations; 14439.16 current ops/sec; [INSERT AverageLatency(us)=24.26] [READ AverageLatency(us)=2732.73] 
2014-07-06 08:19:03:355 230 sec: 3493952 operations; 12786.12 current ops/sec; [INSERT AverageLatency(us)=17.02] [READ AverageLatency(us)=3110.73] 
2014-07-06 08:19:13:355 240 sec: 3598615 operations; 10466.3 current ops/sec; [INSERT AverageLatency(us)=21.55] [READ AverageLatency(us)=3764.13] 
2014-07-06 08:19:23:360 250 sec: 3733937 operations; 13525.44 current ops/sec; [INSERT AverageLatency(us)=19.68] [READ AverageLatency(us)=2921.89] 
2014-07-06 08:19:33:362 260 sec: 3809050 operations; 7509.8 current ops/sec; [INSERT AverageLatency(us)=18.19] [READ AverageLatency(us)=5253.71] 
2014-07-06 08:19:43:378 270 sec: 3937323 operations; 12806.81 current ops/sec; [INSERT AverageLatency(us)=14.07] [READ AverageLatency(us)=3106.81] 
2014-07-06 08:19:53:379 280 sec: 4086709 operations; 14937.11 current ops/sec; [INSERT AverageLatency(us)=18.82] [READ AverageLatency(us)=2654.41] 
2014-07-06 08:20:03:380 290 sec: 4221979 operations; 13525.65 current ops/sec; [INSERT AverageLatency(us)=16.07] [READ AverageLatency(us)=2933.57] 
2014-07-06 08:20:13:381 300 sec: 4368856 operations; 14686.23 current ops/sec; [INSERT AverageLatency(us)=15.03] [READ AverageLatency(us)=2687.44] 
2014-07-06 08:20:23:382 310 sec: 4513111 operations; 14424.06 current ops/sec; [INSERT AverageLatency(us)=15.5] [READ AverageLatency(us)=2743.99] 
2014-07-06 08:20:33:382 320 sec: 4672592 operations; 15948.1 current ops/sec; [INSERT AverageLatency(us)=13.68] [READ AverageLatency(us)=2477.33] 
2014-07-06 08:20:43:384 330 sec: 4808800 operations; 13619.44 current ops/sec; [INSERT AverageLatency(us)=17.72] [READ AverageLatency(us)=2901.95] 
2014-07-06 08:20:53:402 340 sec: 4940206 operations; 13116.99 current ops/sec; [INSERT AverageLatency(us)=20.75] [READ AverageLatency(us)=3017.62] 
2014-07-06 08:21:01:154 347 sec: 5000000 operations; 7712.37 current ops/sec; [UPDATE AverageLatency(us)=296749.7] [INSERT AverageLatency(us)=13.39] [READ AverageLatency(us)=3275.39] [CLEANUP AverageLatency(us)=297108.6] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404660061
1404660061
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo workloadc...
workloadc...
+ echo 'start time: '
start time: 
++ date +%s
+ echo 1404660071
1404660071
++ echo /home/hadoop/git/physical_design/caseresult/case18/workloadc_1.dat
+ ./workloadc 5000000 20 /home/hadoop/git/physical_design/caseresult/case18/workloadc_1.dat
Loading workload...
Starting test.
2014-07-06 08:21:12:975 0 sec: 0 operations; 
14/07/06 08:21:13 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/06 08:21:13 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/06 08:21:13 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/06 08:21:13 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/06 08:21:13 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/06 08:21:13 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/06 08:21:13 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/06 08:21:13 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/06 08:21:13 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/06 08:21:13 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/06 08:21:13 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/06 08:21:13 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/06 08:21:13 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/06 08:21:13 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/06 08:21:13 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/06 08:21:13 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x41fbfa37, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/06 08:21:13 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x41fbfa37 connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/06 08:21:13 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/06 08:21:13 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/06 08:21:13 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x1470c25ee7b0012, negotiated timeout = 90000
2014-07-06 08:21:22:976 10 sec: 201980 operations; 20193.96 current ops/sec; [INSERT AverageLatency(us)=131.46] [READ AverageLatency(us)=7365.59] 
2014-07-06 08:21:32:977 20 sec: 395316 operations; 19331.67 current ops/sec; [INSERT AverageLatency(us)=35.18] [READ AverageLatency(us)=9808.83] 
2014-07-06 08:21:42:978 30 sec: 623318 operations; 22797.92 current ops/sec; [INSERT AverageLatency(us)=18.57] [READ AverageLatency(us)=8512.24] 
2014-07-06 08:21:52:979 40 sec: 858143 operations; 23480.15 current ops/sec; [INSERT AverageLatency(us)=16.65] [READ AverageLatency(us)=8467.49] 
2014-07-06 08:22:02:995 50 sec: 1093775 operations; 23525.56 current ops/sec; [INSERT AverageLatency(us)=14.52] [READ AverageLatency(us)=8289.2] 
2014-07-06 08:22:12:996 60 sec: 1301939 operations; 20814.32 current ops/sec; [INSERT AverageLatency(us)=16.37] [READ AverageLatency(us)=9321.06] 
2014-07-06 08:22:22:997 70 sec: 1509327 operations; 20736.73 current ops/sec; [INSERT AverageLatency(us)=13.8] [READ AverageLatency(us)=9372.19] 
2014-07-06 08:22:32:997 80 sec: 1669766 operations; 16043.9 current ops/sec; [INSERT AverageLatency(us)=14.4] [READ AverageLatency(us)=11786.44] 
2014-07-06 08:22:43:039 90 sec: 1862427 operations; 19185.52 current ops/sec; [INSERT AverageLatency(us)=14.02] [READ AverageLatency(us)=10663.28] 
2014-07-06 08:22:53:040 100 sec: 2018946 operations; 15650.33 current ops/sec; [INSERT AverageLatency(us)=12.83] [READ AverageLatency(us)=12525.95] 
2014-07-06 08:23:03:040 110 sec: 2183810 operations; 16486.4 current ops/sec; [INSERT AverageLatency(us)=14.54] [READ AverageLatency(us)=11977.35] 
2014-07-06 08:23:13:041 120 sec: 2358298 operations; 17447.06 current ops/sec; [INSERT AverageLatency(us)=13.63] [READ AverageLatency(us)=11393.24] 
2014-07-06 08:23:23:042 130 sec: 2523967 operations; 16566.9 current ops/sec; [INSERT AverageLatency(us)=12.78] [READ AverageLatency(us)=11886.49] 
2014-07-06 08:23:33:042 140 sec: 2695333 operations; 17134.89 current ops/sec; [INSERT AverageLatency(us)=12.84] [READ AverageLatency(us)=11455.26] 
2014-07-06 08:23:43:043 150 sec: 2848769 operations; 15342.07 current ops/sec; [INSERT AverageLatency(us)=13.48] [READ AverageLatency(us)=12798.88] 
2014-07-06 08:23:53:054 160 sec: 2993750 operations; 14482.17 current ops/sec; [INSERT AverageLatency(us)=14.23] [READ AverageLatency(us)=13699.56] 
2014-07-06 08:24:03:063 170 sec: 3142480 operations; 14859.63 current ops/sec; [INSERT AverageLatency(us)=14.8] [READ AverageLatency(us)=13186.86] 
2014-07-06 08:24:13:064 180 sec: 3305957 operations; 16346.07 current ops/sec; [INSERT AverageLatency(us)=13.65] [READ AverageLatency(us)=12137.12] 
2014-07-06 08:24:23:065 190 sec: 3488999 operations; 18302.37 current ops/sec; [INSERT AverageLatency(us)=12.77] [READ AverageLatency(us)=10816.09] 
2014-07-06 08:24:33:066 200 sec: 3650397 operations; 16138.19 current ops/sec; [INSERT AverageLatency(us)=13.8] [READ AverageLatency(us)=12145.82] 
2014-07-06 08:24:43:066 210 sec: 3813874 operations; 16347.7 current ops/sec; [INSERT AverageLatency(us)=12.78] [READ AverageLatency(us)=12154.32] 
2014-07-06 08:24:53:073 220 sec: 3992302 operations; 17830.32 current ops/sec; [INSERT AverageLatency(us)=13.07] [READ AverageLatency(us)=11138.44] 
2014-07-06 08:25:03:075 230 sec: 4156530 operations; 16419.52 current ops/sec; [INSERT AverageLatency(us)=13.9] [READ AverageLatency(us)=12066.46] 
2014-07-06 08:25:13:076 240 sec: 4335719 operations; 17917.11 current ops/sec; [INSERT AverageLatency(us)=13.16] [READ AverageLatency(us)=10950.84] 
2014-07-06 08:25:23:077 250 sec: 4501899 operations; 16616.34 current ops/sec; [INSERT AverageLatency(us)=13.17] [READ AverageLatency(us)=11733.05] 
2014-07-06 08:25:33:078 260 sec: 4640307 operations; 13839.42 current ops/sec; [INSERT AverageLatency(us)=14.67] [READ AverageLatency(us)=14286.97] 
2014-07-06 08:25:43:079 270 sec: 4811146 operations; 17082.19 current ops/sec; [INSERT AverageLatency(us)=12.99] [READ AverageLatency(us)=11541.05] 
2014-07-06 08:25:53:080 280 sec: 4952638 operations; 14147.79 current ops/sec; [UPDATE AverageLatency(us)=486941.6] [INSERT AverageLatency(us)=13.06] [READ AverageLatency(us)=12816.54] [CLEANUP AverageLatency(us)=487875.8] 
2014-07-06 08:25:59:473 286 sec: 5000000 operations; 7408.42 current ops/sec; [UPDATE AverageLatency(us)=421085.27] [INSERT AverageLatency(us)=11.83] [READ AverageLatency(us)=10066.24] [CLEANUP AverageLatency(us)=421104.67] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404660360
1404660360
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ let counter=1+1
+ read line
+ set +x
