++ wc -l
+ filename=case72
+ mkdir caseresult/case72
+ ssh hadoop@master mkdir /home/hadoop/git/physical_design/caseresult/case72
+ RESULT_DIR=/home/hadoop/git/physical_design/caseresult/case72
+ TEN=10
+ SIXTY=60
+ SLEEP_TIME=300
+ YCSB_DIR=/home/hadoop/ycsb-0.1.4
+ number_of_operations=10000000
+ number_of_threads=20
+ number_of_records=10000000
+ output_file_suffix=.dat
+ experiment_list_file=/home/hadoop/git/physical_design/case72.list
+ clean=false
+ create=false
+ load=false
+ random_read=false
+ workloada=false
+ workloadb=false
+ workloadc=false
+ scan=false
+ all=false
+ for i in '$@'
+ '[' clean == all ']'
+ '[' clean == clean ']'
+ clean=true
+ for i in '$@'
+ '[' create == all ']'
+ '[' create == clean ']'
+ '[' create == create ']'
+ create=true
+ for i in '$@'
+ '[' load == all ']'
+ '[' load == clean ']'
+ '[' load == create ']'
+ '[' load == load ']'
+ load=true
+ let counter=1
+ cd /home/hadoop/ycsb-0.1.4
++ pwd
+ echo /home/hadoop/ycsb-0.1.4
/home/hadoop/ycsb-0.1.4
+ read line
+ false
+ true
+ echo 'sleeping for 60 ...'
sleeping for 60 ...
+ sleep 60
+ echo 'droping usertable...'
droping usertable...
+ ssh hadoop@master /home/hadoop/hbase/bin/hbase shell /home/hadoop/git/physical_design/delete_table
0 row(s) in 2.6450 seconds

0 row(s) in 0.8800 seconds

0 row(s) in 0.3250 seconds

+ echo 'sleeping for 300 ...'
sleeping for 300 ...
+ sleep 300
+ false
+ true
+ echo 'creating usertable...'
creating usertable...
+ create_statement='create '\''usertable'\'', { NAME=>'\''family'\'', COMPRESSION=>'\''GZ'\'', CONFIGURATION =>  { '\''hbase.hregion.majorcompaction'\'' => '\''0'\'', '\''hbase.hstore.compactionThreshold'\'' => '\''100000000000000'\'', '\''hbase.server.compactchecker.interval.multiplier'\'' => '\''100000000'\'', '\''hbase.hstore.compaction.max.size'\'' => '\''128'\'' } }, SPLITS => ['\''user1'\'', '\''user2'\'', '\''user3'\'', '\''user4'\'', '\''user5'\'', '\''user6'\'', '\''user7'\'', '\''user8'\'', '\''user9'\'']'
+ echo create ''\''usertable'\'',' '{' 'NAME=>'\''family'\'',' 'COMPRESSION=>'\''GZ'\'',' CONFIGURATION '=>' '{' ''\''hbase.hregion.majorcompaction'\''' '=>' ''\''0'\'',' ''\''hbase.hstore.compactionThreshold'\''' '=>' ''\''100000000000000'\'',' ''\''hbase.server.compactchecker.interval.multiplier'\''' '=>' ''\''100000000'\'',' ''\''hbase.hstore.compaction.max.size'\''' '=>' ''\''128'\''' '}' '},' SPLITS '=>' '['\''user1'\'',' ''\''user2'\'',' ''\''user3'\'',' ''\''user4'\'',' ''\''user5'\'',' ''\''user6'\'',' ''\''user7'\'',' ''\''user8'\'',' ''\''user9'\'']'
+ echo 'exit '
+ scp /home/hadoop/git/physical_design/caseresult/case72/create_1.script hadoop@master:/home/hadoop/git/physical_design/caseresult/case72/create_1.script
+ create_table /home/hadoop/git/physical_design/caseresult/case72/create_1.script
+ echo 'creating table...'
creating table...
+ echo /home/hadoop/git/physical_design/caseresult/case72/create_1.script
/home/hadoop/git/physical_design/caseresult/case72/create_1.script
+ ssh hadoop@master /home/hadoop/hbase/bin/hbase shell /home/hadoop/git/physical_design/caseresult/case72/create_1.script
0 row(s) in 1.7500 seconds

+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ false
+ true
+ echo 'loading data...'
loading data...
+ echo 'starting time: '
starting time: 
++ date +%s
+ echo 1405033686
1405033686
++ echo /home/hadoop/git/physical_design/caseresult/case72/load_1.dat
+ ./ld 10000000 20 /home/hadoop/git/physical_design/caseresult/case72/load_1.dat
Loading workload...
Starting test.
2014-07-10 16:08:06:515 0 sec: 0 operations; 
14/07/10 16:08:06 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/10 16:08:06 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm43.almaden.ibm.com
14/07/10 16:08:06 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/10 16:08:06 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/10 16:08:06 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/10 16:08:06 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf
14/07/10 16:08:06 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/10 16:08:06 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/10 16:08:06 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/10 16:08:06 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/10 16:08:06 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/10 16:08:06 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/10 16:08:06 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/10 16:08:06 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/10 16:08:06 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/10 16:08:06 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x29ee65b1, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/10 16:08:06 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x29ee65b1 connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/10 16:08:06 INFO zookeeper.ClientCnxn: Opening socket connection to server master/9.1.143.58:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/10 16:08:06 INFO zookeeper.ClientCnxn: Socket connection established to master/9.1.143.58:2181, initiating session
14/07/10 16:08:06 INFO zookeeper.ClientCnxn: Session establishment complete on server master/9.1.143.58:2181, sessionid = 0x472434cc6e000e, negotiated timeout = 90000
2014-07-10 16:08:16:516 10 sec: 266540 operations; 26651.33 current ops/sec; [INSERT AverageLatency(us)=437.21] 
2014-07-10 16:08:26:517 20 sec: 266540 operations; 0 current ops/sec;  
2014-07-10 16:08:36:517 30 sec: 266540 operations; 0 current ops/sec;  
2014-07-10 16:08:46:517 40 sec: 426159 operations; 15961.9 current ops/sec; [INSERT AverageLatency(us)=2411.47] 
2014-07-10 16:08:56:518 50 sec: 496766 operations; 7059.99 current ops/sec; [INSERT AverageLatency(us)=1235.81] 
2014-07-10 16:09:06:519 60 sec: 496766 operations; 0 current ops/sec;  
14/07/10 16:09:12 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2486 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=907, waitTime=2719, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:08:14 PDT 2014, retrying after 10022 ms, replay 2486 ops.
14/07/10 16:09:12 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2423 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=907, waitTime=2719, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:08:08 PDT 2014, retrying after 10049 ms, replay 2423 ops.
14/07/10 16:09:12 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2390 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=907, waitTime=2719, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:08:08 PDT 2014, retrying after 10080 ms, replay 2390 ops.
14/07/10 16:09:12 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2455 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=907, waitTime=2719, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:08:08 PDT 2014, retrying after 10033 ms, replay 2455 ops.
14/07/10 16:09:12 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 2427 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=907, waitTime=2719, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:08:08 PDT 2014, retrying after 10078 ms, replay 2427 ops.
14/07/10 16:09:12 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2440 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=907, waitTime=2719, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:08:15 PDT 2014, retrying after 10050 ms, replay 2440 ops.
2014-07-10 16:09:16:519 70 sec: 496781 operations; 1.5 current ops/sec; [INSERT AverageLatency(us)=1267935.07] 
2014-07-10 16:09:26:519 80 sec: 614504 operations; 11772.3 current ops/sec; [INSERT AverageLatency(us)=2109.55] 
14/07/10 16:09:26 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 2390 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1066, waitTime=2888, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:08:08 PDT 2014, retrying after 10007 ms, replay 2390 ops.
14/07/10 16:09:26 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2423 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1066, waitTime=2888, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:08:08 PDT 2014, retrying after 10008 ms, replay 2423 ops.
14/07/10 16:09:26 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2440 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1066, waitTime=2888, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:08:15 PDT 2014, retrying after 10085 ms, replay 2440 ops.
14/07/10 16:09:26 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 2455 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1066, waitTime=2888, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:08:08 PDT 2014, retrying after 10032 ms, replay 2455 ops.
14/07/10 16:09:26 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2486 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1066, waitTime=2888, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:08:14 PDT 2014, retrying after 10048 ms, replay 2486 ops.
14/07/10 16:09:26 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 2427 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1066, waitTime=2888, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:08:08 PDT 2014, retrying after 10061 ms, replay 2427 ops.
2014-07-10 16:09:36:527 90 sec: 644936 operations; 3040.77 current ops/sec; [INSERT AverageLatency(us)=4605.83] 
14/07/10 16:09:37 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:08:08 PDT 2014
14/07/10 16:09:37 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:08:08 PDT 2014
14/07/10 16:09:37 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:08:14 PDT 2014
14/07/10 16:09:38 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:08:08 PDT 2014
14/07/10 16:09:38 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2456 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1326, waitTime=2120, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:08:38 PDT 2014, retrying after 10070 ms, replay 2456 ops.
14/07/10 16:09:38 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 failed 2440 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1326, waitTime=2120, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:08:15 PDT 2014, retrying after 20157 ms, replay 2440 ops.
14/07/10 16:09:38 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 failed 2423 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1326, waitTime=2120, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:08:08 PDT 2014, retrying after 20062 ms, replay 2423 ops.
14/07/10 16:09:38 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2427 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1326, waitTime=2120, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:08:39 PDT 2014, retrying after 10042 ms, replay 2427 ops.
2014-07-10 16:09:46:528 100 sec: 739996 operations; 9505.05 current ops/sec; [INSERT AverageLatency(us)=5037.2] 
14/07/10 16:09:50 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2427 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1570, waitTime=2024, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:08:39 PDT 2014, retrying after 10075 ms, replay 2427 ops.
14/07/10 16:09:51 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2456 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1571, waitTime=2174, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:08:38 PDT 2014, retrying after 10038 ms, replay 2456 ops.
2014-07-10 16:09:56:528 110 sec: 772739 operations; 3274.3 current ops/sec; [INSERT AverageLatency(us)=1819.89] 
14/07/10 16:10:00 INFO client.AsyncProcess: #14, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:08:15 PDT 2014
14/07/10 16:10:00 INFO client.AsyncProcess: #3, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:08:08 PDT 2014
14/07/10 16:10:02 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:08:39 PDT 2014
14/07/10 16:10:02 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:08:38 PDT 2014
2014-07-10 16:10:06:529 120 sec: 976179 operations; 20341.97 current ops/sec; [INSERT AverageLatency(us)=2647.92] 
2014-07-10 16:10:17:308 130 sec: 1155548 operations; 16640.6 current ops/sec; [INSERT AverageLatency(us)=2499.07] 
2014-07-10 16:10:27:308 140 sec: 1425599 operations; 27005.1 current ops/sec; [INSERT AverageLatency(us)=794.63] 
2014-07-10 16:10:37:317 150 sec: 1543195 operations; 11749.03 current ops/sec; [INSERT AverageLatency(us)=1500.59] 
2014-07-10 16:10:47:318 160 sec: 1543204 operations; 0.9 current ops/sec; [INSERT AverageLatency(us)=367389.89] 
2014-07-10 16:10:57:318 170 sec: 1603247 operations; 6004.3 current ops/sec; [INSERT AverageLatency(us)=3435.29] 
2014-07-10 16:11:07:319 180 sec: 1961597 operations; 35831.42 current ops/sec; [INSERT AverageLatency(us)=495.76] 
2014-07-10 16:11:17:319 190 sec: 1989586 operations; 2798.9 current ops/sec; [INSERT AverageLatency(us)=3120.93] 
14/07/10 16:11:18 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 2480 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3604, waitTime=2431, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:24 PDT 2014, retrying after 10043 ms, replay 2480 ops.
14/07/10 16:11:18 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2870 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3604, waitTime=2431, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:24 PDT 2014, retrying after 10094 ms, replay 2870 ops.
14/07/10 16:11:18 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2437 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3604, waitTime=2431, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:24 PDT 2014, retrying after 10005 ms, replay 2437 ops.
14/07/10 16:11:18 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2478 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3604, waitTime=2431, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:24 PDT 2014, retrying after 10042 ms, replay 2478 ops.
14/07/10 16:11:18 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 1768 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3604, waitTime=2431, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:24 PDT 2014, retrying after 10051 ms, replay 1768 ops.
14/07/10 16:11:18 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2159 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3604, waitTime=2431, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:24 PDT 2014, retrying after 10028 ms, replay 2159 ops.
14/07/10 16:11:18 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2098 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3604, waitTime=2431, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:24 PDT 2014, retrying after 10082 ms, replay 2098 ops.
14/07/10 16:11:18 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2422 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3604, waitTime=2431, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:24 PDT 2014, retrying after 10015 ms, replay 2422 ops.
14/07/10 16:11:24 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2469 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3701, waitTime=2380, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:33 PDT 2014, retrying after 10048 ms, replay 2469 ops.
14/07/10 16:11:24 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2420 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3717, waitTime=2000, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:33 PDT 2014, retrying after 10015 ms, replay 2420 ops.
2014-07-10 16:11:27:320 200 sec: 2056772 operations; 6717.93 current ops/sec; [INSERT AverageLatency(us)=941.01] 
14/07/10 16:11:30 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:24 PDT 2014
14/07/10 16:11:30 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:24 PDT 2014
14/07/10 16:11:30 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:24 PDT 2014
14/07/10 16:11:30 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:24 PDT 2014
14/07/10 16:11:30 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2422 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3900, waitTime=2132, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:24 PDT 2014, retrying after 10064 ms, replay 2422 ops.
14/07/10 16:11:30 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2437 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3900, waitTime=2132, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:24 PDT 2014, retrying after 10040 ms, replay 2437 ops.
14/07/10 16:11:30 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 2098 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3900, waitTime=2132, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:24 PDT 2014, retrying after 10072 ms, replay 2098 ops.
14/07/10 16:11:30 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2870 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3900, waitTime=2132, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:24 PDT 2014, retrying after 10003 ms, replay 2870 ops.
14/07/10 16:11:36 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:33 PDT 2014
14/07/10 16:11:36 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:33 PDT 2014
2014-07-10 16:11:37:328 210 sec: 2316299 operations; 25931.95 current ops/sec; [INSERT AverageLatency(us)=1212.44] 
14/07/10 16:11:42 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2870 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4449, waitTime=2024, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:24 PDT 2014, retrying after 20075 ms, replay 2870 ops.
14/07/10 16:11:43 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 2422 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4451, waitTime=2670, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:24 PDT 2014, retrying after 20189 ms, replay 2422 ops.
14/07/10 16:11:43 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 failed 2437 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4451, waitTime=2670, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:24 PDT 2014, retrying after 20150 ms, replay 2437 ops.
14/07/10 16:11:43 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 failed 2098 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4451, waitTime=2670, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:24 PDT 2014, retrying after 20124 ms, replay 2098 ops.
2014-07-10 16:11:47:329 220 sec: 2461292 operations; 14497.85 current ops/sec; [INSERT AverageLatency(us)=466.87] 
14/07/10 16:11:57 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2522 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4719, waitTime=2450, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:05 PDT 2014, retrying after 10037 ms, replay 2522 ops.
14/07/10 16:11:57 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2408 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4719, waitTime=2450, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:07 PDT 2014, retrying after 10004 ms, replay 2408 ops.
14/07/10 16:11:57 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2922 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4719, waitTime=2450, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:05 PDT 2014, retrying after 10007 ms, replay 2922 ops.
2014-07-10 16:11:57:329 230 sec: 2515030 operations; 5373.8 current ops/sec; [INSERT AverageLatency(us)=2751.39] 
14/07/10 16:11:57 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2926 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4748, waitTime=2609, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:05 PDT 2014, retrying after 10025 ms, replay 2926 ops.
14/07/10 16:11:57 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2953 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4748, waitTime=2609, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:06 PDT 2014, retrying after 10074 ms, replay 2953 ops.
14/07/10 16:12:03 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:24 PDT 2014
14/07/10 16:12:04 INFO client.AsyncProcess: #8, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:24 PDT 2014
14/07/10 16:12:05 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:24 PDT 2014
14/07/10 16:12:05 INFO client.AsyncProcess: #19, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:10:24 PDT 2014
2014-07-10 16:12:07:330 240 sec: 2693785 operations; 17873.71 current ops/sec; [INSERT AverageLatency(us)=2792.15] 
14/07/10 16:12:09 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 2522 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5112, waitTime=2627, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:05 PDT 2014, retrying after 10023 ms, replay 2522 ops.
14/07/10 16:12:10 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2922 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5112, waitTime=2627, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:05 PDT 2014, retrying after 10029 ms, replay 2922 ops.
14/07/10 16:12:10 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2408 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5112, waitTime=2627, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:07 PDT 2014, retrying after 10072 ms, replay 2408 ops.
14/07/10 16:12:10 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2926 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5124, waitTime=2398, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:05 PDT 2014, retrying after 10014 ms, replay 2926 ops.
14/07/10 16:12:10 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2953 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5124, waitTime=2398, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:06 PDT 2014, retrying after 10036 ms, replay 2953 ops.
2014-07-10 16:12:17:330 250 sec: 2734367 operations; 4058.2 current ops/sec; [INSERT AverageLatency(us)=662.14] 
14/07/10 16:12:22 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 failed 2522 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5391, waitTime=2359, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:05 PDT 2014, retrying after 20116 ms, replay 2522 ops.
14/07/10 16:12:22 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 failed 2922 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5391, waitTime=2359, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:05 PDT 2014, retrying after 20092 ms, replay 2922 ops.
14/07/10 16:12:22 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2926 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5394, waitTime=2229, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:05 PDT 2014, retrying after 20018 ms, replay 2926 ops.
14/07/10 16:12:22 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 failed 2953 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5394, waitTime=2229, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:06 PDT 2014, retrying after 20197 ms, replay 2953 ops.
14/07/10 16:12:22 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 failed 2408 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5394, waitTime=2229, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:07 PDT 2014, retrying after 20095 ms, replay 2408 ops.
2014-07-10 16:12:27:331 260 sec: 2828736 operations; 9435.96 current ops/sec; [INSERT AverageLatency(us)=1592.89] 
14/07/10 16:12:32 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2882 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5692, waitTime=2306, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:41 PDT 2014, retrying after 10039 ms, replay 2882 ops.
14/07/10 16:12:32 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2542 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5692, waitTime=2306, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:41 PDT 2014, retrying after 10047 ms, replay 2542 ops.
14/07/10 16:12:32 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2931 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5735, waitTime=2278, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:42 PDT 2014, retrying after 10023 ms, replay 2931 ops.
2014-07-10 16:12:37:331 270 sec: 3058867 operations; 23013.1 current ops/sec; [INSERT AverageLatency(us)=548.86] 
14/07/10 16:12:44 INFO client.AsyncProcess: #12, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:05 PDT 2014
14/07/10 16:12:44 INFO client.AsyncProcess: #18, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:05 PDT 2014
14/07/10 16:12:44 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 2882 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6152, waitTime=2052, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:41 PDT 2014, retrying after 10030 ms, replay 2882 ops.
14/07/10 16:12:44 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 2542 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6152, waitTime=2052, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:41 PDT 2014, retrying after 10098 ms, replay 2542 ops.
14/07/10 16:12:44 INFO client.AsyncProcess: #18, table=usertable, attempt=13/35 failed 2408 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6175, waitTime=2123, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:07 PDT 2014, retrying after 20124 ms, replay 2408 ops.
14/07/10 16:12:44 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 failed 2926 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6175, waitTime=2123, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:05 PDT 2014, retrying after 20180 ms, replay 2926 ops.
14/07/10 16:12:45 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2931 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6179, waitTime=2479, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:42 PDT 2014, retrying after 10079 ms, replay 2931 ops.
14/07/10 16:12:45 INFO client.AsyncProcess: #17, table=usertable, attempt=13/35 failed 2953 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6179, waitTime=2479, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:06 PDT 2014, retrying after 20062 ms, replay 2953 ops.
2014-07-10 16:12:47:332 280 sec: 3261590 operations; 20270.27 current ops/sec; [INSERT AverageLatency(us)=1047.25] 
14/07/10 16:12:56 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2391 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6551, waitTime=2035, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:12:05 PDT 2014, retrying after 10085 ms, replay 2391 ops.
14/07/10 16:12:56 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 2542 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6551, waitTime=2035, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:41 PDT 2014, retrying after 20000 ms, replay 2542 ops.
14/07/10 16:12:56 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:41 PDT 2014
14/07/10 16:12:57 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 2931 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6589, waitTime=2300, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:42 PDT 2014, retrying after 20159 ms, replay 2931 ops.
14/07/10 16:12:57 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2602 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6589, waitTime=2300, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:12:07 PDT 2014, retrying after 10005 ms, replay 2602 ops.
2014-07-10 16:12:57:332 290 sec: 3386333 operations; 12474.3 current ops/sec; [INSERT AverageLatency(us)=1292.69] 
14/07/10 16:12:57 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2515 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6605, waitTime=2091, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:12:07 PDT 2014, retrying after 10031 ms, replay 2515 ops.
14/07/10 16:13:06 INFO client.AsyncProcess: #18, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:07 PDT 2014
14/07/10 16:13:06 INFO client.AsyncProcess: #17, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:06 PDT 2014
14/07/10 16:13:06 INFO client.AsyncProcess: #15, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:05 PDT 2014
2014-07-10 16:13:07:411 300 sec: 3642407 operations; 25406.69 current ops/sec; [INSERT AverageLatency(us)=1677.72] 
14/07/10 16:13:08 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2391 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7012, waitTime=2160, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:12:05 PDT 2014, retrying after 10043 ms, replay 2391 ops.
14/07/10 16:13:09 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2515 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7049, waitTime=2063, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:12:07 PDT 2014, retrying after 10042 ms, replay 2515 ops.
14/07/10 16:13:09 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 2602 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7041, waitTime=2067, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:12:07 PDT 2014, retrying after 10059 ms, replay 2602 ops.
2014-07-10 16:13:17:411 310 sec: 3781207 operations; 13880 current ops/sec; [INSERT AverageLatency(us)=742.16] 
14/07/10 16:13:19 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 failed 2542 ops, last exception: java.io.IOException: Unexpected closed connection on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:41 PDT 2014, retrying after 20199 ms, replay 2542 ops.
14/07/10 16:13:19 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 failed 2391 ops, last exception: java.io.IOException: Unexpected closed connection on slave1,60020,1405061745702, tracking started Thu Jul 10 16:12:05 PDT 2014, retrying after 20008 ms, replay 2391 ops.
14/07/10 16:13:19 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 failed 2931 ops, last exception: java.io.IOException: Unexpected closed connection on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:42 PDT 2014, retrying after 20093 ms, replay 2931 ops.
14/07/10 16:13:19 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 failed 2515 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: java.io.IOException: The stream is closed on slave1,60020,1405061745702, tracking started Thu Jul 10 16:12:07 PDT 2014, retrying after 20125 ms, replay 2515 ops.
14/07/10 16:13:19 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 failed 2602 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: java.io.IOException: The stream is closed on slave1,60020,1405061745702, tracking started Thu Jul 10 16:12:07 PDT 2014, retrying after 20198 ms, replay 2602 ops.
14/07/10 16:13:23 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2781 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44799 remote=slave1/9.1.143.59:60020] on slave1,60020,1405061745702, tracking started Thu Jul 10 16:12:34 PDT 2014, retrying after 10028 ms, replay 2781 ops.
2014-07-10 16:13:27:412 320 sec: 3781207 operations; 0 current ops/sec;  
14/07/10 16:13:34 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:12:34 PDT 2014
2014-07-10 16:13:37:412 330 sec: 3944405 operations; 16319.8 current ops/sec; [INSERT AverageLatency(us)=1301.3] 
14/07/10 16:13:40 INFO client.AsyncProcess: #19, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:12:05 PDT 2014
14/07/10 16:13:40 INFO client.AsyncProcess: #4, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:41 PDT 2014
14/07/10 16:13:40 INFO client.AsyncProcess: #20, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:11:42 PDT 2014
14/07/10 16:13:41 INFO client.AsyncProcess: #8, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:12:07 PDT 2014
14/07/10 16:13:41 INFO client.AsyncProcess: #14, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:12:07 PDT 2014
2014-07-10 16:13:47:413 340 sec: 4355100 operations; 41065.39 current ops/sec; [INSERT AverageLatency(us)=1875.24] 
14/07/10 16:13:57 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2524 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8782, waitTime=2115, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 10010 ms, replay 2524 ops.
14/07/10 16:13:57 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2226 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8782, waitTime=2115, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:08 PDT 2014, retrying after 10088 ms, replay 2226 ops.
2014-07-10 16:13:57:413 350 sec: 4678777 operations; 32367.7 current ops/sec; [INSERT AverageLatency(us)=407.62] 
14/07/10 16:13:57 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2863 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8782, waitTime=2115, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 10031 ms, replay 2863 ops.
14/07/10 16:13:57 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2938 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8782, waitTime=2115, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 10062 ms, replay 2938 ops.
14/07/10 16:13:57 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2933 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8782, waitTime=2115, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 10082 ms, replay 2933 ops.
14/07/10 16:13:57 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2885 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8782, waitTime=2115, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 10041 ms, replay 2885 ops.
14/07/10 16:13:57 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 1912 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8782, waitTime=2115, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 10033 ms, replay 1912 ops.
2014-07-10 16:14:07:414 360 sec: 4821227 operations; 14243.58 current ops/sec; [INSERT AverageLatency(us)=756.69] 
14/07/10 16:14:09 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:08 PDT 2014
14/07/10 16:14:09 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014
14/07/10 16:14:10 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 2933 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9262, waitTime=2810, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 10007 ms, replay 2933 ops.
14/07/10 16:14:10 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2885 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9262, waitTime=2810, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 10042 ms, replay 2885 ops.
14/07/10 16:14:10 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014
14/07/10 16:14:10 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 1912 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9262, waitTime=2810, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 10094 ms, replay 1912 ops.
14/07/10 16:14:10 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2938 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9262, waitTime=2810, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 10081 ms, replay 2938 ops.
2014-07-10 16:14:17:414 370 sec: 4955664 operations; 13443.7 current ops/sec; [INSERT AverageLatency(us)=1527.45] 
14/07/10 16:14:22 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 failed 1912 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9737, waitTime=2555, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 20090 ms, replay 1912 ops.
14/07/10 16:14:22 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 2938 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9737, waitTime=2555, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 20051 ms, replay 2938 ops.
14/07/10 16:14:22 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 failed 2885 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9737, waitTime=2555, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 20030 ms, replay 2885 ops.
14/07/10 16:14:22 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 failed 2933 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9737, waitTime=2555, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 20144 ms, replay 2933 ops.
2014-07-10 16:14:27:463 380 sec: 5286543 operations; 32926.56 current ops/sec; [INSERT AverageLatency(us)=622.35] 
2014-07-10 16:14:37:464 390 sec: 5307861 operations; 2131.59 current ops/sec; [INSERT AverageLatency(us)=2103.12] 
14/07/10 16:14:45 INFO client.AsyncProcess: #16, table=usertable, attempt=13/35 failed 1912 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=10400, waitTime=2779, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 20036 ms, replay 1912 ops.
14/07/10 16:14:45 INFO client.AsyncProcess: #13, table=usertable, attempt=13/35 failed 2885 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=10400, waitTime=2779, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 20086 ms, replay 2885 ops.
14/07/10 16:14:45 INFO client.AsyncProcess: #12, table=usertable, attempt=13/35 failed 2933 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=10400, waitTime=2779, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 20195 ms, replay 2933 ops.
14/07/10 16:14:45 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 failed 2938 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=10400, waitTime=2779, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 20058 ms, replay 2938 ops.
2014-07-10 16:14:47:464 400 sec: 5307861 operations; 0 current ops/sec;  
2014-07-10 16:14:57:465 410 sec: 5529159 operations; 22127.59 current ops/sec; [UPDATE AverageLatency(us)=29426232] [INSERT AverageLatency(us)=1457.7] [CLEANUP AverageLatency(us)=29426383] 
14/07/10 16:15:07 INFO client.AsyncProcess: #16, table=usertable, attempt=14/35 failed 1912 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11019, waitTime=2006, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 20121 ms, replay 1912 ops.
14/07/10 16:15:07 INFO client.AsyncProcess: #13, table=usertable, attempt=14/35 failed 2885 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11020, waitTime=2187, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 20114 ms, replay 2885 ops.
14/07/10 16:15:07 INFO client.AsyncProcess: #12, table=usertable, attempt=14/35 failed 2933 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11020, waitTime=2187, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 20145 ms, replay 2933 ops.
14/07/10 16:15:07 INFO client.AsyncProcess: #9, table=usertable, attempt=14/35 failed 2938 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11020, waitTime=2187, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 20131 ms, replay 2938 ops.
2014-07-10 16:15:07:465 420 sec: 5706059 operations; 17690 current ops/sec;  [INSERT AverageLatency(us)=194.83]  
14/07/10 16:15:17 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2913 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11406, waitTime=2408, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:14:21 PDT 2014, retrying after 10085 ms, replay 2913 ops.
14/07/10 16:15:17 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2937 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11406, waitTime=2408, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:14:21 PDT 2014, retrying after 10087 ms, replay 2937 ops.
2014-07-10 16:15:17:466 430 sec: 6082607 operations; 37651.03 current ops/sec;  [INSERT AverageLatency(us)=766.55]  
2014-07-10 16:15:27:467 440 sec: 6478713 operations; 39610.6 current ops/sec; [UPDATE AverageLatency(us)=1980383] [INSERT AverageLatency(us)=295.51] [CLEANUP AverageLatency(us)=1980875] 
14/07/10 16:15:29 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2937 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11920, waitTime=2432, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:14:21 PDT 2014, retrying after 10038 ms, replay 2937 ops.
14/07/10 16:15:29 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 2913 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11920, waitTime=2432, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:14:21 PDT 2014, retrying after 10055 ms, replay 2913 ops.
14/07/10 16:15:29 INFO client.AsyncProcess: #16, table=usertable, attempt=15/35 failed 1912 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11920, waitTime=2432, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 20000 ms, replay 1912 ops.
14/07/10 16:15:29 INFO client.AsyncProcess: #13, table=usertable, attempt=15/35 failed 2885 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11949, waitTime=2017, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 20102 ms, replay 2885 ops.
14/07/10 16:15:29 INFO client.AsyncProcess: #9, table=usertable, attempt=15/35 failed 2938 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11949, waitTime=2017, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 20118 ms, replay 2938 ops.
14/07/10 16:15:29 INFO client.AsyncProcess: #12, table=usertable, attempt=15/35 failed 2933 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11951, waitTime=2000, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 20126 ms, replay 2933 ops.
2014-07-10 16:15:37:467 450 sec: 6599897 operations; 12117.19 current ops/sec;  [INSERT AverageLatency(us)=682.68]  
14/07/10 16:15:40 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:14:21 PDT 2014
14/07/10 16:15:40 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:14:21 PDT 2014
2014-07-10 16:15:47:468 460 sec: 6975809 operations; 37587.44 current ops/sec; [UPDATE AverageLatency(us)=4263440] [INSERT AverageLatency(us)=729.45] [CLEANUP AverageLatency(us)=4263451] 
14/07/10 16:15:51 INFO client.AsyncProcess: #9, table=usertable, attempt=16/35 failed 2938 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=12782, waitTime=2338, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 20164 ms, replay 2938 ops.
14/07/10 16:15:51 INFO client.AsyncProcess: #13, table=usertable, attempt=16/35 failed 2885 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=12782, waitTime=2338, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 20164 ms, replay 2885 ops.
14/07/10 16:15:51 INFO client.AsyncProcess: #16, table=usertable, attempt=16/35 failed 1912 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=12782, waitTime=2338, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 20143 ms, replay 1912 ops.
14/07/10 16:15:51 INFO client.AsyncProcess: #12, table=usertable, attempt=16/35 failed 2933 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=12794, waitTime=2213, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 20099 ms, replay 2933 ops.
2014-07-10 16:15:57:468 470 sec: 6996605 operations; 2079.6 current ops/sec;  [INSERT AverageLatency(us)=2877.31]  
2014-07-10 16:16:07:469 480 sec: 7164009 operations; 16738.73 current ops/sec; [UPDATE AverageLatency(us)=7191894] [INSERT AverageLatency(us)=763.78] [CLEANUP AverageLatency(us)=7191905] 
14/07/10 16:16:14 INFO client.AsyncProcess: #13, table=usertable, attempt=17/35 failed 2885 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=13316, waitTime=2271, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 20128 ms, replay 2885 ops.
14/07/10 16:16:14 INFO client.AsyncProcess: #12, table=usertable, attempt=17/35 failed 2933 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=13316, waitTime=2271, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 20134 ms, replay 2933 ops.
14/07/10 16:16:14 INFO client.AsyncProcess: #9, table=usertable, attempt=17/35 failed 2938 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=13316, waitTime=2271, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 20116 ms, replay 2938 ops.
14/07/10 16:16:14 INFO client.AsyncProcess: #16, table=usertable, attempt=17/35 failed 1912 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=13316, waitTime=2271, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014, retrying after 20061 ms, replay 1912 ops.
2014-07-10 16:16:17:469 490 sec: 7229444 operations; 6543.5 current ops/sec;  [INSERT AverageLatency(us)=368.1]  
2014-07-10 16:16:27:470 500 sec: 7525919 operations; 29644.54 current ops/sec; [UPDATE AverageLatency(us)=21431703] [INSERT AverageLatency(us)=502.44] [CLEANUP AverageLatency(us)=21431714] 
14/07/10 16:16:34 INFO client.AsyncProcess: #12, table=usertable, attempt=18/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014
14/07/10 16:16:35 INFO client.AsyncProcess: #16, table=usertable, attempt=18/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014
14/07/10 16:16:35 INFO client.AsyncProcess: #13, table=usertable, attempt=18/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014
14/07/10 16:16:35 INFO client.AsyncProcess: #9, table=usertable, attempt=18/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:13:15 PDT 2014
14/07/10 16:16:37 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2954 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14185, waitTime=2415, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:15:43 PDT 2014, retrying after 10094 ms, replay 2954 ops.
14/07/10 16:16:37 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2165 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14185, waitTime=2415, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:15:45 PDT 2014, retrying after 10051 ms, replay 2165 ops.
2014-07-10 16:16:37:471 510 sec: 8029389 operations; 50347 current ops/sec; [UPDATE AverageLatency(us)=1636132] [INSERT AverageLatency(us)=1639.58] [CLEANUP AverageLatency(us)=1636145] 
14/07/10 16:16:37 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2804 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14190, waitTime=2006, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:15:44 PDT 2014, retrying after 10009 ms, replay 2804 ops.
2014-07-10 16:16:47:471 520 sec: 8453083 operations; 42365.16 current ops/sec; [UPDATE AverageLatency(us)=2222057] [INSERT AverageLatency(us)=229.78] [CLEANUP AverageLatency(us)=2222068] 
14/07/10 16:16:49 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2804 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14707, waitTime=2002, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:15:44 PDT 2014, retrying after 10030 ms, replay 2804 ops.
14/07/10 16:16:49 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2165 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14708, waitTime=2031, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:15:45 PDT 2014, retrying after 10006 ms, replay 2165 ops.
14/07/10 16:16:51 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2954 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14709, waitTime=3503, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:15:43 PDT 2014, retrying after 10086 ms, replay 2954 ops.
2014-07-10 16:16:57:472 530 sec: 8453131 operations; 4.8 current ops/sec;  [INSERT AverageLatency(us)=209213.48]  
14/07/10 16:17:02 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 failed 2804 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14927, waitTime=2657, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:15:44 PDT 2014, retrying after 20047 ms, replay 2804 ops.
14/07/10 16:17:02 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 failed 2165 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14927, waitTime=2657, rpcTimetout=2000 on slave1,60020,1405061745702, tracking started Thu Jul 10 16:15:45 PDT 2014, retrying after 20002 ms, replay 2165 ops.
14/07/10 16:17:05 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 failed 2954 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44801 remote=slave1/9.1.143.59:60020] on slave1,60020,1405061745702, tracking started Thu Jul 10 16:15:43 PDT 2014, retrying after 20073 ms, replay 2954 ops.
2014-07-10 16:17:07:472 540 sec: 8455661 operations; 253 current ops/sec;  [INSERT AverageLatency(us)=7444.27]  
2014-07-10 16:17:17:473 550 sec: 8593139 operations; 13746.43 current ops/sec;  [INSERT AverageLatency(us)=1286.82]  
14/07/10 16:17:23 INFO client.AsyncProcess: #18, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:15:45 PDT 2014
14/07/10 16:17:23 INFO client.AsyncProcess: #14, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:15:44 PDT 2014
14/07/10 16:17:27 INFO client.AsyncProcess: #14, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405061745702, tracking started Thu Jul 10 16:15:43 PDT 2014
2014-07-10 16:17:27:473 560 sec: 8869162 operations; 27602.3 current ops/sec; [UPDATE AverageLatency(us)=1613003] [INSERT AverageLatency(us)=1250.03] [CLEANUP AverageLatency(us)=1613013] 
2014-07-10 16:17:37:474 570 sec: 9105536 operations; 23635.04 current ops/sec; [UPDATE AverageLatency(us)=1898427.33] [INSERT AverageLatency(us)=116.04] [CLEANUP AverageLatency(us)=1898439.33] 
2014-07-10 16:17:47:475 580 sec: 9342304 operations; 23674.43 current ops/sec;  [INSERT AverageLatency(us)=705.76]  
2014-07-10 16:17:57:475 590 sec: 9756471 operations; 41416.7 current ops/sec; [UPDATE AverageLatency(us)=1683941.75] [INSERT AverageLatency(us)=175.61] [CLEANUP AverageLatency(us)=1683954.25] 
2014-07-10 16:18:04:321 597 sec: 10000000 operations; 35572.45 current ops/sec; [UPDATE AverageLatency(us)=671060.5] [INSERT AverageLatency(us)=68.66] [CLEANUP AverageLatency(us)=671071] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1405034284
1405034284
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ false
+ false
+ false
+ false
+ false
+ false
+ false
+ false
+ let counter=1+1
+ read line
+ set +x
