++ ls caseresult/ -ltr
++ wc -l
+ filename=case20
+ mkdir caseresult/case20
+ RESULT_DIR=/home/hadoop/git/physical_design/caseresult/case20
+ TEN=10
+ SLEEP_TIME=300
+ YCSB_DIR=/home/hadoop/ycsb-0.1.4
+ number_of_operations=5000000
+ number_of_threads=20
+ number_of_records=5000000
+ output_file_suffix=.dat
+ experiment_list_file=/home/hadoop/git/physical_design/case20.list
+ clean=false
+ create=false
+ load=false
+ random_read=false
+ scan=false
+ all=false
+ for i in '$@'
+ '[' all == all ']'
+ all=true
+ let counter=1
+ cd /home/hadoop/ycsb-0.1.4
++ pwd
+ echo /home/hadoop/ycsb-0.1.4
/home/hadoop/ycsb-0.1.4
+ read line
+ true
+ echo 'droping usertable...'
droping usertable...
+ hbase shell /home/hadoop/git/physical_design/delete_table
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/hadoop/hbase-0.98.3-hadoop1/lib/slf4j-log4j12-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/hadoop/hadoop-1.2.1/lib/slf4j-log4j12-1.4.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
0 row(s) in 34.7490 seconds

0 row(s) in 0.8020 seconds

0 row(s) in 0.0700 seconds

+ echo 'sleeping for 300 ...'
sleeping for 300 ...
+ sleep 300
+ true
+ echo 'creating usertable...'
creating usertable...
+ create_statement='create '\''usertable'\'', { NAME=>'\''family'\'', BLOOMFILTER=>'\''ROWCOL'\''}, SPLITS => ['\''user1'\'', '\''user2'\'', '\''user3'\'', '\''user4'\'', '\''user5'\'', '\''user6'\'', '\''user7'\'', '\''user8'\'', '\''user9'\'']'
+ echo create ''\''usertable'\'',' '{' 'NAME=>'\''family'\'',' 'BLOOMFILTER=>'\''ROWCOL'\''},' SPLITS '=>' '['\''user1'\'',' ''\''user2'\'',' ''\''user3'\'',' ''\''user4'\'',' ''\''user5'\'',' ''\''user6'\'',' ''\''user7'\'',' ''\''user8'\'',' ''\''user9'\'']'
+ echo 'exit '
+ create_table /home/hadoop/git/physical_design/caseresult/case20/create_1.script
+ echo 'creating table...'
creating table...
+ echo /home/hadoop/git/physical_design/caseresult/case20/create_1.script
/home/hadoop/git/physical_design/caseresult/case20/create_1.script
+ hbase shell /home/hadoop/git/physical_design/caseresult/case20/create_1.script
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/hadoop/hbase-0.98.3-hadoop1/lib/slf4j-log4j12-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/hadoop/hadoop-1.2.1/lib/slf4j-log4j12-1.4.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
0 row(s) in 2.2000 seconds

+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo 'loading data...'
loading data...
+ echo 'starting time: '
starting time: 
++ date +%s
+ echo 1404663467
1404663467
++ echo /home/hadoop/git/physical_design/caseresult/case20/load_1.dat
+ ./ld 5000000 20 /home/hadoop/git/physical_design/caseresult/case20/load_1.dat
Loading workload...
Starting test.
2014-07-06 09:17:47:927 0 sec: 0 operations; 
14/07/06 09:17:48 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/06 09:17:48 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/06 09:17:48 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/06 09:17:48 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/06 09:17:48 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/06 09:17:48 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/06 09:17:48 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/06 09:17:48 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/06 09:17:48 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/06 09:17:48 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/06 09:17:48 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/06 09:17:48 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/06 09:17:48 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/06 09:17:48 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/06 09:17:48 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/06 09:17:48 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x5e852b9, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/06 09:17:48 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x5e852b9 connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/06 09:17:48 INFO zookeeper.ClientCnxn: Opening socket connection to server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/06 09:17:48 INFO zookeeper.ClientCnxn: Socket connection established to sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, initiating session
14/07/06 09:17:48 INFO zookeeper.ClientCnxn: Session establishment complete on server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, sessionid = 0x470c721260000e, negotiated timeout = 90000
2014-07-06 09:17:57:940 10 sec: 280011 operations; 27925.7 current ops/sec; [INSERT AverageLatency(us)=362.51] 
2014-07-06 09:18:09:903 21 sec: 328700 operations; 4070.65 current ops/sec; [INSERT AverageLatency(us)=90.18] 
14/07/06 09:18:15 INFO zookeeper.ClientCnxn: Unable to read additional data from server sessionid 0x470c721260000e, likely server has closed socket, closing socket connection and attempting reconnect
14/07/06 09:18:15 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/06 09:18:15 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/06 09:18:15 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x470c721260000e, negotiated timeout = 90000
14/07/06 09:18:15 INFO zookeeper.ClientCnxn: Unable to read additional data from server sessionid 0x470c721260000e, likely server has closed socket, closing socket connection and attempting reconnect
14/07/06 09:18:16 INFO zookeeper.ClientCnxn: Opening socket connection to server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/06 09:18:16 INFO zookeeper.ClientCnxn: Socket connection established to sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, initiating session
14/07/06 09:18:16 INFO zookeeper.ClientCnxn: Session establishment complete on server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, sessionid = 0x470c721260000e, negotiated timeout = 90000
2014-07-06 09:18:19:915 32 sec: 328700 operations; 0 current ops/sec;  
2014-07-06 09:18:29:916 42 sec: 328700 operations; 0 current ops/sec;  
2014-07-06 09:18:39:916 52 sec: 328700 operations; 0 current ops/sec;  
2014-07-06 09:18:49:917 62 sec: 328700 operations; 0 current ops/sec;  
2014-07-06 09:18:59:918 72 sec: 328700 operations; 0 current ops/sec;  
2014-07-06 09:19:09:918 82 sec: 328700 operations; 0 current ops/sec;  
14/07/06 09:19:13 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2262 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=586, waitTime=2575, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10066 ms, replay 2262 ops.
14/07/06 09:19:13 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2257 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=586, waitTime=2575, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10030 ms, replay 2257 ops.
14/07/06 09:19:13 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2254 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=586, waitTime=2575, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10046 ms, replay 2254 ops.
14/07/06 09:19:13 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2190 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=586, waitTime=2575, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10079 ms, replay 2190 ops.
14/07/06 09:19:13 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2171 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=586, waitTime=2575, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10043 ms, replay 2171 ops.
14/07/06 09:19:13 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2323 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=586, waitTime=2575, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10069 ms, replay 2323 ops.
14/07/06 09:19:13 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2220 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=586, waitTime=2575, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10057 ms, replay 2220 ops.
14/07/06 09:19:13 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2306 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=586, waitTime=2575, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10010 ms, replay 2306 ops.
14/07/06 09:19:13 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2265 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=586, waitTime=2575, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10030 ms, replay 2265 ops.
14/07/06 09:19:13 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2306 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=586, waitTime=2575, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10007 ms, replay 2306 ops.
14/07/06 09:19:13 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2292 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=586, waitTime=2575, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10016 ms, replay 2292 ops.
14/07/06 09:19:13 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 2273 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=586, waitTime=2575, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10079 ms, replay 2273 ops.
14/07/06 09:19:13 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2248 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=586, waitTime=2575, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:54 PDT 2014, retrying after 10015 ms, replay 2248 ops.
14/07/06 09:19:13 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2278 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=586, waitTime=2575, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10082 ms, replay 2278 ops.
14/07/06 09:19:13 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2254 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=586, waitTime=2575, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10047 ms, replay 2254 ops.
14/07/06 09:19:13 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2279 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=586, waitTime=2575, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10062 ms, replay 2279 ops.
14/07/06 09:19:13 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2264 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=586, waitTime=2575, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10066 ms, replay 2264 ops.
14/07/06 09:19:13 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2241 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=586, waitTime=2575, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10031 ms, replay 2241 ops.
14/07/06 09:19:13 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2304 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=586, waitTime=2575, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10092 ms, replay 2304 ops.
14/07/06 09:19:16 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2316 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=609, waitTime=2079, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10009 ms, replay 2316 ops.
14/07/06 09:19:18 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2265 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=610, waitTime=3324, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10099 ms, replay 2265 ops.
14/07/06 09:19:18 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2233 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=610, waitTime=3324, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:55 PDT 2014, retrying after 10010 ms, replay 2233 ops.
14/07/06 09:19:19 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2225 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=614, waitTime=3079, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:55 PDT 2014, retrying after 10017 ms, replay 2225 ops.
14/07/06 09:19:19 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2237 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=614, waitTime=3079, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:56 PDT 2014, retrying after 10069 ms, replay 2237 ops.
14/07/06 09:19:19 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2262 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=614, waitTime=3079, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:54 PDT 2014, retrying after 10093 ms, replay 2262 ops.
14/07/06 09:19:19 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 2280 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=614, waitTime=3079, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:55 PDT 2014, retrying after 10056 ms, replay 2280 ops.
14/07/06 09:19:19 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2287 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=614, waitTime=3079, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:55 PDT 2014, retrying after 10096 ms, replay 2287 ops.
14/07/06 09:19:19 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2226 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=614, waitTime=3079, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:55 PDT 2014, retrying after 10043 ms, replay 2226 ops.
14/07/06 09:19:19 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2228 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=614, waitTime=3079, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:55 PDT 2014, retrying after 10072 ms, replay 2228 ops.
14/07/06 09:19:19 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2320 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=614, waitTime=3079, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:54 PDT 2014, retrying after 10012 ms, replay 2320 ops.
14/07/06 09:19:19 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2266 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=614, waitTime=3079, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:56 PDT 2014, retrying after 10068 ms, replay 2266 ops.
14/07/06 09:19:19 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2313 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=614, waitTime=3079, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:55 PDT 2014, retrying after 10091 ms, replay 2313 ops.
14/07/06 09:19:19 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2258 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=614, waitTime=3079, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:56 PDT 2014, retrying after 10036 ms, replay 2258 ops.
2014-07-06 09:19:19:919 92 sec: 328700 operations; 0 current ops/sec;  
14/07/06 09:19:20 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2273 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=627, waitTime=2389, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:54 PDT 2014, retrying after 10059 ms, replay 2273 ops.
14/07/06 09:19:20 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=627, waitTime=2389, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:58 PDT 2014, retrying after 10076 ms, replay 2247 ops.
14/07/06 09:19:20 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2270 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=627, waitTime=2389, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:57 PDT 2014, retrying after 10039 ms, replay 2270 ops.
14/07/06 09:19:20 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2277 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=627, waitTime=2389, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:57 PDT 2014, retrying after 10061 ms, replay 2277 ops.
14/07/06 09:19:20 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2254 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=627, waitTime=2389, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:55 PDT 2014, retrying after 10071 ms, replay 2254 ops.
14/07/06 09:19:20 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2298 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=627, waitTime=2389, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:57 PDT 2014, retrying after 10036 ms, replay 2298 ops.
14/07/06 09:19:20 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2253 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=627, waitTime=2389, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:58 PDT 2014, retrying after 10078 ms, replay 2253 ops.
14/07/06 09:19:20 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2190 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=627, waitTime=2389, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:56 PDT 2014, retrying after 10084 ms, replay 2190 ops.
14/07/06 09:19:20 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2229 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=627, waitTime=2389, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:58 PDT 2014, retrying after 10094 ms, replay 2229 ops.
14/07/06 09:19:20 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2272 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=627, waitTime=2389, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:57 PDT 2014, retrying after 10034 ms, replay 2272 ops.
14/07/06 09:19:20 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2204 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=627, waitTime=2389, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:58 PDT 2014, retrying after 10033 ms, replay 2204 ops.
14/07/06 09:19:20 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2302 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=627, waitTime=2389, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:56 PDT 2014, retrying after 10011 ms, replay 2302 ops.
14/07/06 09:19:20 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2267 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=627, waitTime=2389, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:58 PDT 2014, retrying after 10043 ms, replay 2267 ops.
14/07/06 09:19:20 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2230 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=627, waitTime=2389, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:57 PDT 2014, retrying after 10015 ms, replay 2230 ops.
14/07/06 09:19:25 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2232 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:43238 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:58 PDT 2014, retrying after 10044 ms, replay 2232 ops.
14/07/06 09:19:26 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2248 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=644, waitTime=2547, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:54 PDT 2014, retrying after 10052 ms, replay 2248 ops.
14/07/06 09:19:26 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 2279 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=644, waitTime=2547, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10050 ms, replay 2279 ops.
14/07/06 09:19:26 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 2254 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=644, waitTime=2547, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10068 ms, replay 2254 ops.
14/07/06 09:19:26 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2306 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=644, waitTime=2547, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10089 ms, replay 2306 ops.
14/07/06 09:19:26 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2304 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=644, waitTime=2547, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10099 ms, replay 2304 ops.
14/07/06 09:19:26 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2306 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=644, waitTime=2547, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10073 ms, replay 2306 ops.
14/07/06 09:19:26 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 2292 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=644, waitTime=2547, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10068 ms, replay 2292 ops.
14/07/06 09:19:26 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2257 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=644, waitTime=2547, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10031 ms, replay 2257 ops.
14/07/06 09:19:26 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2171 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=644, waitTime=2547, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10044 ms, replay 2171 ops.
14/07/06 09:19:26 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2254 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=644, waitTime=2547, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10046 ms, replay 2254 ops.
14/07/06 09:19:26 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2220 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=644, waitTime=2547, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10066 ms, replay 2220 ops.
14/07/06 09:19:26 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 2273 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=644, waitTime=2547, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10027 ms, replay 2273 ops.
14/07/06 09:19:26 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2323 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=644, waitTime=2547, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10070 ms, replay 2323 ops.
14/07/06 09:19:26 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2190 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=644, waitTime=2547, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10079 ms, replay 2190 ops.
14/07/06 09:19:26 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2260 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=644, waitTime=2547, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:59 PDT 2014, retrying after 10081 ms, replay 2260 ops.
14/07/06 09:19:26 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2309 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=644, waitTime=2547, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:59 PDT 2014, retrying after 10091 ms, replay 2309 ops.
14/07/06 09:19:26 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2264 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=644, waitTime=2547, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10077 ms, replay 2264 ops.
14/07/06 09:19:26 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 2262 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=644, waitTime=2547, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10001 ms, replay 2262 ops.
14/07/06 09:19:26 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2265 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=644, waitTime=2547, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10050 ms, replay 2265 ops.
14/07/06 09:19:26 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2241 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=644, waitTime=2547, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10087 ms, replay 2241 ops.
14/07/06 09:19:26 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 2278 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=644, waitTime=2547, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10016 ms, replay 2278 ops.
14/07/06 09:19:28 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2316 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=667, waitTime=2178, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10061 ms, replay 2316 ops.
2014-07-06 09:19:29:920 102 sec: 328700 operations; 0 current ops/sec;  
14/07/06 09:19:30 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2265 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:43238 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 10068 ms, replay 2265 ops.
14/07/06 09:19:30 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2233 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:43238 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:55 PDT 2014, retrying after 10084 ms, replay 2233 ops.
14/07/06 09:19:32 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2258 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=672, waitTime=2529, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:56 PDT 2014, retrying after 10010 ms, replay 2258 ops.
14/07/06 09:19:32 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 2280 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=672, waitTime=2529, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:55 PDT 2014, retrying after 10012 ms, replay 2280 ops.
14/07/06 09:19:32 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 2287 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=672, waitTime=2529, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:55 PDT 2014, retrying after 10063 ms, replay 2287 ops.
14/07/06 09:19:32 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2266 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=672, waitTime=2529, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:56 PDT 2014, retrying after 10046 ms, replay 2266 ops.
14/07/06 09:19:32 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2226 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=672, waitTime=2529, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:55 PDT 2014, retrying after 10027 ms, replay 2226 ops.
14/07/06 09:19:32 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2313 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=672, waitTime=2529, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:55 PDT 2014, retrying after 10019 ms, replay 2313 ops.
14/07/06 09:19:32 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2225 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=672, waitTime=2529, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:55 PDT 2014, retrying after 10038 ms, replay 2225 ops.
14/07/06 09:19:32 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2320 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=672, waitTime=2529, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:54 PDT 2014, retrying after 10005 ms, replay 2320 ops.
14/07/06 09:19:32 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 2237 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=672, waitTime=2529, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:56 PDT 2014, retrying after 10073 ms, replay 2237 ops.
14/07/06 09:19:32 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 2262 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=672, waitTime=2529, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:54 PDT 2014, retrying after 10090 ms, replay 2262 ops.
14/07/06 09:19:32 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 2228 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=672, waitTime=2529, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:55 PDT 2014, retrying after 10049 ms, replay 2228 ops.
14/07/06 09:19:33 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2270 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=683, waitTime=2527, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:57 PDT 2014, retrying after 10019 ms, replay 2270 ops.
14/07/06 09:19:33 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2229 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=683, waitTime=2527, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:58 PDT 2014, retrying after 10031 ms, replay 2229 ops.
14/07/06 09:19:33 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2254 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=683, waitTime=2527, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:55 PDT 2014, retrying after 10046 ms, replay 2254 ops.
14/07/06 09:19:33 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2190 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=683, waitTime=2527, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:56 PDT 2014, retrying after 10006 ms, replay 2190 ops.
14/07/06 09:19:33 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2302 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=683, waitTime=2527, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:56 PDT 2014, retrying after 10096 ms, replay 2302 ops.
14/07/06 09:19:33 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2277 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=683, waitTime=2527, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:57 PDT 2014, retrying after 10034 ms, replay 2277 ops.
14/07/06 09:19:33 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2253 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=683, waitTime=2527, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:58 PDT 2014, retrying after 10083 ms, replay 2253 ops.
14/07/06 09:19:33 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2272 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=683, waitTime=2527, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:57 PDT 2014, retrying after 10078 ms, replay 2272 ops.
14/07/06 09:19:33 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2273 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=683, waitTime=2527, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:54 PDT 2014, retrying after 10042 ms, replay 2273 ops.
14/07/06 09:19:33 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2204 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=683, waitTime=2527, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:58 PDT 2014, retrying after 10034 ms, replay 2204 ops.
14/07/06 09:19:33 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2267 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=683, waitTime=2527, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:58 PDT 2014, retrying after 10045 ms, replay 2267 ops.
14/07/06 09:19:33 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2230 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=683, waitTime=2527, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:57 PDT 2014, retrying after 10098 ms, replay 2230 ops.
14/07/06 09:19:33 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=683, waitTime=2527, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:58 PDT 2014, retrying after 10001 ms, replay 2247 ops.
14/07/06 09:19:33 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2298 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=683, waitTime=2527, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:57 PDT 2014, retrying after 10026 ms, replay 2298 ops.
14/07/06 09:19:37 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2232 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=701, waitTime=2434, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:58 PDT 2014, retrying after 10012 ms, replay 2232 ops.
14/07/06 09:19:38 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 failed 2248 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=702, waitTime=2049, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:54 PDT 2014, retrying after 20010 ms, replay 2248 ops.
14/07/06 09:19:38 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 2262 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=702, waitTime=2049, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20078 ms, replay 2262 ops.
14/07/06 09:19:38 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 failed 2273 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=702, waitTime=2049, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20051 ms, replay 2273 ops.
14/07/06 09:19:38 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 failed 2257 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=702, waitTime=2049, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20054 ms, replay 2257 ops.
14/07/06 09:19:38 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 failed 2279 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=702, waitTime=2049, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20023 ms, replay 2279 ops.
14/07/06 09:19:38 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 failed 2171 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=702, waitTime=2049, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20078 ms, replay 2171 ops.
14/07/06 09:19:38 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 2278 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=702, waitTime=2049, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20148 ms, replay 2278 ops.
14/07/06 09:19:38 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2254 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=702, waitTime=2049, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20005 ms, replay 2254 ops.
14/07/06 09:19:38 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 failed 2265 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=710, waitTime=2494, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20003 ms, replay 2265 ops.
14/07/06 09:19:38 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 2304 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=710, waitTime=2494, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20199 ms, replay 2304 ops.
14/07/06 09:19:38 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2306 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=710, waitTime=2494, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20061 ms, replay 2306 ops.
14/07/06 09:19:38 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 failed 2306 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=710, waitTime=2494, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20128 ms, replay 2306 ops.
14/07/06 09:19:38 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2309 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=710, waitTime=2494, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:59 PDT 2014, retrying after 10049 ms, replay 2309 ops.
14/07/06 09:19:38 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 failed 2220 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=710, waitTime=2494, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20185 ms, replay 2220 ops.
14/07/06 09:19:38 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 failed 2323 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=710, waitTime=2494, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20106 ms, replay 2323 ops.
14/07/06 09:19:38 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 failed 2264 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=710, waitTime=2494, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20190 ms, replay 2264 ops.
14/07/06 09:19:38 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 2190 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=710, waitTime=2494, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20014 ms, replay 2190 ops.
14/07/06 09:19:38 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 2241 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=710, waitTime=2494, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20007 ms, replay 2241 ops.
14/07/06 09:19:38 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2260 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=710, waitTime=2494, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:59 PDT 2014, retrying after 10001 ms, replay 2260 ops.
14/07/06 09:19:38 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 failed 2254 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=710, waitTime=2494, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20126 ms, replay 2254 ops.
14/07/06 09:19:38 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 failed 2292 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=710, waitTime=2494, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20172 ms, replay 2292 ops.
14/07/06 09:19:39 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014
2014-07-06 09:19:39:921 112 sec: 328700 operations; 0 current ops/sec;  
14/07/06 09:19:41 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:55 PDT 2014
14/07/06 09:19:41 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014
14/07/06 09:19:43 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:54 PDT 2014
14/07/06 09:19:43 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:55 PDT 2014
14/07/06 09:19:43 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:55 PDT 2014
14/07/06 09:19:43 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:55 PDT 2014
14/07/06 09:19:43 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:54 PDT 2014
14/07/06 09:19:43 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:56 PDT 2014
14/07/06 09:19:43 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:55 PDT 2014
14/07/06 09:19:43 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:56 PDT 2014
14/07/06 09:19:43 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:56 PDT 2014
14/07/06 09:19:44 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:55 PDT 2014
14/07/06 09:19:44 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:55 PDT 2014
14/07/06 09:19:44 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:58 PDT 2014
14/07/06 09:19:44 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:56 PDT 2014
14/07/06 09:19:44 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:58 PDT 2014
14/07/06 09:19:45 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:55 PDT 2014
14/07/06 09:19:45 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:54 PDT 2014
14/07/06 09:19:45 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:57 PDT 2014
14/07/06 09:19:45 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:58 PDT 2014
14/07/06 09:19:45 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:58 PDT 2014
14/07/06 09:19:45 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:57 PDT 2014
14/07/06 09:19:45 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:57 PDT 2014
14/07/06 09:19:45 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:57 PDT 2014
14/07/06 09:19:45 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:56 PDT 2014
14/07/06 09:19:45 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:58 PDT 2014
14/07/06 09:19:45 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:57 PDT 2014
14/07/06 09:19:48 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:58 PDT 2014
14/07/06 09:19:49 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:59 PDT 2014
14/07/06 09:19:49 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:59 PDT 2014
2014-07-06 09:19:49:922 122 sec: 432012 operations; 10330.17 current ops/sec; [INSERT AverageLatency(us)=2163.67] 
14/07/06 09:19:59 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014
2014-07-06 09:19:59:923 132 sec: 624548 operations; 19251.67 current ops/sec; [INSERT AverageLatency(us)=754.77] 
14/07/06 09:20:00 INFO client.AsyncProcess: #17, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:54 PDT 2014
14/07/06 09:20:00 INFO client.AsyncProcess: #7, table=usertable, attempt=13/35 failed 2273 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=880, waitTime=2150, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20185 ms, replay 2273 ops.
14/07/06 09:20:00 INFO client.AsyncProcess: #3, table=usertable, attempt=13/35 failed 2171 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=880, waitTime=2150, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20174 ms, replay 2171 ops.
14/07/06 09:20:00 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 failed 2262 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=880, waitTime=2150, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20098 ms, replay 2262 ops.
14/07/06 09:20:00 INFO client.AsyncProcess: #17, table=usertable, attempt=13/35 failed 2257 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=880, waitTime=2150, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20178 ms, replay 2257 ops.
14/07/06 09:20:00 INFO client.AsyncProcess: #12, table=usertable, attempt=13/35 failed 2279 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=880, waitTime=2150, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20146 ms, replay 2279 ops.
14/07/06 09:20:00 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014
14/07/06 09:20:01 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 failed 2190 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=888, waitTime=2811, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20004 ms, replay 2190 ops.
14/07/06 09:20:01 INFO client.AsyncProcess: #18, table=usertable, attempt=13/35 failed 2323 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=888, waitTime=2811, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20035 ms, replay 2323 ops.
14/07/06 09:20:01 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 failed 2306 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=888, waitTime=2811, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20004 ms, replay 2306 ops.
14/07/06 09:20:01 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 failed 2304 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=888, waitTime=2811, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20125 ms, replay 2304 ops.
14/07/06 09:20:01 INFO client.AsyncProcess: #19, table=usertable, attempt=13/35 failed 2265 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=888, waitTime=2811, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20121 ms, replay 2265 ops.
14/07/06 09:20:01 INFO client.AsyncProcess: #8, table=usertable, attempt=13/35 failed 2254 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=888, waitTime=2811, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20187 ms, replay 2254 ops.
14/07/06 09:20:01 INFO client.AsyncProcess: #5, table=usertable, attempt=13/35 failed 2292 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=888, waitTime=2811, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20117 ms, replay 2292 ops.
14/07/06 09:20:01 INFO client.AsyncProcess: #14, table=usertable, attempt=13/35 failed 2220 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=888, waitTime=2811, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20123 ms, replay 2220 ops.
14/07/06 09:20:01 INFO client.AsyncProcess: #13, table=usertable, attempt=13/35 failed 2306 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=888, waitTime=2811, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20098 ms, replay 2306 ops.
14/07/06 09:20:01 INFO client.AsyncProcess: #16, table=usertable, attempt=13/35 failed 2264 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=888, waitTime=2811, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20099 ms, replay 2264 ops.
14/07/06 09:20:01 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 failed 2241 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=888, waitTime=2811, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20084 ms, replay 2241 ops.
2014-07-06 09:20:09:924 142 sec: 879578 operations; 25500.45 current ops/sec; [INSERT AverageLatency(us)=665.51] 
2014-07-06 09:20:19:924 152 sec: 1096374 operations; 21679.6 current ops/sec; [UPDATE AverageLatency(us)=1058127.5] [INSERT AverageLatency(us)=111.52] [CLEANUP AverageLatency(us)=1059014] 
14/07/06 09:20:21 INFO client.AsyncProcess: #4, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014
14/07/06 09:20:21 INFO client.AsyncProcess: #12, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014
14/07/06 09:20:21 INFO client.AsyncProcess: #3, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014
14/07/06 09:20:21 INFO client.AsyncProcess: #7, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014
14/07/06 09:20:21 INFO client.AsyncProcess: #17, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014
14/07/06 09:20:22 INFO client.AsyncProcess: #2, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014
14/07/06 09:20:23 INFO client.AsyncProcess: #18, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014
14/07/06 09:20:23 INFO client.AsyncProcess: #9, table=usertable, attempt=14/35 failed 2190 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1130, waitTime=2190, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20100 ms, replay 2190 ops.
14/07/06 09:20:23 INFO client.AsyncProcess: #8, table=usertable, attempt=14/35 failed 2254 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1136, waitTime=2240, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20118 ms, replay 2254 ops.
14/07/06 09:20:23 INFO client.AsyncProcess: #6, table=usertable, attempt=14/35 failed 2304 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1136, waitTime=2240, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20115 ms, replay 2304 ops.
14/07/06 09:20:23 INFO client.AsyncProcess: #20, table=usertable, attempt=14/35 failed 2241 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1136, waitTime=2240, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20010 ms, replay 2241 ops.
14/07/06 09:20:23 INFO client.AsyncProcess: #16, table=usertable, attempt=14/35 failed 2264 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1136, waitTime=2240, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20097 ms, replay 2264 ops.
14/07/06 09:20:23 INFO client.AsyncProcess: #13, table=usertable, attempt=14/35 failed 2306 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1136, waitTime=2240, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20146 ms, replay 2306 ops.
14/07/06 09:20:23 INFO client.AsyncProcess: #14, table=usertable, attempt=14/35 failed 2220 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1136, waitTime=2240, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20178 ms, replay 2220 ops.
14/07/06 09:20:23 INFO client.AsyncProcess: #19, table=usertable, attempt=14/35 failed 2265 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1136, waitTime=2240, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20166 ms, replay 2265 ops.
14/07/06 09:20:23 INFO client.AsyncProcess: #5, table=usertable, attempt=14/35 failed 2292 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1136, waitTime=2240, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20079 ms, replay 2292 ops.
2014-07-06 09:20:29:925 162 sec: 1227862 operations; 13147.49 current ops/sec;  [INSERT AverageLatency(us)=7997.37]  
2014-07-06 09:20:39:926 172 sec: 1317086 operations; 8921.51 current ops/sec;  [INSERT AverageLatency(us)=1567.17]  
14/07/06 09:20:45 INFO client.AsyncProcess: #9, table=usertable, attempt=15/35 failed 2190 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1418, waitTime=2139, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20034 ms, replay 2190 ops.
14/07/06 09:20:46 INFO client.AsyncProcess: #5, table=usertable, attempt=15/35 failed 2292 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1422, waitTime=2395, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20130 ms, replay 2292 ops.
14/07/06 09:20:46 INFO client.AsyncProcess: #20, table=usertable, attempt=15/35 failed 2241 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1422, waitTime=2395, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20155 ms, replay 2241 ops.
14/07/06 09:20:46 INFO client.AsyncProcess: #16, table=usertable, attempt=15/35 failed 2264 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1422, waitTime=2395, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20137 ms, replay 2264 ops.
14/07/06 09:20:46 INFO client.AsyncProcess: #8, table=usertable, attempt=15/35 failed 2254 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1422, waitTime=2395, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20036 ms, replay 2254 ops.
14/07/06 09:20:46 INFO client.AsyncProcess: #13, table=usertable, attempt=15/35 failed 2306 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1422, waitTime=2395, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20090 ms, replay 2306 ops.
14/07/06 09:20:46 INFO client.AsyncProcess: #14, table=usertable, attempt=15/35 failed 2220 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1422, waitTime=2395, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20129 ms, replay 2220 ops.
14/07/06 09:20:46 INFO client.AsyncProcess: #6, table=usertable, attempt=15/35 failed 2304 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1422, waitTime=2395, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20174 ms, replay 2304 ops.
14/07/06 09:20:46 INFO client.AsyncProcess: #19, table=usertable, attempt=15/35 failed 2265 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1422, waitTime=2395, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20080 ms, replay 2265 ops.
2014-07-06 09:20:49:927 182 sec: 1581829 operations; 26471.65 current ops/sec;  [INSERT AverageLatency(us)=229.95]  
2014-07-06 09:20:59:928 192 sec: 1584758 operations; 292.87 current ops/sec;  [INSERT AverageLatency(us)=9.44]  
14/07/06 09:21:09 INFO client.AsyncProcess: #9, table=usertable, attempt=16/35 failed 2190 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1678, waitTime=3456, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20027 ms, replay 2190 ops.
14/07/06 09:21:09 INFO client.AsyncProcess: #14, table=usertable, attempt=16/35 failed 2220 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1678, waitTime=3456, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20186 ms, replay 2220 ops.
14/07/06 09:21:09 INFO client.AsyncProcess: #16, table=usertable, attempt=16/35 failed 2264 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1678, waitTime=3456, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20080 ms, replay 2264 ops.
14/07/06 09:21:09 INFO client.AsyncProcess: #8, table=usertable, attempt=16/35 failed 2254 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1678, waitTime=3456, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20098 ms, replay 2254 ops.
14/07/06 09:21:09 INFO client.AsyncProcess: #6, table=usertable, attempt=16/35 failed 2304 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1678, waitTime=3456, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20172 ms, replay 2304 ops.
14/07/06 09:21:09 INFO client.AsyncProcess: #5, table=usertable, attempt=16/35 failed 2292 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1678, waitTime=3456, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20063 ms, replay 2292 ops.
14/07/06 09:21:09 INFO client.AsyncProcess: #20, table=usertable, attempt=16/35 failed 2241 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1678, waitTime=3456, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20056 ms, replay 2241 ops.
14/07/06 09:21:09 INFO client.AsyncProcess: #13, table=usertable, attempt=16/35 failed 2306 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1678, waitTime=3456, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20065 ms, replay 2306 ops.
14/07/06 09:21:09 INFO client.AsyncProcess: #19, table=usertable, attempt=16/35 failed 2265 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1678, waitTime=3456, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014, retrying after 20109 ms, replay 2265 ops.
2014-07-06 09:21:09:929 202 sec: 1584758 operations; 0 current ops/sec;    
2014-07-06 09:21:19:930 212 sec: 1584758 operations; 0 current ops/sec;    
2014-07-06 09:21:29:931 222 sec: 1694992 operations; 11022.3 current ops/sec; [UPDATE AverageLatency(us)=1416192.5] [INSERT AverageLatency(us)=1167.87] [CLEANUP AverageLatency(us)=1416214] 
14/07/06 09:21:30 INFO client.AsyncProcess: #19, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014
14/07/06 09:21:30 INFO client.AsyncProcess: #20, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014
14/07/06 09:21:30 INFO client.AsyncProcess: #8, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014
14/07/06 09:21:30 INFO client.AsyncProcess: #5, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014
14/07/06 09:21:30 INFO client.AsyncProcess: #16, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014
14/07/06 09:21:30 INFO client.AsyncProcess: #13, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014
14/07/06 09:21:30 INFO client.AsyncProcess: #9, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014
14/07/06 09:21:30 INFO client.AsyncProcess: #14, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014
14/07/06 09:21:30 INFO client.AsyncProcess: #6, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:17:50 PDT 2014
14/07/06 09:21:38 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2268 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1907, waitTime=2593, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:47 PDT 2014, retrying after 10085 ms, replay 2268 ops.
14/07/06 09:21:38 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2264 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1907, waitTime=2593, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:46 PDT 2014, retrying after 10062 ms, replay 2264 ops.
14/07/06 09:21:38 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2228 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1907, waitTime=2593, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:47 PDT 2014, retrying after 10085 ms, replay 2228 ops.
14/07/06 09:21:38 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2223 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1907, waitTime=2593, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:46 PDT 2014, retrying after 10003 ms, replay 2223 ops.
14/07/06 09:21:38 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2271 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1907, waitTime=2593, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:46 PDT 2014, retrying after 10099 ms, replay 2271 ops.
14/07/06 09:21:38 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 2270 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1907, waitTime=2593, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:44 PDT 2014, retrying after 10070 ms, replay 2270 ops.
14/07/06 09:21:38 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2279 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1907, waitTime=2593, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:47 PDT 2014, retrying after 10077 ms, replay 2279 ops.
14/07/06 09:21:38 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2272 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1907, waitTime=2593, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:44 PDT 2014, retrying after 10074 ms, replay 2272 ops.
14/07/06 09:21:38 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2296 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1907, waitTime=2593, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:47 PDT 2014, retrying after 10079 ms, replay 2296 ops.
14/07/06 09:21:38 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2242 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1907, waitTime=2593, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:46 PDT 2014, retrying after 10055 ms, replay 2242 ops.
14/07/06 09:21:38 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2248 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1907, waitTime=2593, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:46 PDT 2014, retrying after 10048 ms, replay 2248 ops.
2014-07-06 09:21:39:983 232 sec: 1872251 operations; 17634.2 current ops/sec;  [INSERT AverageLatency(us)=11214.48]  
14/07/06 09:21:49 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:46 PDT 2014
2014-07-06 09:21:49:983 242 sec: 2072226 operations; 19997.5 current ops/sec;  [INSERT AverageLatency(us)=653.11]  
14/07/06 09:21:51 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:46 PDT 2014
14/07/06 09:21:52 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:46 PDT 2014
14/07/06 09:21:52 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 2296 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2066, waitTime=2490, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:47 PDT 2014, retrying after 10047 ms, replay 2296 ops.
14/07/06 09:21:52 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 2270 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2066, waitTime=2490, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:44 PDT 2014, retrying after 10061 ms, replay 2270 ops.
14/07/06 09:21:52 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 2279 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2066, waitTime=2490, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:47 PDT 2014, retrying after 10037 ms, replay 2279 ops.
14/07/06 09:21:52 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 2228 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2066, waitTime=2490, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:47 PDT 2014, retrying after 10029 ms, replay 2228 ops.
14/07/06 09:21:52 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 2268 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2066, waitTime=2490, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:47 PDT 2014, retrying after 10050 ms, replay 2268 ops.
14/07/06 09:21:52 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2272 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2066, waitTime=2490, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:44 PDT 2014, retrying after 10076 ms, replay 2272 ops.
14/07/06 09:21:52 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 2271 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2066, waitTime=2490, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:46 PDT 2014, retrying after 10019 ms, replay 2271 ops.
14/07/06 09:21:52 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2264 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2066, waitTime=2490, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:46 PDT 2014, retrying after 10061 ms, replay 2264 ops.
2014-07-06 09:21:59:984 252 sec: 2178680 operations; 10644.34 current ops/sec;  [INSERT AverageLatency(us)=777.04]  
14/07/06 09:22:04 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 failed 2279 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2273, waitTime=2104, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:47 PDT 2014, retrying after 20059 ms, replay 2279 ops.
14/07/06 09:22:04 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 failed 2270 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2273, waitTime=2104, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:44 PDT 2014, retrying after 20125 ms, replay 2270 ops.
14/07/06 09:22:04 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 2296 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2273, waitTime=2104, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:47 PDT 2014, retrying after 20158 ms, replay 2296 ops.
14/07/06 09:22:04 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 failed 2272 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2273, waitTime=2104, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:44 PDT 2014, retrying after 20164 ms, replay 2272 ops.
14/07/06 09:22:04 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 failed 2268 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2273, waitTime=2104, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:47 PDT 2014, retrying after 20135 ms, replay 2268 ops.
14/07/06 09:22:04 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 failed 2271 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2273, waitTime=2104, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:46 PDT 2014, retrying after 20082 ms, replay 2271 ops.
14/07/06 09:22:04 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 failed 2264 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2273, waitTime=2104, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:46 PDT 2014, retrying after 20085 ms, replay 2264 ops.
14/07/06 09:22:04 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 2228 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2273, waitTime=2104, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:47 PDT 2014, retrying after 20197 ms, replay 2228 ops.
2014-07-06 09:22:09:985 262 sec: 2178680 operations; 0 current ops/sec;    
2014-07-06 09:22:19:986 272 sec: 2342830 operations; 16413.36 current ops/sec;  [INSERT AverageLatency(us)=756.19]  
14/07/06 09:22:25 INFO client.AsyncProcess: #7, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:44 PDT 2014
14/07/06 09:22:25 INFO client.AsyncProcess: #12, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:46 PDT 2014
14/07/06 09:22:25 INFO client.AsyncProcess: #12, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:47 PDT 2014
14/07/06 09:22:25 INFO client.AsyncProcess: #17, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:46 PDT 2014
14/07/06 09:22:25 INFO client.AsyncProcess: #12, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:47 PDT 2014
14/07/06 09:22:25 INFO client.AsyncProcess: #18, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:44 PDT 2014
14/07/06 09:22:26 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:47 PDT 2014
14/07/06 09:22:26 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:20:47 PDT 2014
2014-07-06 09:22:29:986 282 sec: 2662368 operations; 31953.8 current ops/sec;  [INSERT AverageLatency(us)=1707.73]  
2014-07-06 09:22:39:987 292 sec: 2718720 operations; 5634.64 current ops/sec;  [INSERT AverageLatency(us)=872.85]  
14/07/06 09:22:42 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2256 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2729, waitTime=2652, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:49 PDT 2014, retrying after 10040 ms, replay 2256 ops.
14/07/06 09:22:42 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2291 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2729, waitTime=2652, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:51 PDT 2014, retrying after 10099 ms, replay 2291 ops.
14/07/06 09:22:42 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2238 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2729, waitTime=2652, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:50 PDT 2014, retrying after 10038 ms, replay 2238 ops.
14/07/06 09:22:42 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2220 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2729, waitTime=2652, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:51 PDT 2014, retrying after 10001 ms, replay 2220 ops.
14/07/06 09:22:42 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2229 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2729, waitTime=2652, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:50 PDT 2014, retrying after 10025 ms, replay 2229 ops.
14/07/06 09:22:42 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2273 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2729, waitTime=2652, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:50 PDT 2014, retrying after 10098 ms, replay 2273 ops.
14/07/06 09:22:42 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2235 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2729, waitTime=2652, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:49 PDT 2014, retrying after 10059 ms, replay 2235 ops.
14/07/06 09:22:42 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2269 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2729, waitTime=2652, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:51 PDT 2014, retrying after 10034 ms, replay 2269 ops.
14/07/06 09:22:42 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2250 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2729, waitTime=2652, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:50 PDT 2014, retrying after 10062 ms, replay 2250 ops.
14/07/06 09:22:42 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2273 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2729, waitTime=2652, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:49 PDT 2014, retrying after 10051 ms, replay 2273 ops.
14/07/06 09:22:42 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2228 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2729, waitTime=2652, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:51 PDT 2014, retrying after 10054 ms, replay 2228 ops.
2014-07-06 09:22:49:988 302 sec: 2746886 operations; 2816.32 current ops/sec;  [INSERT AverageLatency(us)=3695.94]  
14/07/06 09:22:54 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2220 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2847, waitTime=2384, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:51 PDT 2014, retrying after 10035 ms, replay 2220 ops.
14/07/06 09:22:54 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 2229 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2847, waitTime=2384, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:50 PDT 2014, retrying after 10064 ms, replay 2229 ops.
14/07/06 09:22:54 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 2256 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2847, waitTime=2384, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:49 PDT 2014, retrying after 10028 ms, replay 2256 ops.
14/07/06 09:22:54 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2238 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2847, waitTime=2384, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:50 PDT 2014, retrying after 10032 ms, replay 2238 ops.
14/07/06 09:22:54 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2269 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2847, waitTime=2384, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:51 PDT 2014, retrying after 10012 ms, replay 2269 ops.
14/07/06 09:22:55 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2273 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2856, waitTime=2397, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:49 PDT 2014, retrying after 10057 ms, replay 2273 ops.
14/07/06 09:22:55 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2273 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2856, waitTime=2397, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:50 PDT 2014, retrying after 10034 ms, replay 2273 ops.
14/07/06 09:22:55 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2291 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2856, waitTime=2397, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:51 PDT 2014, retrying after 10077 ms, replay 2291 ops.
14/07/06 09:22:55 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2235 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2856, waitTime=2397, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:49 PDT 2014, retrying after 10020 ms, replay 2235 ops.
14/07/06 09:22:55 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2250 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2856, waitTime=2397, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:50 PDT 2014, retrying after 10064 ms, replay 2250 ops.
14/07/06 09:22:55 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2228 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2856, waitTime=2397, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:51 PDT 2014, retrying after 10093 ms, replay 2228 ops.
2014-07-06 09:22:59:989 312 sec: 2883080 operations; 13619.4 current ops/sec;  [INSERT AverageLatency(us)=1357]  
14/07/06 09:23:06 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:51 PDT 2014
14/07/06 09:23:06 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:49 PDT 2014
14/07/06 09:23:06 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 failed 2220 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2997, waitTime=2103, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:51 PDT 2014, retrying after 20115 ms, replay 2220 ops.
14/07/06 09:23:06 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 failed 2229 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2997, waitTime=2103, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:50 PDT 2014, retrying after 20197 ms, replay 2229 ops.
14/07/06 09:23:06 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2238 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2997, waitTime=2103, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:50 PDT 2014, retrying after 20199 ms, replay 2238 ops.
14/07/06 09:23:07 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:49 PDT 2014
14/07/06 09:23:07 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 2291 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3000, waitTime=2836, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:51 PDT 2014, retrying after 20142 ms, replay 2291 ops.
14/07/06 09:23:07 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 2228 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3000, waitTime=2836, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:51 PDT 2014, retrying after 20169 ms, replay 2228 ops.
14/07/06 09:23:07 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 failed 2273 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3000, waitTime=2836, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:50 PDT 2014, retrying after 20088 ms, replay 2273 ops.
14/07/06 09:23:07 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 failed 2250 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3000, waitTime=2836, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:50 PDT 2014, retrying after 20124 ms, replay 2250 ops.
14/07/06 09:23:07 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 2235 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3000, waitTime=2836, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:49 PDT 2014, retrying after 20163 ms, replay 2235 ops.
2014-07-06 09:23:09:989 322 sec: 3066224 operations; 18312.57 current ops/sec;  [INSERT AverageLatency(us)=411.04]  
2014-07-06 09:23:19:990 332 sec: 3245785 operations; 17954.3 current ops/sec;  [INSERT AverageLatency(us)=658.21]  
14/07/06 09:23:28 INFO client.AsyncProcess: #16, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:51 PDT 2014
14/07/06 09:23:28 INFO client.AsyncProcess: #5, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:50 PDT 2014
14/07/06 09:23:28 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:50 PDT 2014
2014-07-06 09:23:29:991 342 sec: 3509874 operations; 26408.9 current ops/sec; [UPDATE AverageLatency(us)=3280872] [INSERT AverageLatency(us)=1072.82] [CLEANUP AverageLatency(us)=3280894] 
14/07/06 09:23:30 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 failed 2291 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3273, waitTime=2826, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:51 PDT 2014, retrying after 20152 ms, replay 2291 ops.
14/07/06 09:23:30 INFO client.AsyncProcess: #16, table=usertable, attempt=13/35 failed 2250 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3273, waitTime=2826, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:50 PDT 2014, retrying after 20100 ms, replay 2250 ops.
14/07/06 09:23:30 INFO client.AsyncProcess: #13, table=usertable, attempt=13/35 failed 2273 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3273, waitTime=2826, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:50 PDT 2014, retrying after 20040 ms, replay 2273 ops.
14/07/06 09:23:30 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 failed 2235 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3273, waitTime=2826, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:49 PDT 2014, retrying after 20007 ms, replay 2235 ops.
14/07/06 09:23:30 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 failed 2228 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3273, waitTime=2826, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:51 PDT 2014, retrying after 20107 ms, replay 2228 ops.
2014-07-06 09:23:39:992 352 sec: 3594402 operations; 8451.95 current ops/sec; [UPDATE AverageLatency(us)=3459999] [INSERT AverageLatency(us)=303.11] [CLEANUP AverageLatency(us)=3460026] 
2014-07-06 09:23:49:992 362 sec: 3594402 operations; 0 current ops/sec;    
14/07/06 09:23:53 INFO client.AsyncProcess: #9, table=usertable, attempt=14/35 failed 2291 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3531, waitTime=2369, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:51 PDT 2014, retrying after 20198 ms, replay 2291 ops.
14/07/06 09:23:53 INFO client.AsyncProcess: #20, table=usertable, attempt=14/35 failed 2228 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3531, waitTime=2369, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:51 PDT 2014, retrying after 20071 ms, replay 2228 ops.
14/07/06 09:23:53 INFO client.AsyncProcess: #13, table=usertable, attempt=14/35 failed 2273 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3531, waitTime=2369, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:50 PDT 2014, retrying after 20078 ms, replay 2273 ops.
14/07/06 09:23:53 INFO client.AsyncProcess: #16, table=usertable, attempt=14/35 failed 2250 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3531, waitTime=2369, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:50 PDT 2014, retrying after 20068 ms, replay 2250 ops.
14/07/06 09:23:53 INFO client.AsyncProcess: #9, table=usertable, attempt=14/35 failed 2235 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3531, waitTime=2369, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:49 PDT 2014, retrying after 20131 ms, replay 2235 ops.
2014-07-06 09:23:59:993 372 sec: 3655450 operations; 6104.19 current ops/sec;  [INSERT AverageLatency(us)=950.59]  
2014-07-06 09:24:09:994 382 sec: 3983034 operations; 32755.12 current ops/sec; [UPDATE AverageLatency(us)=889047] [INSERT AverageLatency(us)=930.16] [CLEANUP AverageLatency(us)=889071.67] 
14/07/06 09:24:15 INFO client.AsyncProcess: #9, table=usertable, attempt=15/35 failed 2235 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3803, waitTime=2496, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:49 PDT 2014, retrying after 20039 ms, replay 2235 ops.
14/07/06 09:24:15 INFO client.AsyncProcess: #9, table=usertable, attempt=15/35 failed 2291 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3803, waitTime=2496, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:51 PDT 2014, retrying after 20182 ms, replay 2291 ops.
14/07/06 09:24:15 INFO client.AsyncProcess: #13, table=usertable, attempt=15/35 failed 2273 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3803, waitTime=2496, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:50 PDT 2014, retrying after 20048 ms, replay 2273 ops.
14/07/06 09:24:15 INFO client.AsyncProcess: #16, table=usertable, attempt=15/35 failed 2250 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3803, waitTime=2496, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:50 PDT 2014, retrying after 20130 ms, replay 2250 ops.
14/07/06 09:24:15 INFO client.AsyncProcess: #20, table=usertable, attempt=15/35 failed 2228 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3803, waitTime=2496, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:51 PDT 2014, retrying after 20094 ms, replay 2228 ops.
2014-07-06 09:24:19:995 392 sec: 4168183 operations; 18513.05 current ops/sec; [UPDATE AverageLatency(us)=2466316.5] [INSERT AverageLatency(us)=275.51] [CLEANUP AverageLatency(us)=2466343.5] 
2014-07-06 09:24:29:996 402 sec: 4281756 operations; 11356.16 current ops/sec; [UPDATE AverageLatency(us)=808898.8] [INSERT AverageLatency(us)=138.59] [CLEANUP AverageLatency(us)=808923] 
14/07/06 09:24:36 INFO client.AsyncProcess: #9, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:49 PDT 2014
14/07/06 09:24:36 INFO client.AsyncProcess: #13, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:50 PDT 2014
14/07/06 09:24:36 INFO client.AsyncProcess: #20, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:51 PDT 2014
14/07/06 09:24:36 INFO client.AsyncProcess: #16, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:50 PDT 2014
14/07/06 09:24:36 INFO client.AsyncProcess: #9, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404663109155, tracking started Sun Jul 06 09:21:51 PDT 2014
2014-07-06 09:24:39:997 412 sec: 4405308 operations; 12353.96 current ops/sec;  [INSERT AverageLatency(us)=5419.73]  
2014-07-06 09:24:49:997 422 sec: 4718484 operations; 31317.6 current ops/sec;  [INSERT AverageLatency(us)=118.62]  
2014-07-06 09:24:59:998 432 sec: 4998887 operations; 28037.5 current ops/sec; [UPDATE AverageLatency(us)=558525.67] [INSERT AverageLatency(us)=105.42] [CLEANUP AverageLatency(us)=558550.33] 
2014-07-06 09:25:00:501 432 sec: 5000000 operations; 2212.72 current ops/sec; [UPDATE AverageLatency(us)=345857] [INSERT AverageLatency(us)=199.41] [CLEANUP AverageLatency(us)=345877] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404663901
1404663901
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo 'random read...'
random read...
+ echo 'starting time: '
starting time: 
++ date +%s
+ echo 1404663911
1404663911
++ echo /home/hadoop/git/physical_design/caseresult/case20/random_read_1.dat
+ ./random_read 5000000 20 /home/hadoop/git/physical_design/caseresult/case20/random_read_1.dat
Loading workload...
Starting test.
2014-07-06 09:25:15:182 0 sec: 0 operations; 
14/07/06 09:25:16 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/06 09:25:16 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/06 09:25:16 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/06 09:25:16 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/06 09:25:16 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/06 09:25:16 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/06 09:25:16 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/06 09:25:16 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/06 09:25:16 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/06 09:25:16 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/06 09:25:16 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/06 09:25:16 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/06 09:25:16 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/06 09:25:16 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/06 09:25:16 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/06 09:25:16 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x4ef888ea, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/06 09:25:16 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x4ef888ea connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/06 09:25:16 INFO zookeeper.ClientCnxn: Opening socket connection to server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/06 09:25:16 INFO zookeeper.ClientCnxn: Socket connection established to sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, initiating session
14/07/06 09:25:16 INFO zookeeper.ClientCnxn: Session establishment complete on server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, sessionid = 0x470c77fd370000, negotiated timeout = 90000
2014-07-06 09:25:25:202 10 sec: 42456 operations; 4236.7 current ops/sec; [READ AverageLatency(us)=4617.76] 
2014-07-06 09:25:35:208 20 sec: 164747 operations; 12221.77 current ops/sec; [READ AverageLatency(us)=1633.8] 
2014-07-06 09:25:45:209 30 sec: 297283 operations; 13252.27 current ops/sec; [READ AverageLatency(us)=1503.57] 
2014-07-06 09:25:55:211 40 sec: 439227 operations; 14191.56 current ops/sec; [READ AverageLatency(us)=1403.59] 
2014-07-06 09:26:05:212 50 sec: 590010 operations; 15078.3 current ops/sec; [READ AverageLatency(us)=1318.65] 
2014-07-06 09:26:15:212 60 sec: 740972 operations; 15094.69 current ops/sec; [READ AverageLatency(us)=1321.28] 
2014-07-06 09:26:25:213 70 sec: 888718 operations; 14773.12 current ops/sec; [READ AverageLatency(us)=1347.92] 
2014-07-06 09:26:35:214 80 sec: 1031727 operations; 14300.9 current ops/sec; [READ AverageLatency(us)=1392.9] 
2014-07-06 09:26:45:214 90 sec: 1198966 operations; 16722.23 current ops/sec; [READ AverageLatency(us)=1190.36] 
2014-07-06 09:26:55:215 100 sec: 1380406 operations; 18142.19 current ops/sec; [READ AverageLatency(us)=1096.73] 
2014-07-06 09:27:05:216 110 sec: 1562440 operations; 18203.4 current ops/sec; [READ AverageLatency(us)=1093.22] 
2014-07-06 09:27:15:216 120 sec: 1745590 operations; 18313.17 current ops/sec; [READ AverageLatency(us)=1086.6] 
2014-07-06 09:27:25:217 130 sec: 1936628 operations; 19101.89 current ops/sec; [READ AverageLatency(us)=1041.22] 
2014-07-06 09:27:35:218 140 sec: 2126271 operations; 18962.4 current ops/sec; [READ AverageLatency(us)=1050.25] 
2014-07-06 09:27:45:219 150 sec: 2316136 operations; 18984.6 current ops/sec; [READ AverageLatency(us)=1048.32] 
2014-07-06 09:27:55:220 160 sec: 2504338 operations; 18818.32 current ops/sec; [READ AverageLatency(us)=1057.73] 
2014-07-06 09:28:05:221 170 sec: 2695085 operations; 19074.7 current ops/sec; [READ AverageLatency(us)=1043.51] 
2014-07-06 09:28:15:221 180 sec: 2885708 operations; 19060.39 current ops/sec; [READ AverageLatency(us)=1044.13] 
2014-07-06 09:28:25:222 190 sec: 3072674 operations; 18694.73 current ops/sec; [READ AverageLatency(us)=1060.94] 
2014-07-06 09:28:35:222 200 sec: 3246337 operations; 17366.3 current ops/sec; [READ AverageLatency(us)=1149.79] 
2014-07-06 09:28:45:223 210 sec: 3421878 operations; 17552.34 current ops/sec; [READ AverageLatency(us)=1133.83] 
2014-07-06 09:28:55:223 220 sec: 3589316 operations; 16743.8 current ops/sec; [READ AverageLatency(us)=1188.74] 
2014-07-06 09:29:05:224 230 sec: 3771324 operations; 18198.98 current ops/sec; [READ AverageLatency(us)=1093.38] 
2014-07-06 09:29:15:225 240 sec: 3958205 operations; 18686.23 current ops/sec; [READ AverageLatency(us)=1065.08] 
2014-07-06 09:29:25:226 250 sec: 4141355 operations; 18315 current ops/sec; [READ AverageLatency(us)=1087.06] 
2014-07-06 09:29:35:226 260 sec: 4327900 operations; 18652.63 current ops/sec; [READ AverageLatency(us)=1067.15] 
2014-07-06 09:29:45:227 270 sec: 4496741 operations; 16882.41 current ops/sec; [READ AverageLatency(us)=1179.52] 
2014-07-06 09:29:55:227 280 sec: 4674291 operations; 17755 current ops/sec; [READ AverageLatency(us)=1121.31] 
2014-07-06 09:30:05:228 290 sec: 4862906 operations; 18859.61 current ops/sec; [READ AverageLatency(us)=1053.14] 
2014-07-06 09:30:12:838 297 sec: 5000000 operations; 18014.98 current ops/sec; [UPDATE AverageLatency(us)=13.7] [READ AverageLatency(us)=1044.12] [CLEANUP AverageLatency(us)=228.95] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404664213
1404664213
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo workloada...
workloada...
+ echo 'start time: '
start time: 
++ date +%s
+ echo 1404664223
1404664223
++ echo /home/hadoop/git/physical_design/caseresult/case20/workloada_1.dat
+ ./workloada 5000000 20 /home/hadoop/git/physical_design/caseresult/case20/workloada_1.dat
Loading workload...
Starting test.
2014-07-06 09:30:24:087 0 sec: 0 operations; 
14/07/06 09:30:24 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/06 09:30:24 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/06 09:30:24 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/06 09:30:24 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/06 09:30:24 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/06 09:30:24 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/06 09:30:24 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/06 09:30:24 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/06 09:30:24 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/06 09:30:24 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/06 09:30:24 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/06 09:30:24 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/06 09:30:24 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/06 09:30:24 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/06 09:30:24 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/06 09:30:24 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0xc2c915f, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/06 09:30:24 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0xc2c915f connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/06 09:30:24 INFO zookeeper.ClientCnxn: Opening socket connection to server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/06 09:30:24 INFO zookeeper.ClientCnxn: Socket connection established to sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, initiating session
14/07/06 09:30:24 INFO zookeeper.ClientCnxn: Session establishment complete on server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, sessionid = 0x470c77fd370001, negotiated timeout = 90000
2014-07-06 09:30:34:088 10 sec: 36827 operations; 3682.33 current ops/sec; [INSERT AverageLatency(us)=75.37] [READ AverageLatency(us)=3736.85] 
2014-07-06 09:30:44:090 20 sec: 142559 operations; 10571.09 current ops/sec; [INSERT AverageLatency(us)=17.6] [READ AverageLatency(us)=1970.91] 
2014-07-06 09:30:54:091 30 sec: 260703 operations; 11813.22 current ops/sec; [INSERT AverageLatency(us)=15.01] [READ AverageLatency(us)=1862.56] 
2014-07-06 09:31:04:092 40 sec: 391381 operations; 13066.49 current ops/sec; [INSERT AverageLatency(us)=15.65] [READ AverageLatency(us)=1681] 
2014-07-06 09:31:14:093 50 sec: 518310 operations; 12691.63 current ops/sec; [INSERT AverageLatency(us)=16.35] [READ AverageLatency(us)=1731.28] 
2014-07-06 09:31:24:094 60 sec: 644548 operations; 12622.54 current ops/sec; [INSERT AverageLatency(us)=13.63] [READ AverageLatency(us)=1744.23] 
2014-07-06 09:31:34:095 70 sec: 775415 operations; 13085.39 current ops/sec; [INSERT AverageLatency(us)=17.26] [READ AverageLatency(us)=1684.61] 
2014-07-06 09:31:44:159 80 sec: 892821 operations; 11667.1 current ops/sec; [INSERT AverageLatency(us)=25.8] [READ AverageLatency(us)=1888.88] 
2014-07-06 09:31:54:171 90 sec: 970406 operations; 7748.43 current ops/sec; [INSERT AverageLatency(us)=250.61] [READ AverageLatency(us)=2835.19] 
2014-07-06 09:32:04:172 100 sec: 1083700 operations; 11328.27 current ops/sec; [INSERT AverageLatency(us)=19.66] [READ AverageLatency(us)=1945.7] 
2014-07-06 09:32:14:173 110 sec: 1189668 operations; 10595.74 current ops/sec; [INSERT AverageLatency(us)=21.28] [READ AverageLatency(us)=2073.31] 
2014-07-06 09:32:24:174 120 sec: 1308197 operations; 11851.71 current ops/sec; [INSERT AverageLatency(us)=18.68] [READ AverageLatency(us)=1876.41] 
2014-07-06 09:32:34:174 130 sec: 1442051 operations; 13385.4 current ops/sec; [INSERT AverageLatency(us)=17.97] [READ AverageLatency(us)=1648.24] 
2014-07-06 09:32:44:176 140 sec: 1580752 operations; 13867.33 current ops/sec; [INSERT AverageLatency(us)=14.47] [READ AverageLatency(us)=1592] 
2014-07-06 09:32:54:177 150 sec: 1717334 operations; 13658.2 current ops/sec; [INSERT AverageLatency(us)=21.46] [READ AverageLatency(us)=1614.63] 
2014-07-06 09:33:04:177 160 sec: 1866764 operations; 14941.51 current ops/sec; [INSERT AverageLatency(us)=20.94] [READ AverageLatency(us)=1464.6] 
2014-07-06 09:33:14:178 170 sec: 1993842 operations; 12706.53 current ops/sec; [INSERT AverageLatency(us)=28.91] [READ AverageLatency(us)=1752.17] 
2014-07-06 09:33:24:179 180 sec: 2149745 operations; 15588.74 current ops/sec; [INSERT AverageLatency(us)=19.08] [READ AverageLatency(us)=1412.73] 
2014-07-06 09:33:34:180 190 sec: 2316363 operations; 16660.13 current ops/sec; [INSERT AverageLatency(us)=20.11] [READ AverageLatency(us)=1324.47] 
2014-07-06 09:33:44:180 200 sec: 2494378 operations; 17801.5 current ops/sec; [INSERT AverageLatency(us)=17.82] [READ AverageLatency(us)=1239.62] 
2014-07-06 09:33:54:181 210 sec: 2668030 operations; 17363.46 current ops/sec; [INSERT AverageLatency(us)=18.86] [READ AverageLatency(us)=1269.51] 
2014-07-06 09:34:04:182 220 sec: 2811718 operations; 14367.36 current ops/sec; [INSERT AverageLatency(us)=24.95] [READ AverageLatency(us)=1533.01] 
2014-07-06 09:34:14:183 230 sec: 2923606 operations; 11188.8 current ops/sec; [INSERT AverageLatency(us)=29.81] [READ AverageLatency(us)=1978.78] 
2014-07-06 09:34:24:183 240 sec: 3079562 operations; 15594.04 current ops/sec; [INSERT AverageLatency(us)=19.56] [READ AverageLatency(us)=1415.06] 
2014-07-06 09:34:34:184 250 sec: 3251389 operations; 17180.98 current ops/sec; [INSERT AverageLatency(us)=25.2] [READ AverageLatency(us)=1281.61] 
2014-07-06 09:34:44:185 260 sec: 3430682 operations; 17927.51 current ops/sec; [INSERT AverageLatency(us)=23.15] [READ AverageLatency(us)=1228.54] 
2014-07-06 09:34:54:186 270 sec: 3608567 operations; 17786.72 current ops/sec; [INSERT AverageLatency(us)=17.74] [READ AverageLatency(us)=1241.67] 
2014-07-06 09:35:04:187 280 sec: 3759177 operations; 15059.49 current ops/sec; [INSERT AverageLatency(us)=21.19] [READ AverageLatency(us)=1464.85] 
2014-07-06 09:35:14:187 290 sec: 3910660 operations; 15148.3 current ops/sec; [INSERT AverageLatency(us)=27.09] [READ AverageLatency(us)=1456.07] 
2014-07-06 09:35:24:188 300 sec: 4088113 operations; 17743.53 current ops/sec; [INSERT AverageLatency(us)=16.74] [READ AverageLatency(us)=1241.56] 
2014-07-06 09:35:34:189 310 sec: 4276293 operations; 18816.12 current ops/sec; [INSERT AverageLatency(us)=17.55] [READ AverageLatency(us)=1175.84] 
2014-07-06 09:35:44:190 320 sec: 4467294 operations; 19098.19 current ops/sec; [INSERT AverageLatency(us)=12.65] [READ AverageLatency(us)=1154.63] 
2014-07-06 09:35:54:190 330 sec: 4651280 operations; 18398.6 current ops/sec; [INSERT AverageLatency(us)=14.97] [READ AverageLatency(us)=1197.99] 
2014-07-06 09:36:04:191 340 sec: 4744836 operations; 9354.66 current ops/sec; [INSERT AverageLatency(us)=30.88] [READ AverageLatency(us)=2365.23] 
2014-07-06 09:36:14:192 350 sec: 4873175 operations; 12832.62 current ops/sec; [INSERT AverageLatency(us)=17.25] [READ AverageLatency(us)=1723.19] 
2014-07-06 09:36:23:717 359 sec: 5000000 operations; 13314.96 current ops/sec; [UPDATE AverageLatency(us)=157818.45] [INSERT AverageLatency(us)=14.96] [READ AverageLatency(us)=1348.29] [CLEANUP AverageLatency(us)=157991.05] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404664584
1404664584
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo workloadb...
workloadb...
+ echo 'start time: '
start time: 
++ date +%s
+ echo 1404664594
1404664594
++ echo /home/hadoop/git/physical_design/caseresult/case20/workloadb_1.dat
+ ./workloadb 5000000 20 /home/hadoop/git/physical_design/caseresult/case20/workloadb_1.dat
Loading workload...
Starting test.
2014-07-06 09:36:35:103 0 sec: 0 operations; 
14/07/06 09:36:35 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/06 09:36:35 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/06 09:36:35 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/06 09:36:35 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/06 09:36:35 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/06 09:36:35 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/06 09:36:35 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/06 09:36:35 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/06 09:36:35 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/06 09:36:35 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/06 09:36:35 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/06 09:36:35 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/06 09:36:35 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/06 09:36:35 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/06 09:36:35 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/06 09:36:35 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x30ea3e3c, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/06 09:36:35 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x30ea3e3c connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/06 09:36:35 INFO zookeeper.ClientCnxn: Opening socket connection to server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/06 09:36:35 INFO zookeeper.ClientCnxn: Socket connection established to sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, initiating session
14/07/06 09:36:35 INFO zookeeper.ClientCnxn: Session establishment complete on server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, sessionid = 0x470c77fd370002, negotiated timeout = 90000
2014-07-06 09:36:45:105 10 sec: 45042 operations; 4502.4 current ops/sec; [INSERT AverageLatency(us)=546.75] [READ AverageLatency(us)=3786.55] 
2014-07-06 09:36:55:111 20 sec: 188745 operations; 14361.68 current ops/sec; [INSERT AverageLatency(us)=87.65] [READ AverageLatency(us)=2439.06] 
2014-07-06 09:37:05:112 30 sec: 286523 operations; 9776.82 current ops/sec; [INSERT AverageLatency(us)=59.81] [READ AverageLatency(us)=3964.73] 
2014-07-06 09:37:15:113 40 sec: 452199 operations; 16565.94 current ops/sec; [INSERT AverageLatency(us)=17.9] [READ AverageLatency(us)=2368.23] 
2014-07-06 09:37:25:114 50 sec: 613951 operations; 16173.58 current ops/sec; [INSERT AverageLatency(us)=32.07] [READ AverageLatency(us)=2417.6] 
2014-07-06 09:37:35:115 60 sec: 801703 operations; 18773.32 current ops/sec; [INSERT AverageLatency(us)=19.29] [READ AverageLatency(us)=2091.31] 
2014-07-06 09:37:45:117 70 sec: 972104 operations; 17038.4 current ops/sec; [INSERT AverageLatency(us)=28.7] [READ AverageLatency(us)=2296.93] 
2014-07-06 09:37:55:117 80 sec: 1137504 operations; 16538.35 current ops/sec; [INSERT AverageLatency(us)=19] [READ AverageLatency(us)=2382.96] 
2014-07-06 09:38:05:119 90 sec: 1317922 operations; 18038.19 current ops/sec; [INSERT AverageLatency(us)=21.01] [READ AverageLatency(us)=2182.07] 
2014-07-06 09:38:15:120 100 sec: 1496523 operations; 17860.1 current ops/sec; [INSERT AverageLatency(us)=30.56] [READ AverageLatency(us)=2201.2] 
2014-07-06 09:38:25:120 110 sec: 1669767 operations; 17322.67 current ops/sec; [INSERT AverageLatency(us)=35.26] [READ AverageLatency(us)=2264.29] 
2014-07-06 09:38:35:121 120 sec: 1771687 operations; 10190.98 current ops/sec; [INSERT AverageLatency(us)=22.08] [READ AverageLatency(us)=3868.06] 
2014-07-06 09:38:45:122 130 sec: 1895694 operations; 12400.7 current ops/sec; [INSERT AverageLatency(us)=16.04] [READ AverageLatency(us)=3150.9] 
2014-07-06 09:38:55:122 140 sec: 2050781 operations; 15507.15 current ops/sec; [INSERT AverageLatency(us)=21.51] [READ AverageLatency(us)=2577.88] 
2014-07-06 09:39:05:123 150 sec: 2150337 operations; 9954.6 current ops/sec; [INSERT AverageLatency(us)=26.44] [READ AverageLatency(us)=3987.93] 
2014-07-06 09:39:15:124 160 sec: 2233128 operations; 8278.27 current ops/sec; [INSERT AverageLatency(us)=17.3] [READ AverageLatency(us)=4140.27] 
2014-07-06 09:39:25:124 170 sec: 2246609 operations; 1348.1 current ops/sec; [INSERT AverageLatency(us)=26.12] [READ AverageLatency(us)=33619.12] 
2014-07-06 09:39:35:133 180 sec: 2312038 operations; 6537.02 current ops/sec; [INSERT AverageLatency(us)=36.64] [READ AverageLatency(us)=6058.79] 
2014-07-06 09:39:45:134 190 sec: 2426619 operations; 11456.95 current ops/sec; [INSERT AverageLatency(us)=22.04] [READ AverageLatency(us)=3460.9] 
2014-07-06 09:39:55:135 200 sec: 2492966 operations; 6634.04 current ops/sec; [INSERT AverageLatency(us)=30.06] [READ AverageLatency(us)=5991.17] 
2014-07-06 09:40:05:135 210 sec: 2587827 operations; 9486.1 current ops/sec; [INSERT AverageLatency(us)=16.19] [READ AverageLatency(us)=4196.75] 
2014-07-06 09:40:15:178 220 sec: 2647069 operations; 5898.84 current ops/sec; [INSERT AverageLatency(us)=20.54] [READ AverageLatency(us)=6409.28] 
2014-07-06 09:40:25:179 230 sec: 2647069 operations; 0 current ops/sec;   
2014-07-06 09:40:35:180 240 sec: 2647069 operations; 0 current ops/sec;   
2014-07-06 09:40:45:180 250 sec: 2647069 operations; 0 current ops/sec;   
2014-07-06 09:40:55:181 260 sec: 2647069 operations; 0 current ops/sec;   
2014-07-06 09:41:05:182 270 sec: 2647069 operations; 0 current ops/sec;   
2014-07-06 09:41:15:183 280 sec: 2647069 operations; 0 current ops/sec;   
2014-07-06 09:41:25:184 290 sec: 2647069 operations; 0 current ops/sec;   
2014-07-06 09:41:35:184 300 sec: 2647069 operations; 0 current ops/sec;   
2014-07-06 09:41:45:185 310 sec: 2647069 operations; 0 current ops/sec;   
2014-07-06 09:41:55:213 320 sec: 2656283 operations; 918.83 current ops/sec; [INSERT AverageLatency(us)=141.53] [READ AverageLatency(us)=433255.91] 
2014-07-06 09:42:05:274 330 sec: 2690476 operations; 3398.57 current ops/sec; [INSERT AverageLatency(us)=50.38] [READ AverageLatency(us)=11783.6] 
2014-07-06 09:42:15:275 340 sec: 2733380 operations; 4289.97 current ops/sec; [INSERT AverageLatency(us)=23.11] [READ AverageLatency(us)=9186.92] 
2014-07-06 09:42:25:276 350 sec: 2779223 operations; 4583.84 current ops/sec; [INSERT AverageLatency(us)=15.3] [READ AverageLatency(us)=8435.78] 
2014-07-06 09:42:35:299 360 sec: 2814449 operations; 3514.87 current ops/sec; [INSERT AverageLatency(us)=41.11] [READ AverageLatency(us)=11822.52] 
2014-07-06 09:42:45:311 370 sec: 2851937 operations; 3743.93 current ops/sec; [INSERT AverageLatency(us)=22.92] [READ AverageLatency(us)=10787.35] 
2014-07-06 09:42:55:312 380 sec: 2901997 operations; 5006 current ops/sec; [INSERT AverageLatency(us)=18.88] [READ AverageLatency(us)=7930.24] 
2014-07-06 09:43:05:314 390 sec: 2943747 operations; 4173.75 current ops/sec; [INSERT AverageLatency(us)=15.57] [READ AverageLatency(us)=9534] 
2014-07-06 09:43:15:315 400 sec: 2990243 operations; 4649.14 current ops/sec; [INSERT AverageLatency(us)=19.64] [READ AverageLatency(us)=8589.61] 
2014-07-06 09:43:25:315 410 sec: 3033387 operations; 4314.4 current ops/sec; [INSERT AverageLatency(us)=21.2] [READ AverageLatency(us)=9248.43] 
2014-07-06 09:43:35:316 420 sec: 3082392 operations; 4900.01 current ops/sec; [INSERT AverageLatency(us)=16.35] [READ AverageLatency(us)=8146.49] 
2014-07-06 09:43:45:317 430 sec: 3132409 operations; 5001.2 current ops/sec; [INSERT AverageLatency(us)=27.05] [READ AverageLatency(us)=7953.89] 
2014-07-06 09:43:55:318 440 sec: 3189714 operations; 5729.93 current ops/sec; [INSERT AverageLatency(us)=21.58] [READ AverageLatency(us)=6929.36] 
2014-07-06 09:44:05:318 450 sec: 3236909 operations; 4719.5 current ops/sec; [INSERT AverageLatency(us)=19.68] [READ AverageLatency(us)=8361.02] 
2014-07-06 09:44:15:319 460 sec: 3302713 operations; 6579.74 current ops/sec; [INSERT AverageLatency(us)=14.4] [READ AverageLatency(us)=6134.98] 
2014-07-06 09:44:25:320 470 sec: 3365036 operations; 6231.68 current ops/sec; [INSERT AverageLatency(us)=16.59] [READ AverageLatency(us)=6435.19] 
2014-07-06 09:44:35:321 480 sec: 3413026 operations; 4798.52 current ops/sec; [INSERT AverageLatency(us)=23.17] [READ AverageLatency(us)=8273.4] 
2014-07-06 09:44:45:322 490 sec: 3483786 operations; 7075.29 current ops/sec; [INSERT AverageLatency(us)=15.56] [READ AverageLatency(us)=5690.19] 
2014-07-06 09:44:55:323 500 sec: 3551585 operations; 6779.22 current ops/sec; [INSERT AverageLatency(us)=21.12] [READ AverageLatency(us)=5801.58] 
2014-07-06 09:45:05:324 510 sec: 3605364 operations; 5377.36 current ops/sec; [INSERT AverageLatency(us)=31.21] [READ AverageLatency(us)=7424.3] 
2014-07-06 09:45:15:325 520 sec: 3668962 operations; 6359.16 current ops/sec; [INSERT AverageLatency(us)=21.56] [READ AverageLatency(us)=6280.53] 
2014-07-06 09:45:25:325 530 sec: 3740289 operations; 7132.7 current ops/sec; [INSERT AverageLatency(us)=16.51] [READ AverageLatency(us)=5557.26] 
2014-07-06 09:45:35:326 540 sec: 3783974 operations; 4368.06 current ops/sec; [INSERT AverageLatency(us)=19.2] [READ AverageLatency(us)=9016.6] 
2014-07-06 09:45:45:327 550 sec: 3844006 operations; 6002.6 current ops/sec; [INSERT AverageLatency(us)=26.51] [READ AverageLatency(us)=6678.8] 
2014-07-06 09:45:55:328 560 sec: 3912462 operations; 6844.92 current ops/sec; [INSERT AverageLatency(us)=16.49] [READ AverageLatency(us)=5799.71] 
2014-07-06 09:46:05:329 570 sec: 3965296 operations; 5282.87 current ops/sec; [INSERT AverageLatency(us)=27] [READ AverageLatency(us)=7504.44] 
2014-07-06 09:46:15:330 580 sec: 4033483 operations; 6818.7 current ops/sec; [INSERT AverageLatency(us)=17.42] [READ AverageLatency(us)=5852.7] 
2014-07-06 09:46:25:330 590 sec: 4106272 operations; 7278.17 current ops/sec; [INSERT AverageLatency(us)=19.11] [READ AverageLatency(us)=5484.25] 
2014-07-06 09:46:35:332 600 sec: 4161035 operations; 5475.75 current ops/sec; [INSERT AverageLatency(us)=30.69] [READ AverageLatency(us)=7137.53] 
2014-07-06 09:46:45:332 610 sec: 4230556 operations; 6951.4 current ops/sec; [INSERT AverageLatency(us)=15.28] [READ AverageLatency(us)=5829.11] 
2014-07-06 09:46:55:333 620 sec: 4298702 operations; 6813.92 current ops/sec; [INSERT AverageLatency(us)=19.96] [READ AverageLatency(us)=5725.87] 
2014-07-06 09:47:05:334 630 sec: 4347801 operations; 4909.41 current ops/sec; [INSERT AverageLatency(us)=20.91] [READ AverageLatency(us)=8206.15] 
2014-07-06 09:47:15:335 640 sec: 4403318 operations; 5551.14 current ops/sec; [INSERT AverageLatency(us)=15.87] [READ AverageLatency(us)=7173.99] 
2014-07-06 09:47:25:342 650 sec: 4465657 operations; 6230.78 current ops/sec; [INSERT AverageLatency(us)=20.07] [READ AverageLatency(us)=6407.15] 
2014-07-06 09:47:35:351 660 sec: 4511844 operations; 4613.63 current ops/sec; [INSERT AverageLatency(us)=19.44] [READ AverageLatency(us)=8688.45] 
2014-07-06 09:47:45:352 670 sec: 4565531 operations; 5368.16 current ops/sec; [INSERT AverageLatency(us)=21.82] [READ AverageLatency(us)=7443.99] 
2014-07-06 09:47:55:353 680 sec: 4621289 operations; 5575.24 current ops/sec; [INSERT AverageLatency(us)=15.03] [READ AverageLatency(us)=7095.31] 
2014-07-06 09:48:05:354 690 sec: 4674924 operations; 5363.5 current ops/sec; [INSERT AverageLatency(us)=16.35] [READ AverageLatency(us)=7413.09] 
2014-07-06 09:48:15:354 700 sec: 4722530 operations; 4760.12 current ops/sec; [INSERT AverageLatency(us)=27.23] [READ AverageLatency(us)=8414.17] 
2014-07-06 09:48:25:355 710 sec: 4777948 operations; 5541.25 current ops/sec; [INSERT AverageLatency(us)=14.79] [READ AverageLatency(us)=7205.04] 
2014-07-06 09:48:35:356 720 sec: 4834830 operations; 5687.63 current ops/sec; [INSERT AverageLatency(us)=14.55] [READ AverageLatency(us)=6847.8] 
2014-07-06 09:48:45:357 730 sec: 4882802 operations; 4796.72 current ops/sec; [INSERT AverageLatency(us)=23.28] [READ AverageLatency(us)=8413.75] 
2014-07-06 09:48:55:358 740 sec: 4927705 operations; 4490.3 current ops/sec; [INSERT AverageLatency(us)=19.29] [READ AverageLatency(us)=8887.59] 
2014-07-06 09:49:05:358 750 sec: 4982950 operations; 5523.95 current ops/sec; [UPDATE AverageLatency(us)=484765.33] [INSERT AverageLatency(us)=20.02] [READ AverageLatency(us)=6921.69] [CLEANUP AverageLatency(us)=485884.33] 
2014-07-06 09:49:13:499 758 sec: 5000000 operations; 2094.34 current ops/sec; [UPDATE AverageLatency(us)=459338.24] [INSERT AverageLatency(us)=12.86] [READ AverageLatency(us)=6793.92] [CLEANUP AverageLatency(us)=459353.59] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404665354
1404665354
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo workloadc...
workloadc...
+ echo 'start time: '
start time: 
++ date +%s
+ echo 1404665364
1404665364
++ echo /home/hadoop/git/physical_design/caseresult/case20/workloadc_1.dat
+ ./workloadc 5000000 20 /home/hadoop/git/physical_design/caseresult/case20/workloadc_1.dat
Loading workload...
Starting test.
2014-07-06 09:49:26:108 0 sec: 0 operations; 
14/07/06 09:49:26 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/06 09:49:26 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/06 09:49:26 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/06 09:49:26 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/06 09:49:26 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/06 09:49:26 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/06 09:49:26 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/06 09:49:26 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/06 09:49:26 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/06 09:49:26 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/06 09:49:26 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/06 09:49:26 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/06 09:49:26 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/06 09:49:26 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/06 09:49:26 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/06 09:49:26 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x5e852b9, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/06 09:49:26 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x5e852b9 connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/06 09:49:26 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/06 09:49:26 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/06 09:49:26 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x1470c77fb7c0000, negotiated timeout = 90000
2014-07-06 09:49:36:110 10 sec: 107954 operations; 10792.16 current ops/sec; [INSERT AverageLatency(us)=242.49] [READ AverageLatency(us)=9269.08] 
2014-07-06 09:49:46:112 20 sec: 256318 operations; 14833.43 current ops/sec; [INSERT AverageLatency(us)=12.66] [READ AverageLatency(us)=16323.28] 
2014-07-06 09:49:56:113 30 sec: 410260 operations; 15392.66 current ops/sec; [INSERT AverageLatency(us)=18.56] [READ AverageLatency(us)=12616.98] 
2014-07-06 09:50:06:114 40 sec: 520294 operations; 11002.3 current ops/sec; [INSERT AverageLatency(us)=15.16] [READ AverageLatency(us)=17833.84] 
2014-07-06 09:50:16:115 50 sec: 613255 operations; 9295.17 current ops/sec; [INSERT AverageLatency(us)=21.32] [READ AverageLatency(us)=21380.53] 
2014-07-06 09:50:26:116 60 sec: 713737 operations; 10047.2 current ops/sec; [INSERT AverageLatency(us)=11.7] [READ AverageLatency(us)=19575.93] 
2014-07-06 09:50:36:116 70 sec: 813524 operations; 9978.7 current ops/sec; [INSERT AverageLatency(us)=16.1] [READ AverageLatency(us)=19771.58] 
2014-07-06 09:50:46:118 80 sec: 919920 operations; 10638.54 current ops/sec; [INSERT AverageLatency(us)=11.82] [READ AverageLatency(us)=18923.69] 
2014-07-06 09:50:56:120 90 sec: 1024925 operations; 10497.35 current ops/sec; [INSERT AverageLatency(us)=15] [READ AverageLatency(us)=18374.74] 
2014-07-06 09:51:06:122 100 sec: 1125026 operations; 10009.1 current ops/sec; [INSERT AverageLatency(us)=15.38] [READ AverageLatency(us)=19637.53] 
2014-07-06 09:51:16:122 110 sec: 1217182 operations; 9214.68 current ops/sec; [INSERT AverageLatency(us)=10.76] [READ AverageLatency(us)=21924.19] 
2014-07-06 09:51:26:123 120 sec: 1314938 operations; 9774.62 current ops/sec; [INSERT AverageLatency(us)=14.08] [READ AverageLatency(us)=20513.75] 
2014-07-06 09:51:36:123 130 sec: 1399446 operations; 8450.8 current ops/sec; [INSERT AverageLatency(us)=12.74] [READ AverageLatency(us)=23753.54] 
2014-07-06 09:51:46:124 140 sec: 1481616 operations; 8216.18 current ops/sec; [INSERT AverageLatency(us)=11.79] [READ AverageLatency(us)=24060.37] 
2014-07-06 09:51:56:125 150 sec: 1563962 operations; 8233.78 current ops/sec; [INSERT AverageLatency(us)=14.37] [READ AverageLatency(us)=23890.12] 
2014-07-06 09:52:06:126 160 sec: 1651012 operations; 8705 current ops/sec; [INSERT AverageLatency(us)=12.76] [READ AverageLatency(us)=23191.62] 
2014-07-06 09:52:16:126 170 sec: 1741122 operations; 9010.1 current ops/sec; [INSERT AverageLatency(us)=12.89] [READ AverageLatency(us)=22139.52] 
2014-07-06 09:52:26:127 180 sec: 1835022 operations; 9389.06 current ops/sec; [INSERT AverageLatency(us)=13.88] [READ AverageLatency(us)=20975.62] 
2014-07-06 09:52:36:127 190 sec: 1933167 operations; 9814.5 current ops/sec; [INSERT AverageLatency(us)=12.25] [READ AverageLatency(us)=20243.39] 
2014-07-06 09:52:46:128 200 sec: 2036192 operations; 10301.47 current ops/sec; [INSERT AverageLatency(us)=14.27] [READ AverageLatency(us)=19512.99] 
2014-07-06 09:52:56:129 210 sec: 2140758 operations; 10455.55 current ops/sec; [INSERT AverageLatency(us)=10.86] [READ AverageLatency(us)=18926.77] 
2014-07-06 09:53:06:129 220 sec: 2222279 operations; 8152.1 current ops/sec; [INSERT AverageLatency(us)=12.05] [READ AverageLatency(us)=23779.71] 
2014-07-06 09:53:16:130 230 sec: 2303607 operations; 8131.99 current ops/sec; [INSERT AverageLatency(us)=12.23] [READ AverageLatency(us)=24587.27] 
2014-07-06 09:53:26:131 240 sec: 2391546 operations; 8793.02 current ops/sec; [INSERT AverageLatency(us)=14.2] [READ AverageLatency(us)=22790.56] 
2014-07-06 09:53:36:132 250 sec: 2477231 operations; 8567.64 current ops/sec; [INSERT AverageLatency(us)=11.76] [READ AverageLatency(us)=23185.66] 
2014-07-06 09:53:46:132 260 sec: 2557567 operations; 8033.6 current ops/sec; [INSERT AverageLatency(us)=11.86] [READ AverageLatency(us)=24576.93] 
2014-07-06 09:53:56:133 270 sec: 2639111 operations; 8153.58 current ops/sec; [INSERT AverageLatency(us)=15.42] [READ AverageLatency(us)=23888.73] 
2014-07-06 09:54:06:134 280 sec: 2724911 operations; 8579.14 current ops/sec; [INSERT AverageLatency(us)=13.48] [READ AverageLatency(us)=23395.08] 
2014-07-06 09:54:16:134 290 sec: 2799077 operations; 7416.6 current ops/sec; [INSERT AverageLatency(us)=12.28] [READ AverageLatency(us)=26905] 
2014-07-06 09:54:26:135 300 sec: 2884702 operations; 8561.64 current ops/sec; [INSERT AverageLatency(us)=11.99] [READ AverageLatency(us)=23292.98] 
2014-07-06 09:54:36:136 310 sec: 2964364 operations; 7965.4 current ops/sec; [INSERT AverageLatency(us)=13.81] [READ AverageLatency(us)=25263.5] 
2014-07-06 09:54:46:137 320 sec: 3045207 operations; 8083.49 current ops/sec; [INSERT AverageLatency(us)=13.76] [READ AverageLatency(us)=24716.79] 
2014-07-06 09:54:56:137 330 sec: 3125268 operations; 8006.1 current ops/sec; [INSERT AverageLatency(us)=12.52] [READ AverageLatency(us)=25459.52] 
2014-07-06 09:55:06:138 340 sec: 3204507 operations; 7923.11 current ops/sec; [INSERT AverageLatency(us)=12.75] [READ AverageLatency(us)=25255.58] 
2014-07-06 09:55:16:139 350 sec: 3272088 operations; 6757.42 current ops/sec; [INSERT AverageLatency(us)=11.98] [READ AverageLatency(us)=29117.56] 
2014-07-06 09:55:26:139 360 sec: 3349852 operations; 7776.4 current ops/sec; [INSERT AverageLatency(us)=11.88] [READ AverageLatency(us)=25044.88] 
2014-07-06 09:55:36:140 370 sec: 3428218 operations; 7835.82 current ops/sec; [INSERT AverageLatency(us)=14.36] [READ AverageLatency(us)=25627.6] 
2014-07-06 09:55:46:141 380 sec: 3518085 operations; 8985.8 current ops/sec; [INSERT AverageLatency(us)=12.13] [READ AverageLatency(us)=22533.06] 
2014-07-06 09:55:56:142 390 sec: 3593544 operations; 7545.15 current ops/sec; [INSERT AverageLatency(us)=11.07] [READ AverageLatency(us)=26128.51] 
2014-07-06 09:56:06:143 400 sec: 3674746 operations; 8119.39 current ops/sec; [INSERT AverageLatency(us)=13.63] [READ AverageLatency(us)=24842.44] 
2014-07-06 09:56:16:144 410 sec: 3767533 operations; 9277.77 current ops/sec; [INSERT AverageLatency(us)=10.22] [READ AverageLatency(us)=21240.24] 
2014-07-06 09:56:26:144 420 sec: 3862782 operations; 9524.9 current ops/sec; [INSERT AverageLatency(us)=15.99] [READ AverageLatency(us)=20645.87] 
2014-07-06 09:56:36:145 430 sec: 3948732 operations; 8594.14 current ops/sec; [INSERT AverageLatency(us)=11.93] [READ AverageLatency(us)=23034.33] 
2014-07-06 09:56:46:146 440 sec: 4032430 operations; 8368.96 current ops/sec; [INSERT AverageLatency(us)=16.01] [READ AverageLatency(us)=24102.38] 
2014-07-06 09:56:56:146 450 sec: 4106178 operations; 7374.8 current ops/sec; [INSERT AverageLatency(us)=12.61] [READ AverageLatency(us)=26346.06] 
2014-07-06 09:57:06:147 460 sec: 4186734 operations; 8054.79 current ops/sec; [INSERT AverageLatency(us)=11.42] [READ AverageLatency(us)=25237.84] 
2014-07-06 09:57:16:148 470 sec: 4269273 operations; 8253.07 current ops/sec; [INSERT AverageLatency(us)=11.1] [READ AverageLatency(us)=23975.41] 
2014-07-06 09:57:26:149 480 sec: 4345193 operations; 7592 current ops/sec; [INSERT AverageLatency(us)=11.1] [READ AverageLatency(us)=26165.04] 
2014-07-06 09:57:36:149 490 sec: 4428031 operations; 8282.97 current ops/sec; [INSERT AverageLatency(us)=12.35] [READ AverageLatency(us)=24064.79] 
2014-07-06 09:57:46:150 500 sec: 4504300 operations; 7626.14 current ops/sec; [INSERT AverageLatency(us)=15.07] [READ AverageLatency(us)=26458.05] 
2014-07-06 09:57:56:151 510 sec: 4582897 operations; 7858.91 current ops/sec; [INSERT AverageLatency(us)=12.79] [READ AverageLatency(us)=24918.19] 
2014-07-06 09:58:06:152 520 sec: 4661144 operations; 7823.92 current ops/sec; [INSERT AverageLatency(us)=15.47] [READ AverageLatency(us)=25538.08] 
2014-07-06 09:58:16:153 530 sec: 4741223 operations; 8007.1 current ops/sec; [INSERT AverageLatency(us)=15.28] [READ AverageLatency(us)=25068.87] 
2014-07-06 09:58:26:154 540 sec: 4822841 operations; 8160.98 current ops/sec; [INSERT AverageLatency(us)=11.36] [READ AverageLatency(us)=23929.78] 
2014-07-06 09:58:36:155 550 sec: 4876948 operations; 5410.7 current ops/sec; [INSERT AverageLatency(us)=10.91] [READ AverageLatency(us)=37425.58] 
2014-07-06 09:58:46:155 560 sec: 4941138 operations; 6418.36 current ops/sec; [UPDATE AverageLatency(us)=4253994] [INSERT AverageLatency(us)=13.66] [READ AverageLatency(us)=30203.67] [CLEANUP AverageLatency(us)=4254352] 
2014-07-06 09:58:56:156 570 sec: 4984449 operations; 4330.67 current ops/sec; [UPDATE AverageLatency(us)=1255097.83] [INSERT AverageLatency(us)=10.22] [READ AverageLatency(us)=32275.74] [CLEANUP AverageLatency(us)=1255594] 
2014-07-06 09:59:06:157 580 sec: 5000000 operations; 1554.94 current ops/sec; [UPDATE AverageLatency(us)=1253148.33] [INSERT AverageLatency(us)=12.24] [READ AverageLatency(us)=33028.52] [CLEANUP AverageLatency(us)=1253162.17] 
2014-07-06 09:59:06:564 580 sec: 5000000 operations; 0 current ops/sec; [UPDATE AverageLatency(us)=446248]   [CLEANUP AverageLatency(us)=446260] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404665947
1404665947
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ let counter=1+1
+ read line
+ set +x
