++ ls caseresult/ -ltr
++ wc -l
+ filename=case131
+ mkdir caseresult/case131
+ ssh hadoop@master mkdir /home/hadoop/git/physical_design/caseresult/case131
+ RESULT_DIR=/home/hadoop/git/physical_design/caseresult/case131
+ TEN=10
+ SIXTY=60
+ SLEEP_TIME=300
+ YCSB_DIR=/home/hadoop/ycsb-0.1.4
+ number_of_operations=50000000
+ number_of_threads=20
+ number_of_records=50000000
+ output_file_suffix=.dat
+ experiment_list_file=/home/hadoop/git/physical_design/case131.list
+ clean=false
+ create=false
+ load=false
+ random_read=false
+ workloada=false
+ workloadb=false
+ workloadc=false
+ scan=false
+ all=false
+ for i in '$@'
+ '[' clean == all ']'
+ '[' clean == clean ']'
+ clean=true
+ for i in '$@'
+ '[' create == all ']'
+ '[' create == clean ']'
+ '[' create == create ']'
+ create=true
+ for i in '$@'
+ '[' load == all ']'
+ '[' load == clean ']'
+ '[' load == create ']'
+ '[' load == load ']'
+ load=true
+ let counter=1
+ cd /home/hadoop/ycsb-0.1.4
++ pwd
+ echo /home/hadoop/ycsb-0.1.4
/home/hadoop/ycsb-0.1.4
+ read line
+ false
+ true
+ echo 'sleeping for 60 ...'
sleeping for 60 ...
+ sleep 60
+ echo 'droping usertable...'
droping usertable...
+ ssh hadoop@master /home/hadoop/hbase/bin/hbase shell /home/hadoop/git/physical_design/delete_table
0 row(s) in 2.6970 seconds

0 row(s) in 2.3720 seconds

0 row(s) in 0.0650 seconds

+ echo 'sleeping for 300 ...'
sleeping for 300 ...
+ sleep 300
+ false
+ true
+ echo 'creating usertable...'
creating usertable...
+ create_statement='create '\''usertable'\'', { NAME=>'\''family'\'', CONFIGURATION => { '\''hbase.hregion.majorcompaction'\'' => '\''0'\'' } ,  COMPRESSION=>'\''GZ'\''}, SPLITS => ['\''user1'\'', '\''user2'\'', '\''user3'\'', '\''user4'\'', '\''user5'\'', '\''user6'\'', '\''user7'\'', '\''user8'\'', '\''user9'\'']'
+ echo create ''\''usertable'\'',' '{' 'NAME=>'\''family'\'',' CONFIGURATION '=>' '{' ''\''hbase.hregion.majorcompaction'\''' '=>' ''\''0'\''' '}' , 'COMPRESSION=>'\''GZ'\''},' SPLITS '=>' '['\''user1'\'',' ''\''user2'\'',' ''\''user3'\'',' ''\''user4'\'',' ''\''user5'\'',' ''\''user6'\'',' ''\''user7'\'',' ''\''user8'\'',' ''\''user9'\'']'
+ echo 'exit '
+ scp /home/hadoop/git/physical_design/caseresult/case131/create_1.script hadoop@master:/home/hadoop/git/physical_design/caseresult/case131/create_1.script
+ create_table /home/hadoop/git/physical_design/caseresult/case131/create_1.script
+ echo 'creating table...'
creating table...
+ echo /home/hadoop/git/physical_design/caseresult/case131/create_1.script
/home/hadoop/git/physical_design/caseresult/case131/create_1.script
+ ssh hadoop@master /home/hadoop/hbase/bin/hbase shell /home/hadoop/git/physical_design/caseresult/case131/create_1.script
0 row(s) in 1.7990 seconds

+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ false
+ true
+ echo 'loading data...'
loading data...
+ echo 'starting time: '
starting time: 
++ date +%s
+ echo 1405302747
1405302747
++ echo /home/hadoop/git/physical_design/caseresult/case131/load_1.dat
+ ./ld 50000000 20 /home/hadoop/git/physical_design/caseresult/case131/load_1.dat
Loading workload...
Starting test.
2014-07-13 18:52:27:750 0 sec: 0 operations; 
14/07/13 18:52:28 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/13 18:52:28 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm43.almaden.ibm.com
14/07/13 18:52:28 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/13 18:52:28 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/13 18:52:28 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/13 18:52:28 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf
14/07/13 18:52:28 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/13 18:52:28 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/13 18:52:28 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/13 18:52:28 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/13 18:52:28 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/13 18:52:28 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/13 18:52:28 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/13 18:52:28 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/13 18:52:28 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/13 18:52:28 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x29ee65b1, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/13 18:52:28 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x29ee65b1 connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/13 18:52:28 INFO zookeeper.ClientCnxn: Opening socket connection to server master/9.1.143.58:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/13 18:52:28 INFO zookeeper.ClientCnxn: Socket connection established to master/9.1.143.58:2181, initiating session
14/07/13 18:52:28 INFO zookeeper.ClientCnxn: Session establishment complete on server master/9.1.143.58:2181, sessionid = 0x47343e5afd000e, negotiated timeout = 90000
2014-07-13 18:52:38:189 10 sec: 269397 operations; 25809.25 current ops/sec; [INSERT AverageLatency(us)=363.45] 
2014-07-13 18:52:48:189 20 sec: 319308 operations; 4990.6 current ops/sec; [INSERT AverageLatency(us)=121.05] 
2014-07-13 18:52:58:359 30 sec: 455887 operations; 13429.6 current ops/sec; [INSERT AverageLatency(us)=2317.36] 
2014-07-13 18:53:08:360 40 sec: 615156 operations; 15925.31 current ops/sec; [INSERT AverageLatency(us)=1057.38] 
2014-07-13 18:53:18:360 50 sec: 615156 operations; 0 current ops/sec;  
14/07/13 18:53:23 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2267 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=784, waitTime=3226, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 18:52:29 PDT 2014, retrying after 10058 ms, replay 2267 ops.
2014-07-13 18:53:28:360 60 sec: 615156 operations; 0 current ops/sec;  
14/07/13 18:53:34 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 18:52:29 PDT 2014
2014-07-13 18:53:38:361 70 sec: 760732 operations; 14556.14 current ops/sec; [INSERT AverageLatency(us)=1559.53] 
2014-07-13 18:53:48:361 80 sec: 995532 operations; 23480 current ops/sec; [INSERT AverageLatency(us)=1805.17] 
14/07/13 18:53:53 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2202 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1147, waitTime=2068, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 18:53:02 PDT 2014, retrying after 10094 ms, replay 2202 ops.
14/07/13 18:53:53 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2269 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1147, waitTime=2068, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 18:52:58 PDT 2014, retrying after 10006 ms, replay 2269 ops.
14/07/13 18:53:53 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2289 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1147, waitTime=2068, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 18:53:00 PDT 2014, retrying after 10096 ms, replay 2289 ops.
14/07/13 18:53:53 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2299 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1147, waitTime=2068, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 18:53:00 PDT 2014, retrying after 10032 ms, replay 2299 ops.
14/07/13 18:53:53 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2306 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1147, waitTime=2068, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 18:52:58 PDT 2014, retrying after 10092 ms, replay 2306 ops.
2014-07-13 18:53:58:362 90 sec: 1173980 operations; 17843.02 current ops/sec; [INSERT AverageLatency(us)=1333.92] 
14/07/13 18:54:05 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 2306 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1378, waitTime=2287, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 18:52:58 PDT 2014, retrying after 10027 ms, replay 2306 ops.
14/07/13 18:54:05 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2299 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1378, waitTime=2287, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 18:53:00 PDT 2014, retrying after 10035 ms, replay 2299 ops.
14/07/13 18:54:05 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2289 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1378, waitTime=2287, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 18:53:00 PDT 2014, retrying after 10043 ms, replay 2289 ops.
14/07/13 18:54:05 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2202 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1378, waitTime=2287, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 18:53:02 PDT 2014, retrying after 10058 ms, replay 2202 ops.
14/07/13 18:54:05 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2269 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1378, waitTime=2287, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 18:52:58 PDT 2014, retrying after 10007 ms, replay 2269 ops.
2014-07-13 18:54:08:362 100 sec: 1347732 operations; 17375.2 current ops/sec; [INSERT AverageLatency(us)=309.21] 
14/07/13 18:54:17 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 18:52:58 PDT 2014
14/07/13 18:54:17 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 18:53:02 PDT 2014
14/07/13 18:54:17 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 18:52:58 PDT 2014
14/07/13 18:54:17 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 18:53:00 PDT 2014
14/07/13 18:54:17 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 18:53:00 PDT 2014
2014-07-13 18:54:18:363 110 sec: 1474524 operations; 12679.2 current ops/sec; [INSERT AverageLatency(us)=4046.02] 
2014-07-13 18:54:28:363 120 sec: 1540268 operations; 6573.74 current ops/sec; [INSERT AverageLatency(us)=447.41] 
2014-07-13 18:54:38:363 130 sec: 1540268 operations; 0 current ops/sec;  
2014-07-13 18:54:48:364 140 sec: 1540268 operations; 0 current ops/sec;  
14/07/13 18:54:51 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2292 ops, last exception: java.io.IOException: Unexpected closed connection on slave1,60020,1405330807068, tracking started Sun Jul 13 18:54:00 PDT 2014, retrying after 10015 ms, replay 2292 ops.
14/07/13 18:54:51 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2246 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47234 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 18:53:59 PDT 2014, retrying after 10013 ms, replay 2246 ops.
14/07/13 18:54:51 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2246 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47234 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 18:53:59 PDT 2014, retrying after 10004 ms, replay 2246 ops.
14/07/13 18:54:51 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2302 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47234 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 18:53:58 PDT 2014, retrying after 10035 ms, replay 2302 ops.
14/07/13 18:54:51 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2234 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47234 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 18:53:59 PDT 2014, retrying after 10015 ms, replay 2234 ops.
14/07/13 18:54:51 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2214 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47234 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 18:53:58 PDT 2014, retrying after 10015 ms, replay 2214 ops.
2014-07-13 18:54:58:364 150 sec: 1540268 operations; 0 current ops/sec;  
14/07/13 18:55:03 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 18:53:59 PDT 2014
14/07/13 18:55:03 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 18:54:00 PDT 2014
14/07/13 18:55:03 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 18:53:59 PDT 2014
14/07/13 18:55:03 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 18:53:58 PDT 2014
14/07/13 18:55:03 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 18:53:58 PDT 2014
14/07/13 18:55:03 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 18:53:59 PDT 2014
2014-07-13 18:55:08:364 160 sec: 1793852 operations; 25358.4 current ops/sec; [INSERT AverageLatency(us)=2583.4] 
14/07/13 18:55:08 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2248 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2063, waitTime=2092, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 18:54:18 PDT 2014, retrying after 10029 ms, replay 2248 ops.
14/07/13 18:55:08 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2338 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2063, waitTime=2092, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 18:54:17 PDT 2014, retrying after 10072 ms, replay 2338 ops.
14/07/13 18:55:08 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2289 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2063, waitTime=2092, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 18:54:17 PDT 2014, retrying after 10005 ms, replay 2289 ops.
14/07/13 18:55:08 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2244 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2063, waitTime=2092, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 18:54:18 PDT 2014, retrying after 10007 ms, replay 2244 ops.
14/07/13 18:55:08 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2223 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2063, waitTime=2092, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 18:54:17 PDT 2014, retrying after 10085 ms, replay 2223 ops.
2014-07-13 18:55:18:365 170 sec: 2005172 operations; 21129.89 current ops/sec; [INSERT AverageLatency(us)=1208.99] 
14/07/13 18:55:21 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 2244 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2308, waitTime=3521, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 18:54:18 PDT 2014, retrying after 10038 ms, replay 2244 ops.
14/07/13 18:55:21 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2338 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2308, waitTime=3521, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 18:54:17 PDT 2014, retrying after 10035 ms, replay 2338 ops.
14/07/13 18:55:21 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 2289 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2308, waitTime=3521, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 18:54:17 PDT 2014, retrying after 10061 ms, replay 2289 ops.
14/07/13 18:55:21 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2223 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2308, waitTime=3521, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 18:54:17 PDT 2014, retrying after 10009 ms, replay 2223 ops.
14/07/13 18:55:21 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2248 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2308, waitTime=3521, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 18:54:18 PDT 2014, retrying after 10017 ms, replay 2248 ops.
2014-07-13 18:55:28:365 180 sec: 2005172 operations; 0 current ops/sec;  
14/07/13 18:55:33 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 2244 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2503, waitTime=2355, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 18:54:18 PDT 2014, retrying after 20144 ms, replay 2244 ops.
14/07/13 18:55:33 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 2338 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2503, waitTime=2355, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 18:54:17 PDT 2014, retrying after 20118 ms, replay 2338 ops.
14/07/13 18:55:33 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 failed 2289 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2503, waitTime=2355, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 18:54:17 PDT 2014, retrying after 20182 ms, replay 2289 ops.
14/07/13 18:55:33 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2248 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2503, waitTime=2355, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 18:54:18 PDT 2014, retrying after 20057 ms, replay 2248 ops.
14/07/13 18:55:33 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 failed 2223 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2503, waitTime=2355, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 18:54:17 PDT 2014, retrying after 20112 ms, replay 2223 ops.
2014-07-13 18:55:38:366 190 sec: 2005172 operations; 0 current ops/sec;  
2014-07-13 18:55:48:366 200 sec: 2341444 operations; 33627.2 current ops/sec; [INSERT AverageLatency(us)=1171.78] 
14/07/13 18:55:54 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 18:54:18 PDT 2014
14/07/13 18:55:54 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 18:54:17 PDT 2014
14/07/13 18:55:54 INFO client.AsyncProcess: #17, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 18:54:17 PDT 2014
14/07/13 18:55:54 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 18:54:18 PDT 2014
14/07/13 18:55:54 INFO client.AsyncProcess: #5, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 18:54:17 PDT 2014
2014-07-13 18:55:58:366 210 sec: 2784708 operations; 44326.4 current ops/sec; [INSERT AverageLatency(us)=1658.56] 
2014-07-13 18:56:08:367 220 sec: 3273092 operations; 48833.52 current ops/sec; [INSERT AverageLatency(us)=475.65] 
2014-07-13 18:56:18:367 230 sec: 3493804 operations; 22071.2 current ops/sec; [INSERT AverageLatency(us)=619.32] 
2014-07-13 18:56:28:368 240 sec: 3899800 operations; 40595.54 current ops/sec; [INSERT AverageLatency(us)=629.31] 
2014-07-13 18:56:38:368 250 sec: 4231076 operations; 33127.6 current ops/sec; [INSERT AverageLatency(us)=522.69] 
2014-07-13 18:56:48:369 260 sec: 4677196 operations; 44607.54 current ops/sec; [INSERT AverageLatency(us)=367.52] 
2014-07-13 18:56:58:369 270 sec: 4761724 operations; 8452.8 current ops/sec; [INSERT AverageLatency(us)=524.1] 
2014-07-13 18:57:08:370 280 sec: 4777978 operations; 1625.24 current ops/sec; [INSERT AverageLatency(us)=5790.68] 
2014-07-13 18:57:18:415 290 sec: 5087957 operations; 30859.03 current ops/sec; [INSERT AverageLatency(us)=1680.14] 
2014-07-13 18:57:28:737 300 sec: 5547044 operations; 44476.55 current ops/sec; [INSERT AverageLatency(us)=385.93] 
2014-07-13 18:57:38:738 310 sec: 5823127 operations; 27605.54 current ops/sec; [INSERT AverageLatency(us)=800.62] 
2014-07-13 18:57:48:738 320 sec: 6156436 operations; 33330.9 current ops/sec; [INSERT AverageLatency(us)=473.82] 
2014-07-13 18:57:58:739 330 sec: 6513332 operations; 35686.03 current ops/sec; [INSERT AverageLatency(us)=555.29] 
2014-07-13 18:58:08:739 340 sec: 6513332 operations; 0 current ops/sec;  
2014-07-13 18:58:18:740 350 sec: 6746302 operations; 23297 current ops/sec; [INSERT AverageLatency(us)=1914.65] 
2014-07-13 18:58:28:740 360 sec: 7259996 operations; 51364.26 current ops/sec; [INSERT AverageLatency(us)=361.28] 
2014-07-13 18:58:38:740 370 sec: 7673244 operations; 41324.8 current ops/sec; [INSERT AverageLatency(us)=456.21] 
2014-07-13 18:58:48:741 380 sec: 7940916 operations; 26764.52 current ops/sec; [INSERT AverageLatency(us)=302.13] 
2014-07-13 18:58:58:741 390 sec: 8086492 operations; 14557.6 current ops/sec; [INSERT AverageLatency(us)=2272.18] 
2014-07-13 18:59:09:029 401 sec: 8533614 operations; 43460.54 current ops/sec; [INSERT AverageLatency(us)=420.29] 
2014-07-13 18:59:19:029 411 sec: 9067956 operations; 53434.2 current ops/sec; [INSERT AverageLatency(us)=333.79] 
2014-07-13 18:59:29:130 421 sec: 9287853 operations; 21769.82 current ops/sec; [INSERT AverageLatency(us)=1033.5] 
2014-07-13 18:59:39:731 431 sec: 9701082 operations; 38980.19 current ops/sec; [INSERT AverageLatency(us)=461.29] 
2014-07-13 18:59:49:732 441 sec: 9950804 operations; 24969.7 current ops/sec; [INSERT AverageLatency(us)=282.07] 
2014-07-13 18:59:59:732 451 sec: 9950804 operations; 0 current ops/sec;  
2014-07-13 19:00:09:733 461 sec: 10218476 operations; 26764.52 current ops/sec; [INSERT AverageLatency(us)=1926.73] 
2014-07-13 19:00:19:733 471 sec: 10762026 operations; 54355 current ops/sec; [INSERT AverageLatency(us)=347.42] 
2014-07-13 19:00:29:734 481 sec: 10913484 operations; 15144.29 current ops/sec; [INSERT AverageLatency(us)=277.03] 
2014-07-13 19:00:39:848 492 sec: 11286204 operations; 36851.89 current ops/sec; [INSERT AverageLatency(us)=826.97] 
2014-07-13 19:00:49:848 502 sec: 11918660 operations; 63245.6 current ops/sec; [INSERT AverageLatency(us)=412.86] 
2014-07-13 19:00:59:849 512 sec: 12120356 operations; 20167.58 current ops/sec; [INSERT AverageLatency(us)=362.37] 
2014-07-13 19:01:09:849 522 sec: 12510124 operations; 38976.8 current ops/sec; [INSERT AverageLatency(us)=750.22] 
2014-07-13 19:01:19:850 532 sec: 12580564 operations; 7043.3 current ops/sec; [INSERT AverageLatency(us)=483.59] 
2014-07-13 19:01:29:850 542 sec: 12580564 operations; 0 current ops/sec;  
2014-07-13 19:01:39:851 552 sec: 12834148 operations; 25355.86 current ops/sec; [INSERT AverageLatency(us)=1410.21] 
2014-07-13 19:01:49:851 562 sec: 12834148 operations; 0 current ops/sec;  
2014-07-13 19:01:59:852 572 sec: 12956244 operations; 12208.38 current ops/sec; [INSERT AverageLatency(us)=1068.21] 
2014-07-13 19:02:09:852 582 sec: 13289660 operations; 33341.6 current ops/sec; [INSERT AverageLatency(us)=1828.12] 
2014-07-13 19:02:19:853 592 sec: 13303748 operations; 1408.66 current ops/sec; [INSERT AverageLatency(us)=621.24] 
2014-07-13 19:02:29:853 602 sec: 13490597 operations; 18684.9 current ops/sec; [INSERT AverageLatency(us)=1772.89] 
2014-07-13 19:02:39:854 612 sec: 13900140 operations; 40950.2 current ops/sec; [INSERT AverageLatency(us)=591.65] 
2014-07-13 19:02:49:854 622 sec: 14167812 operations; 26767.2 current ops/sec; [INSERT AverageLatency(us)=848.92] 
14/07/13 19:02:55 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 2270 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9423, waitTime=2188, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:02:04 PDT 2014, retrying after 10098 ms, replay 2270 ops.
14/07/13 19:02:55 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2283 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9423, waitTime=2188, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:02:04 PDT 2014, retrying after 10051 ms, replay 2283 ops.
2014-07-13 19:02:59:855 632 sec: 14275820 operations; 10799.72 current ops/sec; [INSERT AverageLatency(us)=229.67] 
14/07/13 19:03:06 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:02:04 PDT 2014
14/07/13 19:03:06 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:02:04 PDT 2014
2014-07-13 19:03:09:855 642 sec: 14426092 operations; 15027.2 current ops/sec; [INSERT AverageLatency(us)=2298.84] 
2014-07-13 19:03:19:856 652 sec: 14942652 operations; 51650.83 current ops/sec; [INSERT AverageLatency(us)=561.63] 
2014-07-13 19:03:29:856 662 sec: 15299548 operations; 35689.6 current ops/sec; [INSERT AverageLatency(us)=394.37] 
2014-07-13 19:03:39:857 672 sec: 15299548 operations; 0 current ops/sec;  
2014-07-13 19:03:49:857 682 sec: 15299548 operations; 0 current ops/sec;  
2014-07-13 19:03:59:858 692 sec: 15299548 operations; 0 current ops/sec;  
2014-07-13 19:04:09:858 702 sec: 15726678 operations; 42713 current ops/sec; [INSERT AverageLatency(us)=1275.9] 
2014-07-13 19:04:19:859 712 sec: 16093172 operations; 36645.74 current ops/sec; [INSERT AverageLatency(us)=1070.38] 
14/07/13 19:04:26 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2234 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11040, waitTime=3707, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:03:26 PDT 2014, retrying after 10033 ms, replay 2234 ops.
2014-07-13 19:04:29:859 722 sec: 16093172 operations; 0 current ops/sec;  
2014-07-13 19:04:39:860 732 sec: 16093172 operations; 0 current ops/sec;  
14/07/13 19:04:40 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 2234 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11325, waitTime=3145, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:03:26 PDT 2014, retrying after 10064 ms, replay 2234 ops.
2014-07-13 19:04:49:860 742 sec: 16093172 operations; 0 current ops/sec;  
14/07/13 19:04:52 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:03:26 PDT 2014
2014-07-13 19:04:59:861 752 sec: 16403108 operations; 30990.5 current ops/sec; [INSERT AverageLatency(us)=1937.43] 
2014-07-13 19:05:09:861 762 sec: 16927652 operations; 52454.4 current ops/sec; [INSERT AverageLatency(us)=861.3] 
2014-07-13 19:05:19:862 772 sec: 16994804 operations; 6714.53 current ops/sec; [INSERT AverageLatency(us)=889.83] 
2014-07-13 19:05:29:862 782 sec: 17140380 operations; 14557.6 current ops/sec; [INSERT AverageLatency(us)=1051.02] 
2014-07-13 19:05:39:863 792 sec: 17530148 operations; 38972.9 current ops/sec; [INSERT AverageLatency(us)=938.12] 
2014-07-13 19:05:49:863 802 sec: 17530148 operations; 0 current ops/sec;  
2014-07-13 19:05:59:864 812 sec: 17689812 operations; 15964.8 current ops/sec; [INSERT AverageLatency(us)=1738.93] 
2014-07-13 19:06:09:864 822 sec: 17910524 operations; 22071.2 current ops/sec; [INSERT AverageLatency(us)=1116.52] 
2014-07-13 19:06:19:865 832 sec: 17910524 operations; 0 current ops/sec;  
2014-07-13 19:06:29:865 842 sec: 18290289 operations; 37976.5 current ops/sec; [INSERT AverageLatency(us)=1142.77] 
2014-07-13 19:06:39:866 852 sec: 18600836 operations; 31051.59 current ops/sec; [INSERT AverageLatency(us)=359.18] 
2014-07-13 19:06:49:866 862 sec: 19103308 operations; 50247.2 current ops/sec; [INSERT AverageLatency(us)=390.13] 
14/07/13 19:06:51 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2298 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=13787, waitTime=2231, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:05:59 PDT 2014, retrying after 10006 ms, replay 2298 ops.
14/07/13 19:06:51 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2263 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=13787, waitTime=2231, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:05:59 PDT 2014, retrying after 10009 ms, replay 2263 ops.
14/07/13 19:06:51 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 2300 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=13787, waitTime=2231, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:05:59 PDT 2014, retrying after 10022 ms, replay 2300 ops.
2014-07-13 19:06:59:867 872 sec: 19140876 operations; 3756.42 current ops/sec; [INSERT AverageLatency(us)=1427.65] 
14/07/13 19:07:03 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2298 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47240 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:05:59 PDT 2014, retrying after 10074 ms, replay 2298 ops.
14/07/13 19:07:03 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 2300 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47240 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:05:59 PDT 2014, retrying after 10028 ms, replay 2300 ops.
14/07/13 19:07:03 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2263 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47240 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:05:59 PDT 2014, retrying after 10015 ms, replay 2263 ops.
2014-07-13 19:07:09:868 882 sec: 19140876 operations; 0 current ops/sec;  
14/07/13 19:07:16 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 failed 2298 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14173, waitTime=2843, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:05:59 PDT 2014, retrying after 20057 ms, replay 2298 ops.
14/07/13 19:07:16 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 2263 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14173, waitTime=2843, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:05:59 PDT 2014, retrying after 20056 ms, replay 2263 ops.
14/07/13 19:07:16 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 failed 2300 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14173, waitTime=2843, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:05:59 PDT 2014, retrying after 20043 ms, replay 2300 ops.
2014-07-13 19:07:19:868 892 sec: 19140876 operations; 0 current ops/sec;  
2014-07-13 19:07:29:868 902 sec: 19305236 operations; 16436 current ops/sec; [INSERT AverageLatency(us)=2047.34] 
14/07/13 19:07:38 INFO client.AsyncProcess: #7, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:05:59 PDT 2014
14/07/13 19:07:38 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 failed 2263 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14388, waitTime=2089, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:05:59 PDT 2014, retrying after 20098 ms, replay 2263 ops.
14/07/13 19:07:38 INFO client.AsyncProcess: #19, table=usertable, attempt=13/35 failed 2298 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14388, waitTime=2089, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:05:59 PDT 2014, retrying after 20106 ms, replay 2298 ops.
2014-07-13 19:07:40:173 912 sec: 19315627 operations; 1008.35 current ops/sec; [INSERT AverageLatency(us)=9605.78] 
14/07/13 19:07:45 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2243 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14489, waitTime=3287, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:06:48 PDT 2014, retrying after 10070 ms, replay 2243 ops.
14/07/13 19:07:45 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2267 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14489, waitTime=3287, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:06:50 PDT 2014, retrying after 10041 ms, replay 2267 ops.
14/07/13 19:07:45 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2280 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14489, waitTime=3287, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:06:49 PDT 2014, retrying after 10049 ms, replay 2280 ops.
14/07/13 19:07:45 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2280 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14489, waitTime=3287, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:06:51 PDT 2014, retrying after 10076 ms, replay 2280 ops.
14/07/13 19:07:45 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2234 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14489, waitTime=3287, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:06:51 PDT 2014, retrying after 10013 ms, replay 2234 ops.
2014-07-13 19:07:50:173 922 sec: 19624564 operations; 30893.7 current ops/sec; [INSERT AverageLatency(us)=1521.9] 
14/07/13 19:07:58 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2267 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14722, waitTime=3335, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:06:50 PDT 2014, retrying after 10087 ms, replay 2267 ops.
14/07/13 19:07:58 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2280 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14722, waitTime=3335, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:06:49 PDT 2014, retrying after 10068 ms, replay 2280 ops.
14/07/13 19:07:58 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 2243 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14722, waitTime=3335, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:06:48 PDT 2014, retrying after 10038 ms, replay 2243 ops.
14/07/13 19:07:58 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2234 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14722, waitTime=3335, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:06:51 PDT 2014, retrying after 10044 ms, replay 2234 ops.
14/07/13 19:07:58 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2280 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14722, waitTime=3335, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:06:51 PDT 2014, retrying after 10058 ms, replay 2280 ops.
2014-07-13 19:08:00:176 932 sec: 19624564 operations; 0 current ops/sec;  
14/07/13 19:08:02 INFO client.AsyncProcess: #19, table=usertable, attempt=14/35 failed 2298 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14770, waitTime=2125, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:05:59 PDT 2014, retrying after 20018 ms, replay 2298 ops.
14/07/13 19:08:02 INFO client.AsyncProcess: #9, table=usertable, attempt=14/35 failed 2263 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14770, waitTime=2125, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:05:59 PDT 2014, retrying after 20129 ms, replay 2263 ops.
14/07/13 19:08:08 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:06:48 PDT 2014
14/07/13 19:08:08 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:06:51 PDT 2014
14/07/13 19:08:08 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:06:50 PDT 2014
14/07/13 19:08:08 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:06:49 PDT 2014
14/07/13 19:08:09 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:06:51 PDT 2014
2014-07-13 19:08:10:176 942 sec: 19758364 operations; 13378.66 current ops/sec; [INSERT AverageLatency(us)=3465.23] 
2014-07-13 19:08:20:176 952 sec: 20145791 operations; 38742.7 current ops/sec; [INSERT AverageLatency(us)=653.03] 
14/07/13 19:08:24 INFO client.AsyncProcess: #19, table=usertable, attempt=15/35 failed 2298 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=15195, waitTime=2532, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:05:59 PDT 2014, retrying after 20061 ms, replay 2298 ops.
14/07/13 19:08:24 INFO client.AsyncProcess: #9, table=usertable, attempt=15/35 failed 2263 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=15205, waitTime=2111, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:05:59 PDT 2014, retrying after 20041 ms, replay 2263 ops.
2014-07-13 19:08:30:177 962 sec: 20211564 operations; 6576.64 current ops/sec; [INSERT AverageLatency(us)=448.02] 
2014-07-13 19:08:40:399 972 sec: 20787164 operations; 56309.92 current ops/sec; [INSERT AverageLatency(us)=669.59] 
14/07/13 19:08:45 INFO client.AsyncProcess: #9, table=usertable, attempt=16/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:05:59 PDT 2014
14/07/13 19:08:45 INFO client.AsyncProcess: #19, table=usertable, attempt=16/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:05:59 PDT 2014
2014-07-13 19:08:50:399 982 sec: 21404348 operations; 61718.4 current ops/sec; [INSERT AverageLatency(us)=853.91] 
2014-07-13 19:09:00:421 992 sec: 21950527 operations; 54498 current ops/sec; [INSERT AverageLatency(us)=348.67] 
2014-07-13 19:09:10:422 1002 sec: 22517300 operations; 56671.63 current ops/sec; [INSERT AverageLatency(us)=327.34] 
2014-07-13 19:09:20:422 1012 sec: 23113692 operations; 59639.2 current ops/sec; [INSERT AverageLatency(us)=343.57] 
2014-07-13 19:09:30:828 1023 sec: 23606262 operations; 47335.19 current ops/sec; [INSERT AverageLatency(us)=326.03] 
2014-07-13 19:09:40:828 1033 sec: 23968364 operations; 36210.2 current ops/sec; [INSERT AverageLatency(us)=439.04] 
2014-07-13 19:09:50:829 1043 sec: 23977756 operations; 939.11 current ops/sec; [INSERT AverageLatency(us)=1286.06] 
2014-07-13 19:10:00:829 1053 sec: 23977756 operations; 0 current ops/sec;  
2014-07-13 19:10:10:830 1063 sec: 23977756 operations; 0 current ops/sec;  
2014-07-13 19:10:20:830 1073 sec: 24034108 operations; 5635.2 current ops/sec; [INSERT AverageLatency(us)=5142.27] 
2014-07-13 19:10:30:831 1083 sec: 24101832 operations; 6772.4 current ops/sec; [INSERT AverageLatency(us)=4724.85] 
14/07/13 19:10:33 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2301 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=17523, waitTime=2006, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:09:37 PDT 2014, retrying after 10037 ms, replay 2301 ops.
2014-07-13 19:10:40:831 1093 sec: 24649790 operations; 54790.32 current ops/sec; [INSERT AverageLatency(us)=1047.53] 
14/07/13 19:10:45 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2301 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=17873, waitTime=2252, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:09:37 PDT 2014, retrying after 10089 ms, replay 2301 ops.
2014-07-13 19:10:50:832 1103 sec: 25147060 operations; 49722.03 current ops/sec; [INSERT AverageLatency(us)=327.34] 
14/07/13 19:10:57 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:09:37 PDT 2014
2014-07-13 19:11:00:838 1113 sec: 25459349 operations; 31210.17 current ops/sec; [INSERT AverageLatency(us)=778.01] 
2014-07-13 19:11:10:839 1123 sec: 25475780 operations; 1642.94 current ops/sec; [INSERT AverageLatency(us)=1508.94] 
2014-07-13 19:11:20:839 1133 sec: 25475780 operations; 0 current ops/sec;  
2014-07-13 19:11:30:919 1143 sec: 25785809 operations; 30756.85 current ops/sec; [INSERT AverageLatency(us)=1171.03] 
2014-07-13 19:11:40:919 1153 sec: 25917204 operations; 13139.5 current ops/sec; [INSERT AverageLatency(us)=133.08] 
14/07/13 19:11:50 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2211 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=18954, waitTime=2034, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:10:57 PDT 2014, retrying after 10067 ms, replay 2211 ops.
14/07/13 19:11:50 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2287 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=18954, waitTime=2034, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:10:56 PDT 2014, retrying after 10043 ms, replay 2287 ops.
14/07/13 19:11:50 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2250 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=18954, waitTime=2034, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:10:55 PDT 2014, retrying after 10072 ms, replay 2250 ops.
14/07/13 19:11:50 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2221 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=18954, waitTime=2034, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:10:56 PDT 2014, retrying after 10001 ms, replay 2221 ops.
14/07/13 19:11:50 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2266 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=18958, waitTime=2182, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:10:57 PDT 2014, retrying after 10066 ms, replay 2266 ops.
14/07/13 19:11:50 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2306 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=18958, waitTime=2182, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:10:56 PDT 2014, retrying after 10026 ms, replay 2306 ops.
14/07/13 19:11:50 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2250 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=18958, waitTime=2182, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:10:57 PDT 2014, retrying after 10088 ms, replay 2250 ops.
2014-07-13 19:11:50:920 1163 sec: 25921538 operations; 433.36 current ops/sec; [INSERT AverageLatency(us)=11814.59] 
2014-07-13 19:12:00:920 1173 sec: 26494812 operations; 57327.4 current ops/sec; [INSERT AverageLatency(us)=773.83] 
14/07/13 19:12:01 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:10:57 PDT 2014
14/07/13 19:12:01 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:10:57 PDT 2014
14/07/13 19:12:02 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:10:56 PDT 2014
14/07/13 19:12:02 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:10:55 PDT 2014
14/07/13 19:12:02 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:10:57 PDT 2014
14/07/13 19:12:02 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:10:56 PDT 2014
14/07/13 19:12:02 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:10:56 PDT 2014
2014-07-13 19:12:10:921 1183 sec: 26739004 operations; 24416.76 current ops/sec; [INSERT AverageLatency(us)=1759.03] 
2014-07-13 19:12:20:922 1193 sec: 26975884 operations; 23688 current ops/sec; [INSERT AverageLatency(us)=1353.21] 
2014-07-13 19:12:30:922 1203 sec: 27499756 operations; 52381.96 current ops/sec; [INSERT AverageLatency(us)=291.25] 
2014-07-13 19:12:40:923 1213 sec: 27875436 operations; 37564.24 current ops/sec; [INSERT AverageLatency(us)=482.85] 
2014-07-13 19:12:50:923 1223 sec: 27875436 operations; 0 current ops/sec;  
2014-07-13 19:13:00:924 1233 sec: 27875436 operations; 0 current ops/sec;  
2014-07-13 19:13:10:924 1243 sec: 28298076 operations; 42264 current ops/sec; [INSERT AverageLatency(us)=1119.09] 
2014-07-13 19:13:20:925 1253 sec: 28298076 operations; 0 current ops/sec;  
2014-07-13 19:13:30:925 1263 sec: 28298076 operations; 0 current ops/sec;  
14/07/13 19:13:31 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2262 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=20818, waitTime=2726, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:12:38 PDT 2014, retrying after 10077 ms, replay 2262 ops.
14/07/13 19:13:31 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2247 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=20818, waitTime=2726, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:12:39 PDT 2014, retrying after 10032 ms, replay 2247 ops.
14/07/13 19:13:31 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2315 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=20818, waitTime=2726, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:12:38 PDT 2014, retrying after 10092 ms, replay 2315 ops.
14/07/13 19:13:31 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2303 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=20818, waitTime=2726, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:12:38 PDT 2014, retrying after 10099 ms, replay 2303 ops.
14/07/13 19:13:31 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2281 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=20818, waitTime=2726, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:12:39 PDT 2014, retrying after 10003 ms, replay 2281 ops.
2014-07-13 19:13:40:926 1273 sec: 28692540 operations; 39442.46 current ops/sec; [INSERT AverageLatency(us)=991.57] 
14/07/13 19:13:44 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2303 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=21046, waitTime=2637, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:12:38 PDT 2014, retrying after 10037 ms, replay 2303 ops.
14/07/13 19:13:44 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 2281 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=21046, waitTime=2637, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:12:39 PDT 2014, retrying after 10060 ms, replay 2281 ops.
14/07/13 19:13:44 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2262 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=21046, waitTime=2637, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:12:38 PDT 2014, retrying after 10022 ms, replay 2262 ops.
14/07/13 19:13:44 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2315 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=21046, waitTime=2637, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:12:38 PDT 2014, retrying after 10003 ms, replay 2315 ops.
14/07/13 19:13:44 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2247 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=21046, waitTime=2637, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:12:39 PDT 2014, retrying after 10093 ms, replay 2247 ops.
2014-07-13 19:13:51:021 1283 sec: 29073311 operations; 37718.77 current ops/sec; [INSERT AverageLatency(us)=662.52] 
14/07/13 19:13:55 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:12:38 PDT 2014
14/07/13 19:13:55 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:12:38 PDT 2014
14/07/13 19:13:55 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:12:39 PDT 2014
14/07/13 19:13:55 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:12:38 PDT 2014
14/07/13 19:13:55 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:12:39 PDT 2014
2014-07-13 19:14:01:021 1293 sec: 29604425 operations; 53111.4 current ops/sec; [INSERT AverageLatency(us)=986.6] 
2014-07-13 19:14:11:022 1303 sec: 29880628 operations; 27617.54 current ops/sec; [INSERT AverageLatency(us)=286.67] 
2014-07-13 19:14:21:022 1313 sec: 29880628 operations; 0 current ops/sec;  
2014-07-13 19:14:31:023 1323 sec: 29880628 operations; 0 current ops/sec;  
2014-07-13 19:14:41:023 1333 sec: 29880628 operations; 0 current ops/sec;  
2014-07-13 19:14:51:024 1343 sec: 30242220 operations; 36155.58 current ops/sec; [INSERT AverageLatency(us)=1063.73] 
2014-07-13 19:15:01:024 1353 sec: 30725908 operations; 48368.8 current ops/sec; [INSERT AverageLatency(us)=1459.09] 
2014-07-13 19:15:11:025 1363 sec: 30725908 operations; 0 current ops/sec;  
2014-07-13 19:15:21:025 1373 sec: 30725908 operations; 0 current ops/sec;  
2014-07-13 19:15:31:026 1383 sec: 30914698 operations; 18877.11 current ops/sec; [INSERT AverageLatency(us)=1009.84] 
2014-07-13 19:15:41:026 1393 sec: 31312908 operations; 39821 current ops/sec; [INSERT AverageLatency(us)=906.53] 
14/07/13 19:15:49 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2318 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=23219, waitTime=2057, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:14:55 PDT 2014, retrying after 10019 ms, replay 2318 ops.
14/07/13 19:15:49 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2287 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=23219, waitTime=2057, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:14:55 PDT 2014, retrying after 10040 ms, replay 2287 ops.
14/07/13 19:15:49 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2250 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=23219, waitTime=2057, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:14:58 PDT 2014, retrying after 10079 ms, replay 2250 ops.
14/07/13 19:15:49 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2278 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=23219, waitTime=2057, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:14:57 PDT 2014, retrying after 10079 ms, replay 2278 ops.
2014-07-13 19:15:51:027 1403 sec: 31862340 operations; 54937.71 current ops/sec; [INSERT AverageLatency(us)=513.52] 
14/07/13 19:16:00 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:14:57 PDT 2014
14/07/13 19:16:00 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:14:58 PDT 2014
14/07/13 19:16:00 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:14:55 PDT 2014
14/07/13 19:16:00 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:14:55 PDT 2014
2014-07-13 19:16:01:027 1413 sec: 32458867 operations; 59652.7 current ops/sec; [INSERT AverageLatency(us)=692.14] 
2014-07-13 19:16:11:028 1423 sec: 32978303 operations; 51938.41 current ops/sec; [INSERT AverageLatency(us)=335.07] 
2014-07-13 19:16:21:028 1433 sec: 33186612 operations; 20830.9 current ops/sec; [INSERT AverageLatency(us)=257.76] 
2014-07-13 19:16:31:029 1443 sec: 33186612 operations; 0 current ops/sec;  
2014-07-13 19:16:41:030 1453 sec: 33186612 operations; 0 current ops/sec;  
2014-07-13 19:16:51:030 1463 sec: 33242964 operations; 5634.64 current ops/sec; [INSERT AverageLatency(us)=1075.77] 
2014-07-13 19:17:01:031 1473 sec: 33242964 operations; 0 current ops/sec;  
14/07/13 19:17:03 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2255 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=24430, waitTime=2089, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:16:10 PDT 2014, retrying after 10013 ms, replay 2255 ops.
14/07/13 19:17:03 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2232 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=24430, waitTime=2089, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:16:10 PDT 2014, retrying after 10036 ms, replay 2232 ops.
14/07/13 19:17:03 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2212 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=24430, waitTime=2089, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:16:11 PDT 2014, retrying after 10090 ms, replay 2212 ops.
14/07/13 19:17:09 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2249 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=24482, waitTime=2064, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:16:13 PDT 2014, retrying after 10027 ms, replay 2249 ops.
14/07/13 19:17:09 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2249 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=24482, waitTime=2064, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:16:12 PDT 2014, retrying after 10055 ms, replay 2249 ops.
14/07/13 19:17:09 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2266 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=24482, waitTime=2064, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:16:12 PDT 2014, retrying after 10032 ms, replay 2266 ops.
14/07/13 19:17:09 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2304 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=24482, waitTime=2064, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:16:09 PDT 2014, retrying after 10005 ms, replay 2304 ops.
14/07/13 19:17:09 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2241 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=24482, waitTime=2064, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:16:13 PDT 2014, retrying after 10052 ms, replay 2241 ops.
2014-07-13 19:17:11:031 1483 sec: 33355668 operations; 11269.27 current ops/sec; [INSERT AverageLatency(us)=5893.67] 
14/07/13 19:17:14 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:16:10 PDT 2014
14/07/13 19:17:14 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:16:10 PDT 2014
14/07/13 19:17:14 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:16:11 PDT 2014
14/07/13 19:17:20 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:16:09 PDT 2014
14/07/13 19:17:20 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:16:13 PDT 2014
14/07/13 19:17:20 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:16:12 PDT 2014
14/07/13 19:17:20 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:16:12 PDT 2014
14/07/13 19:17:20 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:16:13 PDT 2014
2014-07-13 19:17:21:032 1493 sec: 33412020 operations; 5635.2 current ops/sec; [INSERT AverageLatency(us)=8170.15] 
2014-07-13 19:17:31:032 1503 sec: 33444892 operations; 3286.87 current ops/sec; [INSERT AverageLatency(us)=2241.25] 
2014-07-13 19:17:41:033 1513 sec: 33740740 operations; 29581.84 current ops/sec; [INSERT AverageLatency(us)=1216.21] 
2014-07-13 19:17:51:033 1523 sec: 33740740 operations; 0 current ops/sec;  
2014-07-13 19:18:01:034 1533 sec: 33797092 operations; 5634.64 current ops/sec; [INSERT AverageLatency(us)=4142.79] 
2014-07-13 19:18:11:034 1543 sec: 33905100 operations; 10800.8 current ops/sec; [INSERT AverageLatency(us)=414.63] 
2014-07-13 19:18:21:035 1553 sec: 34139900 operations; 23477.65 current ops/sec; [INSERT AverageLatency(us)=2248.92] 
2014-07-13 19:18:31:035 1563 sec: 34153988 operations; 1408.8 current ops/sec; [INSERT AverageLatency(us)=2298.66] 
2014-07-13 19:18:41:036 1573 sec: 34416964 operations; 26294.97 current ops/sec; [INSERT AverageLatency(us)=1513.88] 
2014-07-13 19:18:51:037 1583 sec: 34740988 operations; 32402.4 current ops/sec; [INSERT AverageLatency(us)=736.6] 
2014-07-13 19:19:01:037 1593 sec: 35079100 operations; 33807.82 current ops/sec; [INSERT AverageLatency(us)=575.46] 
2014-07-13 19:19:11:038 1603 sec: 35412516 operations; 33338.27 current ops/sec; [INSERT AverageLatency(us)=728.88] 
2014-07-13 19:19:21:040 1613 sec: 35925022 operations; 51245.48 current ops/sec; [INSERT AverageLatency(us)=346.96] 
2014-07-13 19:19:31:040 1623 sec: 36383129 operations; 45806.12 current ops/sec; [INSERT AverageLatency(us)=436.9] 
2014-07-13 19:19:41:040 1633 sec: 36830880 operations; 44775.1 current ops/sec; [INSERT AverageLatency(us)=443.65] 
2014-07-13 19:19:51:041 1643 sec: 37262024 operations; 43110.09 current ops/sec; [INSERT AverageLatency(us)=387.59] 
2014-07-13 19:20:01:041 1653 sec: 37741732 operations; 47970.8 current ops/sec; [INSERT AverageLatency(us)=488.26] 
2014-07-13 19:20:11:042 1663 sec: 38173764 operations; 43198.88 current ops/sec; [INSERT AverageLatency(us)=364.52] 
2014-07-13 19:20:21:042 1673 sec: 38272380 operations; 9861.6 current ops/sec; [INSERT AverageLatency(us)=1159.69] 
2014-07-13 19:20:31:043 1683 sec: 38648060 operations; 37564.24 current ops/sec; [INSERT AverageLatency(us)=771.51] 
2014-07-13 19:20:41:043 1693 sec: 39042524 operations; 39446.4 current ops/sec; [INSERT AverageLatency(us)=389.55] 
2014-07-13 19:20:51:044 1703 sec: 39042524 operations; 0 current ops/sec;  
2014-07-13 19:21:01:044 1713 sec: 39272628 operations; 23010.4 current ops/sec; [INSERT AverageLatency(us)=1982.84] 
2014-07-13 19:21:11:044 1723 sec: 39817638 operations; 54501 current ops/sec; [INSERT AverageLatency(us)=350.42] 
2014-07-13 19:21:21:045 1733 sec: 39920676 operations; 10302.77 current ops/sec; [INSERT AverageLatency(us)=414.49] 
2014-07-13 19:21:31:045 1743 sec: 39920676 operations; 0 current ops/sec;  
2014-07-13 19:21:41:046 1753 sec: 39920676 operations; 0 current ops/sec;  
2014-07-13 19:21:51:046 1763 sec: 39920676 operations; 0 current ops/sec;  
2014-07-13 19:22:01:046 1773 sec: 39920676 operations; 0 current ops/sec;  
14/07/13 19:22:06 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2257 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:21:09 PDT 2014, retrying after 10087 ms, replay 2257 ops.
14/07/13 19:22:08 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2266 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=28004, waitTime=2753, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:21:10 PDT 2014, retrying after 10074 ms, replay 2266 ops.
14/07/13 19:22:08 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2254 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=28004, waitTime=2753, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:21:10 PDT 2014, retrying after 10078 ms, replay 2254 ops.
14/07/13 19:22:08 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2251 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=28004, waitTime=2753, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:21:09 PDT 2014, retrying after 10092 ms, replay 2251 ops.
14/07/13 19:22:08 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2280 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=28004, waitTime=2753, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:21:10 PDT 2014, retrying after 10076 ms, replay 2280 ops.
14/07/13 19:22:08 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2259 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=28004, waitTime=2753, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:21:10 PDT 2014, retrying after 10078 ms, replay 2259 ops.
14/07/13 19:22:08 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2324 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=28004, waitTime=2753, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:21:12 PDT 2014, retrying after 10021 ms, replay 2324 ops.
14/07/13 19:22:08 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2235 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=28004, waitTime=2753, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:21:10 PDT 2014, retrying after 10014 ms, replay 2235 ops.
2014-07-13 19:22:11:047 1783 sec: 39965668 operations; 4498.75 current ops/sec; [INSERT AverageLatency(us)=7809.7] 
14/07/13 19:22:11 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2221 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=28019, waitTime=2237, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:21:11 PDT 2014, retrying after 10047 ms, replay 2221 ops.
14/07/13 19:22:12 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2285 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=28032, waitTime=2161, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:21:13 PDT 2014, retrying after 10040 ms, replay 2285 ops.
14/07/13 19:22:12 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2225 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=28032, waitTime=2161, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:21:13 PDT 2014, retrying after 10051 ms, replay 2225 ops.
14/07/13 19:22:17 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:21:09 PDT 2014
14/07/13 19:22:20 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:21:10 PDT 2014
14/07/13 19:22:20 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:21:10 PDT 2014
14/07/13 19:22:20 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:21:10 PDT 2014
14/07/13 19:22:20 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:21:12 PDT 2014
14/07/13 19:22:20 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:21:10 PDT 2014
14/07/13 19:22:20 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:21:10 PDT 2014
14/07/13 19:22:20 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2251 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=28264, waitTime=2186, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:21:09 PDT 2014, retrying after 10090 ms, replay 2251 ops.
2014-07-13 19:22:21:047 1793 sec: 40531156 operations; 56548.8 current ops/sec; [INSERT AverageLatency(us)=1294.87] 
14/07/13 19:22:22 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:21:11 PDT 2014
14/07/13 19:22:23 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:21:13 PDT 2014
14/07/13 19:22:23 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:21:13 PDT 2014
2014-07-13 19:22:31:048 1803 sec: 40888052 operations; 35686.03 current ops/sec; [INSERT AverageLatency(us)=862.66] 
14/07/13 19:22:34 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 failed 2251 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:21:09 PDT 2014, retrying after 20092 ms, replay 2251 ops.
2014-07-13 19:22:41:048 1813 sec: 40888052 operations; 0 current ops/sec;  
2014-07-13 19:22:51:049 1823 sec: 41122852 operations; 23480 current ops/sec; [INSERT AverageLatency(us)=998.58] 
14/07/13 19:22:55 INFO client.AsyncProcess: #3, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:21:09 PDT 2014
2014-07-13 19:23:01:049 1833 sec: 41301300 operations; 17843.02 current ops/sec; [INSERT AverageLatency(us)=1762.02] 
2014-07-13 19:23:11:049 1843 sec: 41301300 operations; 0 current ops/sec;  
2014-07-13 19:23:21:050 1853 sec: 41301300 operations; 0 current ops/sec;  
14/07/13 19:23:22 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2308 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:26 PDT 2014, retrying after 10043 ms, replay 2308 ops.
14/07/13 19:23:22 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2228 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:28 PDT 2014, retrying after 10063 ms, replay 2228 ops.
14/07/13 19:23:22 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2424 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:26 PDT 2014, retrying after 10079 ms, replay 2424 ops.
14/07/13 19:23:22 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2166 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:26 PDT 2014, retrying after 10058 ms, replay 2166 ops.
14/07/13 19:23:22 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2253 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:27 PDT 2014, retrying after 10082 ms, replay 2253 ops.
2014-07-13 19:23:31:050 1863 sec: 41301300 operations; 0 current ops/sec;  
14/07/13 19:23:36 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2308 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29207, waitTime=3231, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:26 PDT 2014, retrying after 10072 ms, replay 2308 ops.
14/07/13 19:23:36 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2424 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29207, waitTime=3231, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:26 PDT 2014, retrying after 10083 ms, replay 2424 ops.
14/07/13 19:23:36 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2166 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29207, waitTime=3231, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:26 PDT 2014, retrying after 10097 ms, replay 2166 ops.
14/07/13 19:23:36 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2253 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29207, waitTime=3231, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:27 PDT 2014, retrying after 10072 ms, replay 2253 ops.
14/07/13 19:23:36 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2228 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29207, waitTime=3231, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:28 PDT 2014, retrying after 10078 ms, replay 2228 ops.
2014-07-13 19:23:41:051 1873 sec: 41374782 operations; 7347.47 current ops/sec; [INSERT AverageLatency(us)=2646.24] 
14/07/13 19:23:47 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:26 PDT 2014
14/07/13 19:23:48 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2319 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29366, waitTime=2382, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:56 PDT 2014, retrying after 10075 ms, replay 2319 ops.
14/07/13 19:23:48 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2259 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29366, waitTime=2382, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:55 PDT 2014, retrying after 10037 ms, replay 2259 ops.
14/07/13 19:23:48 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 2302 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29366, waitTime=2382, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:55 PDT 2014, retrying after 10093 ms, replay 2302 ops.
14/07/13 19:23:48 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 2253 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29366, waitTime=2382, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:27 PDT 2014, retrying after 20111 ms, replay 2253 ops.
14/07/13 19:23:48 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2283 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29366, waitTime=2382, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:55 PDT 2014, retrying after 10068 ms, replay 2283 ops.
14/07/13 19:23:48 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2308 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29366, waitTime=2382, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:26 PDT 2014, retrying after 20171 ms, replay 2308 ops.
14/07/13 19:23:48 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2285 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29366, waitTime=2382, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:54 PDT 2014, retrying after 10034 ms, replay 2285 ops.
14/07/13 19:23:48 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 failed 2424 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29366, waitTime=2382, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:26 PDT 2014, retrying after 20043 ms, replay 2424 ops.
14/07/13 19:23:48 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:28 PDT 2014
14/07/13 19:23:48 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2241 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29366, waitTime=2382, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:55 PDT 2014, retrying after 10028 ms, replay 2241 ops.
14/07/13 19:23:48 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2246 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29366, waitTime=2382, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:54 PDT 2014, retrying after 10097 ms, replay 2246 ops.
14/07/13 19:23:48 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2175 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29366, waitTime=2382, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:55 PDT 2014, retrying after 10071 ms, replay 2175 ops.
14/07/13 19:23:48 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2260 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29387, waitTime=2013, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:56 PDT 2014, retrying after 10073 ms, replay 2260 ops.
14/07/13 19:23:49 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2256 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29392, waitTime=2154, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:56 PDT 2014, retrying after 10013 ms, replay 2256 ops.
2014-07-13 19:23:51:051 1883 sec: 41644108 operations; 26932.6 current ops/sec; [INSERT AverageLatency(us)=979.16] 
2014-07-13 19:24:01:052 1893 sec: 41954044 operations; 30993.6 current ops/sec; [INSERT AverageLatency(us)=270.9] 
14/07/13 19:24:01 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2246 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29588, waitTime=3014, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:54 PDT 2014, retrying after 10053 ms, replay 2246 ops.
14/07/13 19:24:01 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2241 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29588, waitTime=3014, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:55 PDT 2014, retrying after 10036 ms, replay 2241 ops.
14/07/13 19:24:01 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2285 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29588, waitTime=3014, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:54 PDT 2014, retrying after 10050 ms, replay 2285 ops.
14/07/13 19:24:01 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2283 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29588, waitTime=3014, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:55 PDT 2014, retrying after 10004 ms, replay 2283 ops.
14/07/13 19:24:01 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2175 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29588, waitTime=3014, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:55 PDT 2014, retrying after 10006 ms, replay 2175 ops.
14/07/13 19:24:01 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2259 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29588, waitTime=3014, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:55 PDT 2014, retrying after 10021 ms, replay 2259 ops.
14/07/13 19:24:01 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2256 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29588, waitTime=3014, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:56 PDT 2014, retrying after 10074 ms, replay 2256 ops.
14/07/13 19:24:01 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 2302 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29588, waitTime=3014, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:55 PDT 2014, retrying after 10055 ms, replay 2302 ops.
14/07/13 19:24:01 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 2260 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29588, waitTime=3014, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:56 PDT 2014, retrying after 10050 ms, replay 2260 ops.
14/07/13 19:24:01 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 2319 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29588, waitTime=3014, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:56 PDT 2014, retrying after 10035 ms, replay 2319 ops.
14/07/13 19:24:09 INFO client.AsyncProcess: #13, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:26 PDT 2014
14/07/13 19:24:09 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:26 PDT 2014
14/07/13 19:24:09 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:27 PDT 2014
2014-07-13 19:24:11:094 1903 sec: 42322442 operations; 36682.07 current ops/sec; [INSERT AverageLatency(us)=1094.19] 
14/07/13 19:24:13 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 failed 2259 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29814, waitTime=2543, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:55 PDT 2014, retrying after 20163 ms, replay 2259 ops.
14/07/13 19:24:13 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 failed 2260 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29814, waitTime=2543, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:56 PDT 2014, retrying after 20040 ms, replay 2260 ops.
14/07/13 19:24:13 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:55 PDT 2014
14/07/13 19:24:13 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 failed 2319 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29814, waitTime=2543, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:56 PDT 2014, retrying after 20101 ms, replay 2319 ops.
14/07/13 19:24:13 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 2241 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29814, waitTime=2543, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:55 PDT 2014, retrying after 20136 ms, replay 2241 ops.
14/07/13 19:24:13 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 2246 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29814, waitTime=2543, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:54 PDT 2014, retrying after 20179 ms, replay 2246 ops.
14/07/13 19:24:13 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 failed 2285 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29814, waitTime=2543, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:54 PDT 2014, retrying after 20015 ms, replay 2285 ops.
14/07/13 19:24:13 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 failed 2302 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29814, waitTime=2543, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:55 PDT 2014, retrying after 20094 ms, replay 2302 ops.
14/07/13 19:24:13 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 2283 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29814, waitTime=2543, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:55 PDT 2014, retrying after 20126 ms, replay 2283 ops.
14/07/13 19:24:13 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2256 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=29814, waitTime=2543, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:56 PDT 2014, retrying after 20194 ms, replay 2256 ops.
2014-07-13 19:24:21:095 1913 sec: 42587335 operations; 26486.65 current ops/sec; [INSERT AverageLatency(us)=600.34] 
2014-07-13 19:24:31:095 1923 sec: 42982468 operations; 39513.3 current ops/sec; [INSERT AverageLatency(us)=377.81] 
14/07/13 19:24:36 INFO client.AsyncProcess: #5, table=usertable, attempt=13/35 failed 2260 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:56 PDT 2014, retrying after 20007 ms, replay 2260 ops.
14/07/13 19:24:36 INFO client.AsyncProcess: #12, table=usertable, attempt=13/35 failed 2319 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:56 PDT 2014, retrying after 20110 ms, replay 2319 ops.
14/07/13 19:24:36 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 failed 2283 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:55 PDT 2014, retrying after 20056 ms, replay 2283 ops.
14/07/13 19:24:36 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 failed 2241 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:55 PDT 2014, retrying after 20174 ms, replay 2241 ops.
14/07/13 19:24:36 INFO client.AsyncProcess: #3, table=usertable, attempt=13/35 failed 2259 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:55 PDT 2014, retrying after 20114 ms, replay 2259 ops.
14/07/13 19:24:36 INFO client.AsyncProcess: #18, table=usertable, attempt=13/35 failed 2285 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:54 PDT 2014, retrying after 20050 ms, replay 2285 ops.
14/07/13 19:24:36 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 failed 2246 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:54 PDT 2014, retrying after 20013 ms, replay 2246 ops.
14/07/13 19:24:36 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 failed 2256 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:56 PDT 2014, retrying after 20111 ms, replay 2256 ops.
14/07/13 19:24:36 INFO client.AsyncProcess: #7, table=usertable, attempt=13/35 failed 2302 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:55 PDT 2014, retrying after 20135 ms, replay 2302 ops.
2014-07-13 19:24:41:096 1933 sec: 43066996 operations; 8451.95 current ops/sec; [INSERT AverageLatency(us)=239.06] 
2014-07-13 19:24:51:096 1943 sec: 43066996 operations; 0 current ops/sec;  
14/07/13 19:24:58 INFO client.AsyncProcess: #20, table=usertable, attempt=14/35 failed 2246 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=30378, waitTime=2103, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:54 PDT 2014, retrying after 20154 ms, replay 2246 ops.
14/07/13 19:24:58 INFO client.AsyncProcess: #5, table=usertable, attempt=14/35 failed 2260 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=30378, waitTime=2103, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:56 PDT 2014, retrying after 20079 ms, replay 2260 ops.
14/07/13 19:24:58 INFO client.AsyncProcess: #18, table=usertable, attempt=14/35 failed 2285 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=30391, waitTime=2000, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:54 PDT 2014, retrying after 20024 ms, replay 2285 ops.
14/07/13 19:24:58 INFO client.AsyncProcess: #9, table=usertable, attempt=14/35 failed 2283 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=30392, waitTime=2007, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:55 PDT 2014, retrying after 20074 ms, replay 2283 ops.
14/07/13 19:24:58 INFO client.AsyncProcess: #3, table=usertable, attempt=14/35 failed 2259 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=30393, waitTime=2099, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:55 PDT 2014, retrying after 20053 ms, replay 2259 ops.
14/07/13 19:24:58 INFO client.AsyncProcess: #20, table=usertable, attempt=14/35 failed 2241 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=30393, waitTime=2099, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:55 PDT 2014, retrying after 20022 ms, replay 2241 ops.
14/07/13 19:24:58 INFO client.AsyncProcess: #7, table=usertable, attempt=14/35 failed 2302 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=30393, waitTime=2099, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:55 PDT 2014, retrying after 20055 ms, replay 2302 ops.
14/07/13 19:24:58 INFO client.AsyncProcess: #15, table=usertable, attempt=14/35 failed 2256 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=30393, waitTime=2099, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:56 PDT 2014, retrying after 20019 ms, replay 2256 ops.
14/07/13 19:24:58 INFO client.AsyncProcess: #12, table=usertable, attempt=14/35 failed 2319 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=30393, waitTime=2099, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:56 PDT 2014, retrying after 20044 ms, replay 2319 ops.
2014-07-13 19:25:01:097 1953 sec: 43066996 operations; 0 current ops/sec;  
2014-07-13 19:25:11:097 1963 sec: 43151524 operations; 8451.95 current ops/sec; [INSERT AverageLatency(us)=1163.87] 
14/07/13 19:25:19 INFO client.AsyncProcess: #18, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:54 PDT 2014
14/07/13 19:25:19 INFO client.AsyncProcess: #5, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:56 PDT 2014
14/07/13 19:25:19 INFO client.AsyncProcess: #20, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:54 PDT 2014
14/07/13 19:25:19 INFO client.AsyncProcess: #9, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:55 PDT 2014
14/07/13 19:25:19 INFO client.AsyncProcess: #15, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:56 PDT 2014
14/07/13 19:25:19 INFO client.AsyncProcess: #20, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:55 PDT 2014
14/07/13 19:25:19 INFO client.AsyncProcess: #3, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:55 PDT 2014
14/07/13 19:25:19 INFO client.AsyncProcess: #12, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:56 PDT 2014
14/07/13 19:25:19 INFO client.AsyncProcess: #7, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:22:55 PDT 2014
2014-07-13 19:25:21:097 1973 sec: 43395716 operations; 24419.2 current ops/sec; [INSERT AverageLatency(us)=6502.24] 
2014-07-13 19:25:31:098 1983 sec: 43945148 operations; 54937.71 current ops/sec; [INSERT AverageLatency(us)=428.33] 
2014-07-13 19:25:41:098 1993 sec: 44510935 operations; 56578.7 current ops/sec; [INSERT AverageLatency(us)=342.44] 
2014-07-13 19:25:51:099 2003 sec: 44982110 operations; 47112.79 current ops/sec; [INSERT AverageLatency(us)=429.92] 
2014-07-13 19:26:01:099 2013 sec: 45499050 operations; 51694 current ops/sec; [UPDATE AverageLatency(us)=4200102] [INSERT AverageLatency(us)=364.23] [CLEANUP AverageLatency(us)=4200277] 
2014-07-13 19:26:11:100 2023 sec: 45609261 operations; 11020 current ops/sec;  [INSERT AverageLatency(us)=245.57]  
2014-07-13 19:26:21:100 2033 sec: 45609261 operations; 0 current ops/sec;    
2014-07-13 19:26:31:101 2043 sec: 45609261 operations; 0 current ops/sec;    
2014-07-13 19:26:41:101 2053 sec: 45609261 operations; 0 current ops/sec;    
2014-07-13 19:26:51:101 2063 sec: 45609261 operations; 0 current ops/sec;    
14/07/13 19:26:54 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2285 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32075, waitTime=2105, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014, retrying after 10001 ms, replay 2285 ops.
14/07/13 19:26:54 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2253 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32075, waitTime=2105, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:58 PDT 2014, retrying after 10042 ms, replay 2253 ops.
14/07/13 19:26:54 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2271 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32075, waitTime=2105, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:58 PDT 2014, retrying after 10035 ms, replay 2271 ops.
14/07/13 19:26:55 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2302 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32078, waitTime=2006, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:58 PDT 2014, retrying after 10036 ms, replay 2302 ops.
14/07/13 19:26:55 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2269 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32078, waitTime=2006, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014, retrying after 10065 ms, replay 2269 ops.
14/07/13 19:26:56 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2215 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32080, waitTime=3075, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:58 PDT 2014, retrying after 10042 ms, replay 2215 ops.
14/07/13 19:26:56 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2291 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32080, waitTime=3075, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014, retrying after 10025 ms, replay 2291 ops.
14/07/13 19:26:56 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2204 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32080, waitTime=3075, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:58 PDT 2014, retrying after 10008 ms, replay 2204 ops.
14/07/13 19:26:58 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2229 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 10079 ms, replay 2229 ops.
14/07/13 19:26:58 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2281 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014, retrying after 10048 ms, replay 2281 ops.
14/07/13 19:26:58 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2188 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014, retrying after 10062 ms, replay 2188 ops.
14/07/13 19:26:58 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2236 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 10075 ms, replay 2236 ops.
14/07/13 19:26:58 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2281 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014, retrying after 10032 ms, replay 2281 ops.
14/07/13 19:26:58 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2303 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:00 PDT 2014, retrying after 10080 ms, replay 2303 ops.
14/07/13 19:26:58 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2283 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 10008 ms, replay 2283 ops.
14/07/13 19:26:58 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2257 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:00 PDT 2014, retrying after 10093 ms, replay 2257 ops.
14/07/13 19:26:58 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2226 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014, retrying after 10015 ms, replay 2226 ops.
14/07/13 19:26:58 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2314 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014, retrying after 10019 ms, replay 2314 ops.
14/07/13 19:26:58 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2140 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 10077 ms, replay 2140 ops.
14/07/13 19:26:58 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2242 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 10090 ms, replay 2242 ops.
14/07/13 19:26:58 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2300 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014, retrying after 10012 ms, replay 2300 ops.
14/07/13 19:26:58 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2175 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:00 PDT 2014, retrying after 10081 ms, replay 2175 ops.
14/07/13 19:26:58 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 2262 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014, retrying after 10015 ms, replay 2262 ops.
14/07/13 19:26:58 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2275 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:00 PDT 2014, retrying after 10086 ms, replay 2275 ops.
14/07/13 19:26:58 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2352 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 10028 ms, replay 2352 ops.
14/07/13 19:27:00 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2240 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 10073 ms, replay 2240 ops.
14/07/13 19:27:00 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2302 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 10005 ms, replay 2302 ops.
14/07/13 19:27:00 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2281 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 10088 ms, replay 2281 ops.
14/07/13 19:27:00 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2223 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 10075 ms, replay 2223 ops.
14/07/13 19:27:00 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2291 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 10089 ms, replay 2291 ops.
14/07/13 19:27:00 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2286 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 10054 ms, replay 2286 ops.
14/07/13 19:27:00 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2340 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 10046 ms, replay 2340 ops.
14/07/13 19:27:00 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2273 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 10065 ms, replay 2273 ops.
14/07/13 19:27:00 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2311 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 10097 ms, replay 2311 ops.
14/07/13 19:27:00 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2280 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 10046 ms, replay 2280 ops.
14/07/13 19:27:00 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2244 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 10098 ms, replay 2244 ops.
14/07/13 19:27:00 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2307 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 10059 ms, replay 2307 ops.
14/07/13 19:27:00 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2260 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 10082 ms, replay 2260 ops.
14/07/13 19:27:00 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2232 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 10003 ms, replay 2232 ops.
14/07/13 19:27:00 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2215 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 10089 ms, replay 2215 ops.
14/07/13 19:27:00 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2233 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 10031 ms, replay 2233 ops.
14/07/13 19:27:00 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2252 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 10050 ms, replay 2252 ops.
2014-07-13 19:27:01:102 2073 sec: 45609261 operations; 0 current ops/sec;    
14/07/13 19:27:02 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2260 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 10060 ms, replay 2260 ops.
14/07/13 19:27:02 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2236 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 10070 ms, replay 2236 ops.
14/07/13 19:27:02 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2241 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 10092 ms, replay 2241 ops.
14/07/13 19:27:02 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2257 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:04 PDT 2014, retrying after 10095 ms, replay 2257 ops.
14/07/13 19:27:02 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2237 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:04 PDT 2014, retrying after 10096 ms, replay 2237 ops.
14/07/13 19:27:06 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2271 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32130, waitTime=2148, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:58 PDT 2014, retrying after 10020 ms, replay 2271 ops.
14/07/13 19:27:06 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2285 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32130, waitTime=2148, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014, retrying after 10054 ms, replay 2285 ops.
14/07/13 19:27:06 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2253 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32130, waitTime=2148, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:58 PDT 2014, retrying after 10020 ms, replay 2253 ops.
14/07/13 19:27:07 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 2269 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32133, waitTime=2444, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014, retrying after 10084 ms, replay 2269 ops.
14/07/13 19:27:07 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2302 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32133, waitTime=2444, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:58 PDT 2014, retrying after 10065 ms, replay 2302 ops.
14/07/13 19:27:08 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2204 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32135, waitTime=2172, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:58 PDT 2014, retrying after 10027 ms, replay 2204 ops.
14/07/13 19:27:08 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2291 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32135, waitTime=2172, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014, retrying after 10024 ms, replay 2291 ops.
14/07/13 19:27:08 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 2215 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32135, waitTime=2172, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:58 PDT 2014, retrying after 10075 ms, replay 2215 ops.
2014-07-13 19:27:11:102 2083 sec: 45609261 operations; 0 current ops/sec;    
14/07/13 19:27:11 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2236 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32140, waitTime=2491, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 10037 ms, replay 2236 ops.
14/07/13 19:27:11 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 2257 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32140, waitTime=2491, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:00 PDT 2014, retrying after 10082 ms, replay 2257 ops.
14/07/13 19:27:11 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2281 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32140, waitTime=2491, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014, retrying after 10011 ms, replay 2281 ops.
14/07/13 19:27:11 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2229 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32140, waitTime=2491, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 10097 ms, replay 2229 ops.
14/07/13 19:27:11 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 2352 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32140, waitTime=2491, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 10036 ms, replay 2352 ops.
14/07/13 19:27:11 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2242 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32140, waitTime=2491, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 10083 ms, replay 2242 ops.
14/07/13 19:27:11 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2281 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32140, waitTime=2491, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014, retrying after 10020 ms, replay 2281 ops.
14/07/13 19:27:11 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 2188 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32140, waitTime=2491, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014, retrying after 10088 ms, replay 2188 ops.
14/07/13 19:27:11 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2303 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32140, waitTime=2491, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:00 PDT 2014, retrying after 10024 ms, replay 2303 ops.
14/07/13 19:27:11 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2140 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32140, waitTime=2491, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 10092 ms, replay 2140 ops.
14/07/13 19:27:11 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2226 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32140, waitTime=2491, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014, retrying after 10053 ms, replay 2226 ops.
14/07/13 19:27:11 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2275 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32140, waitTime=2491, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:00 PDT 2014, retrying after 10098 ms, replay 2275 ops.
14/07/13 19:27:11 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2283 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32140, waitTime=2491, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 10094 ms, replay 2283 ops.
14/07/13 19:27:11 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2314 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32140, waitTime=2491, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014, retrying after 10066 ms, replay 2314 ops.
14/07/13 19:27:11 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 2175 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32140, waitTime=2491, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:00 PDT 2014, retrying after 10076 ms, replay 2175 ops.
14/07/13 19:27:11 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2300 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32140, waitTime=2491, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014, retrying after 10023 ms, replay 2300 ops.
14/07/13 19:27:11 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 2262 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32140, waitTime=2491, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014, retrying after 10071 ms, replay 2262 ops.
14/07/13 19:27:13 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 2273 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32157, waitTime=2628, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 10024 ms, replay 2273 ops.
14/07/13 19:27:13 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2311 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32157, waitTime=2628, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 10069 ms, replay 2311 ops.
14/07/13 19:27:13 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2260 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32157, waitTime=2628, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 10064 ms, replay 2260 ops.
14/07/13 19:27:13 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 2286 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32157, waitTime=2628, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 10072 ms, replay 2286 ops.
14/07/13 19:27:13 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 2223 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32157, waitTime=2628, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 10067 ms, replay 2223 ops.
14/07/13 19:27:13 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2281 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32157, waitTime=2628, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 10013 ms, replay 2281 ops.
14/07/13 19:27:13 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2302 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32157, waitTime=2628, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 10073 ms, replay 2302 ops.
14/07/13 19:27:13 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2232 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32157, waitTime=2628, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 10039 ms, replay 2232 ops.
14/07/13 19:27:13 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2252 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32157, waitTime=2628, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 10069 ms, replay 2252 ops.
14/07/13 19:27:13 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2280 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32157, waitTime=2628, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 10014 ms, replay 2280 ops.
14/07/13 19:27:13 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2233 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32157, waitTime=2628, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 10084 ms, replay 2233 ops.
14/07/13 19:27:13 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2215 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32157, waitTime=2628, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 10008 ms, replay 2215 ops.
14/07/13 19:27:13 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2244 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32157, waitTime=2628, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 10052 ms, replay 2244 ops.
14/07/13 19:27:13 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2240 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32157, waitTime=2628, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 10071 ms, replay 2240 ops.
14/07/13 19:27:13 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2340 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32157, waitTime=2628, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 10078 ms, replay 2340 ops.
14/07/13 19:27:13 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2307 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32157, waitTime=2628, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 10045 ms, replay 2307 ops.
14/07/13 19:27:13 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2291 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32157, waitTime=2628, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 10017 ms, replay 2291 ops.
14/07/13 19:27:15 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2236 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32176, waitTime=2620, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 10085 ms, replay 2236 ops.
14/07/13 19:27:15 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2257 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32176, waitTime=2620, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:04 PDT 2014, retrying after 10023 ms, replay 2257 ops.
14/07/13 19:27:15 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2241 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32176, waitTime=2620, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 10027 ms, replay 2241 ops.
14/07/13 19:27:15 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2237 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32176, waitTime=2620, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:04 PDT 2014, retrying after 10013 ms, replay 2237 ops.
14/07/13 19:27:15 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2260 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32176, waitTime=2620, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 10001 ms, replay 2260 ops.
14/07/13 19:27:17 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:58 PDT 2014
14/07/13 19:27:17 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:58 PDT 2014
14/07/13 19:27:17 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014
14/07/13 19:27:18 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:58 PDT 2014
14/07/13 19:27:18 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014
14/07/13 19:27:19 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:58 PDT 2014
14/07/13 19:27:19 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014
14/07/13 19:27:19 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:58 PDT 2014
2014-07-13 19:27:21:103 2093 sec: 45706897 operations; 9762.62 current ops/sec;  [INSERT AverageLatency(us)=2505.72]  
14/07/13 19:27:21 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014
14/07/13 19:27:22 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014
14/07/13 19:27:22 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014
14/07/13 19:27:22 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014
14/07/13 19:27:22 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014
14/07/13 19:27:23 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014
14/07/13 19:27:23 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014
14/07/13 19:27:23 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014
14/07/13 19:27:23 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:00 PDT 2014
14/07/13 19:27:23 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:00 PDT 2014
14/07/13 19:27:23 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014
14/07/13 19:27:23 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014
14/07/13 19:27:23 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:25:59 PDT 2014
14/07/13 19:27:23 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 failed 2257 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32250, waitTime=2156, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:00 PDT 2014, retrying after 20067 ms, replay 2257 ops.
14/07/13 19:27:23 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014
14/07/13 19:27:23 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 2175 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32250, waitTime=2156, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:00 PDT 2014, retrying after 20019 ms, replay 2175 ops.
14/07/13 19:27:23 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2242 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32250, waitTime=2156, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 20143 ms, replay 2242 ops.
14/07/13 19:27:25 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014
14/07/13 19:27:25 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014
14/07/13 19:27:25 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014
14/07/13 19:27:25 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014
14/07/13 19:27:25 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 failed 2281 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32294, waitTime=2007, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 20198 ms, replay 2281 ops.
14/07/13 19:27:25 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 2280 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32294, waitTime=2007, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 20146 ms, replay 2280 ops.
14/07/13 19:27:25 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 2215 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32294, waitTime=2007, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 20170 ms, replay 2215 ops.
14/07/13 19:27:25 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 failed 2273 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32297, waitTime=2005, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 20005 ms, replay 2273 ops.
14/07/13 19:27:25 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014
14/07/13 19:27:25 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 failed 2291 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32297, waitTime=2005, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 20117 ms, replay 2291 ops.
14/07/13 19:27:25 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014
14/07/13 19:27:25 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 failed 2244 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32299, waitTime=2022, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 20161 ms, replay 2244 ops.
14/07/13 19:27:25 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014
14/07/13 19:27:25 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 failed 2232 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32299, waitTime=2022, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 20140 ms, replay 2232 ops.
14/07/13 19:27:25 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2260 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32302, waitTime=2012, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 20015 ms, replay 2260 ops.
14/07/13 19:27:25 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014
14/07/13 19:27:25 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2233 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32310, waitTime=2047, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 20030 ms, replay 2233 ops.
14/07/13 19:27:28 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 2241 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32331, waitTime=3155, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 20134 ms, replay 2241 ops.
14/07/13 19:27:28 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2236 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32331, waitTime=3155, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 20164 ms, replay 2236 ops.
14/07/13 19:27:28 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 2257 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32331, waitTime=3155, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:04 PDT 2014, retrying after 20197 ms, replay 2257 ops.
14/07/13 19:27:28 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 failed 2260 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32331, waitTime=3155, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 20052 ms, replay 2260 ops.
14/07/13 19:27:28 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2237 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32331, waitTime=3155, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:04 PDT 2014, retrying after 20142 ms, replay 2237 ops.
2014-07-13 19:27:31:103 2103 sec: 45970853 operations; 26395.6 current ops/sec;  [INSERT AverageLatency(us)=2502.23]  
2014-07-13 19:27:41:103 2113 sec: 46537704 operations; 56685.1 current ops/sec;  [INSERT AverageLatency(us)=168.04]  
14/07/13 19:27:45 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014
14/07/13 19:27:45 INFO client.AsyncProcess: #5, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:00 PDT 2014
14/07/13 19:27:45 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:00 PDT 2014
14/07/13 19:27:47 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 failed 2215 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 20058 ms, replay 2215 ops.
14/07/13 19:27:47 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 failed 2260 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 20046 ms, replay 2260 ops.
14/07/13 19:27:47 INFO client.AsyncProcess: #8, table=usertable, attempt=13/35 failed 2273 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 20113 ms, replay 2273 ops.
14/07/13 19:27:47 INFO client.AsyncProcess: #16, table=usertable, attempt=13/35 failed 2291 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 20161 ms, replay 2291 ops.
14/07/13 19:27:47 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 failed 2233 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 20070 ms, replay 2233 ops.
14/07/13 19:27:47 INFO client.AsyncProcess: #18, table=usertable, attempt=13/35 failed 2281 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 20193 ms, replay 2281 ops.
14/07/13 19:27:47 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 failed 2280 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 20125 ms, replay 2280 ops.
14/07/13 19:27:47 INFO client.AsyncProcess: #17, table=usertable, attempt=13/35 failed 2232 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 20012 ms, replay 2232 ops.
14/07/13 19:27:47 INFO client.AsyncProcess: #16, table=usertable, attempt=13/35 failed 2244 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 20122 ms, replay 2244 ops.
2014-07-13 19:27:51:104 2123 sec: 46769173 operations; 23144.59 current ops/sec;  [INSERT AverageLatency(us)=1049.3]  
14/07/13 19:27:51 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 failed 2241 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 20065 ms, replay 2241 ops.
14/07/13 19:27:51 INFO client.AsyncProcess: #18, table=usertable, attempt=13/35 failed 2260 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 20026 ms, replay 2260 ops.
14/07/13 19:27:51 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 failed 2236 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 20086 ms, replay 2236 ops.
14/07/13 19:27:51 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 failed 2237 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:04 PDT 2014, retrying after 20126 ms, replay 2237 ops.
14/07/13 19:27:51 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 failed 2257 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:04 PDT 2014, retrying after 20141 ms, replay 2257 ops.
2014-07-13 19:28:01:117 2133 sec: 46769173 operations; 0 current ops/sec;    
14/07/13 19:28:09 INFO client.AsyncProcess: #2, table=usertable, attempt=14/35 failed 2260 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32926, waitTime=2033, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 20138 ms, replay 2260 ops.
14/07/13 19:28:09 INFO client.AsyncProcess: #17, table=usertable, attempt=14/35 failed 2232 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32926, waitTime=2033, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 20100 ms, replay 2232 ops.
14/07/13 19:28:09 INFO client.AsyncProcess: #15, table=usertable, attempt=14/35 failed 2233 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32926, waitTime=2033, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 20028 ms, replay 2233 ops.
14/07/13 19:28:09 INFO client.AsyncProcess: #6, table=usertable, attempt=14/35 failed 2215 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32926, waitTime=2033, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014, retrying after 20009 ms, replay 2215 ops.
14/07/13 19:28:10 INFO client.AsyncProcess: #8, table=usertable, attempt=14/35 failed 2273 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32930, waitTime=2102, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 20126 ms, replay 2273 ops.
14/07/13 19:28:10 INFO client.AsyncProcess: #16, table=usertable, attempt=14/35 failed 2291 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32930, waitTime=2102, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 20128 ms, replay 2291 ops.
14/07/13 19:28:10 INFO client.AsyncProcess: #18, table=usertable, attempt=14/35 failed 2281 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32930, waitTime=2102, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 20061 ms, replay 2281 ops.
14/07/13 19:28:10 INFO client.AsyncProcess: #16, table=usertable, attempt=14/35 failed 2244 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32930, waitTime=2102, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 20094 ms, replay 2244 ops.
14/07/13 19:28:10 INFO client.AsyncProcess: #6, table=usertable, attempt=14/35 failed 2280 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32930, waitTime=2102, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014, retrying after 20083 ms, replay 2280 ops.
2014-07-13 19:28:11:117 2143 sec: 46769173 operations; 0 current ops/sec;    
14/07/13 19:28:14 INFO client.AsyncProcess: #6, table=usertable, attempt=14/35 failed 2241 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32952, waitTime=2390, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 20086 ms, replay 2241 ops.
14/07/13 19:28:14 INFO client.AsyncProcess: #15, table=usertable, attempt=14/35 failed 2236 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32952, waitTime=2390, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 20147 ms, replay 2236 ops.
14/07/13 19:28:14 INFO client.AsyncProcess: #18, table=usertable, attempt=14/35 failed 2260 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32952, waitTime=2390, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 20113 ms, replay 2260 ops.
14/07/13 19:28:14 INFO client.AsyncProcess: #15, table=usertable, attempt=14/35 failed 2237 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32952, waitTime=2390, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:04 PDT 2014, retrying after 20042 ms, replay 2237 ops.
14/07/13 19:28:14 INFO client.AsyncProcess: #6, table=usertable, attempt=14/35 failed 2257 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=32952, waitTime=2390, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:04 PDT 2014, retrying after 20106 ms, replay 2257 ops.
2014-07-13 19:28:21:117 2153 sec: 47145344 operations; 37617.1 current ops/sec; [UPDATE AverageLatency(us)=1849529] [INSERT AverageLatency(us)=1043.92] [CLEANUP AverageLatency(us)=1850170] 
14/07/13 19:28:30 INFO client.AsyncProcess: #15, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014
14/07/13 19:28:30 INFO client.AsyncProcess: #6, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014
14/07/13 19:28:30 INFO client.AsyncProcess: #2, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:01 PDT 2014
2014-07-13 19:28:31:118 2163 sec: 47654104 operations; 50870.91 current ops/sec; [UPDATE AverageLatency(us)=1105355.4] [INSERT AverageLatency(us)=507.34] [CLEANUP AverageLatency(us)=1105367.4] 
14/07/13 19:28:31 INFO client.AsyncProcess: #17, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014
14/07/13 19:28:31 INFO client.AsyncProcess: #16, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014
14/07/13 19:28:32 INFO client.AsyncProcess: #6, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014
14/07/13 19:28:32 INFO client.AsyncProcess: #8, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014
14/07/13 19:28:32 INFO client.AsyncProcess: #16, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014
14/07/13 19:28:32 INFO client.AsyncProcess: #18, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:02 PDT 2014
14/07/13 19:28:35 INFO client.AsyncProcess: #18, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014
14/07/13 19:28:35 INFO client.AsyncProcess: #6, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:04 PDT 2014
14/07/13 19:28:36 INFO client.AsyncProcess: #15, table=usertable, attempt=15/35 failed 2236 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=33439, waitTime=2863, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 20069 ms, replay 2236 ops.
14/07/13 19:28:36 INFO client.AsyncProcess: #15, table=usertable, attempt=15/35 failed 2237 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=33439, waitTime=2863, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:04 PDT 2014, retrying after 20158 ms, replay 2237 ops.
14/07/13 19:28:36 INFO client.AsyncProcess: #6, table=usertable, attempt=15/35 failed 2241 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=33439, waitTime=2863, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 20194 ms, replay 2241 ops.
2014-07-13 19:28:41:118 2173 sec: 48055435 operations; 40133.1 current ops/sec; [UPDATE AverageLatency(us)=4282920] [INSERT AverageLatency(us)=1724.7] [CLEANUP AverageLatency(us)=4282931] 
2014-07-13 19:28:51:120 2183 sec: 48640060 operations; 58450.81 current ops/sec; [UPDATE AverageLatency(us)=1595283] [INSERT AverageLatency(us)=140.62] [CLEANUP AverageLatency(us)=1595297] 
14/07/13 19:29:00 INFO client.AsyncProcess: #15, table=usertable, attempt=16/35 failed 2237 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:04 PDT 2014, retrying after 20093 ms, replay 2237 ops.
14/07/13 19:29:00 INFO client.AsyncProcess: #6, table=usertable, attempt=16/35 failed 2241 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 20142 ms, replay 2241 ops.
14/07/13 19:29:00 INFO client.AsyncProcess: #15, table=usertable, attempt=16/35 failed 2236 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:47241 remote=slave1/9.1.143.59:60020] on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 20080 ms, replay 2236 ops.
2014-07-13 19:29:01:120 2193 sec: 48674255 operations; 3419.5 current ops/sec;  [INSERT AverageLatency(us)=71.9]  
14/07/13 19:29:02 INFO client.AsyncProcess: #19, waiting for some tasks to finish. Expected max=0, tasksSent=1502, tasksDone=1498, currentTasksDone=1498, retries=438 hasError=false, tableName=usertable
2014-07-13 19:29:11:121 2203 sec: 48674255 operations; 0 current ops/sec;    
14/07/13 19:29:14 INFO client.AsyncProcess: #19, waiting for some tasks to finish. Expected max=0, tasksSent=1513, tasksDone=1509, currentTasksDone=1509, retries=447 hasError=false, tableName=usertable
2014-07-13 19:29:21:121 2213 sec: 48674255 operations; 0 current ops/sec;    
14/07/13 19:29:22 INFO client.AsyncProcess: #15, table=usertable, attempt=17/35 failed 2236 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=34023, waitTime=2258, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 20160 ms, replay 2236 ops.
14/07/13 19:29:22 INFO client.AsyncProcess: #15, table=usertable, attempt=17/35 failed 2237 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=34023, waitTime=2258, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:04 PDT 2014, retrying after 20160 ms, replay 2237 ops.
14/07/13 19:29:22 INFO client.AsyncProcess: #6, table=usertable, attempt=17/35 failed 2241 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=34023, waitTime=2258, rpcTimetout=2000 on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014, retrying after 20111 ms, replay 2241 ops.
2014-07-13 19:29:31:122 2223 sec: 48674255 operations; 0 current ops/sec;    
14/07/13 19:29:32 INFO client.AsyncProcess: #19, waiting for some tasks to finish. Expected max=0, tasksSent=1521, tasksDone=1517, currentTasksDone=1517, retries=455 hasError=false, tableName=usertable
2014-07-13 19:29:41:122 2233 sec: 49070448 operations; 39619.3 current ops/sec; [UPDATE AverageLatency(us)=22657342.5] [INSERT AverageLatency(us)=871.67] [CLEANUP AverageLatency(us)=22657355] 
14/07/13 19:29:43 INFO client.AsyncProcess: #15, table=usertable, attempt=18/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:04 PDT 2014
14/07/13 19:29:43 INFO client.AsyncProcess: #15, table=usertable, attempt=18/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014
14/07/13 19:29:43 INFO client.AsyncProcess: #6, table=usertable, attempt=18/35 SUCCEEDED on slave1,60020,1405330807068, tracking started Sun Jul 13 19:26:03 PDT 2014
2014-07-13 19:29:51:123 2243 sec: 49589228 operations; 51872.81 current ops/sec; [UPDATE AverageLatency(us)=1087452] [INSERT AverageLatency(us)=946.27] [CLEANUP AverageLatency(us)=1087464.67] 
2014-07-13 19:30:01:124 2253 sec: 49860358 operations; 27110.29 current ops/sec; [UPDATE AverageLatency(us)=847856] [INSERT AverageLatency(us)=90.53] [CLEANUP AverageLatency(us)=847868.33] 
2014-07-13 19:30:08:731 2260 sec: 50000000 operations; 18357.04 current ops/sec; [UPDATE AverageLatency(us)=650655] [INSERT AverageLatency(us)=68.67] [CLEANUP AverageLatency(us)=650666] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1405305009
1405305009
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ false
+ false
+ false
+ false
+ false
+ false
+ false
+ false
+ let counter=1+1
+ read line
+ set +x
