++ ls caseresult/ -ltr
++ wc -l
+ filename=case30
+ mkdir caseresult/case30
+ RESULT_DIR=/home/hadoop/git/physical_design/caseresult/case30
+ TEN=10
+ SIXTY=60
+ SLEEP_TIME=300
+ YCSB_DIR=/home/hadoop/ycsb-0.1.4
+ number_of_operations=5000000
+ number_of_threads=20
+ number_of_records=5000000
+ output_file_suffix=.dat
+ experiment_list_file=/home/hadoop/git/physical_design/case30.list
+ clean=false
+ create=false
+ load=false
+ random_read=false
+ scan=false
+ all=false
+ for i in '$@'
+ '[' all == all ']'
+ all=true
+ let counter=1
+ cd /home/hadoop/ycsb-0.1.4
++ pwd
+ echo /home/hadoop/ycsb-0.1.4
/home/hadoop/ycsb-0.1.4
+ read line
+ true
+ echo 'sleeping for 60 ...'
sleeping for 60 ...
+ sleep 60
+ echo 'droping usertable...'
droping usertable...
+ hbase shell /home/hadoop/git/physical_design/delete_table
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/hadoop/hbase-0.98.3-hadoop1/lib/slf4j-log4j12-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/hadoop/hadoop-1.2.1/lib/slf4j-log4j12-1.4.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
0 row(s) in 3.3700 seconds

0 row(s) in 0.7680 seconds

0 row(s) in 0.0600 seconds

+ echo 'sleeping for 300 ...'
sleeping for 300 ...
+ sleep 300
+ true
+ echo 'creating usertable...'
creating usertable...
+ create_statement='create '\''usertable'\'', { NAME=>'\''family'\'', CONFIGURATION =>  { '\''hbase.hstore.compaction.min'\'' => '\''3'\'', '\''hbase.hregion.majorcompaction'\'' => '\''0'\'' } }, SPLITS => ['\''user1'\'', '\''user2'\'', '\''user3'\'', '\''user4'\'', '\''user5'\'', '\''user6'\'', '\''user7'\'', '\''user8'\'', '\''user9'\'']'
+ echo create ''\''usertable'\'',' '{' 'NAME=>'\''family'\'',' CONFIGURATION '=>' '{' ''\''hbase.hstore.compaction.min'\''' '=>' ''\''3'\'',' ''\''hbase.hregion.majorcompaction'\''' '=>' ''\''0'\''' '}' '},' SPLITS '=>' '['\''user1'\'',' ''\''user2'\'',' ''\''user3'\'',' ''\''user4'\'',' ''\''user5'\'',' ''\''user6'\'',' ''\''user7'\'',' ''\''user8'\'',' ''\''user9'\'']'
+ echo 'exit '
+ create_table /home/hadoop/git/physical_design/caseresult/case30/create_1.script
+ echo 'creating table...'
creating table...
+ echo /home/hadoop/git/physical_design/caseresult/case30/create_1.script
/home/hadoop/git/physical_design/caseresult/case30/create_1.script
+ hbase shell /home/hadoop/git/physical_design/caseresult/case30/create_1.script
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/hadoop/hbase-0.98.3-hadoop1/lib/slf4j-log4j12-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/hadoop/hadoop-1.2.1/lib/slf4j-log4j12-1.4.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
0 row(s) in 2.0220 seconds

+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo 'loading data...'
loading data...
+ echo 'starting time: '
starting time: 
++ date +%s
+ echo 1404807390
1404807390
++ echo /home/hadoop/git/physical_design/caseresult/case30/load_1.dat
+ ./ld 5000000 20 /home/hadoop/git/physical_design/caseresult/case30/load_1.dat
Loading workload...
Starting test.
2014-07-08 01:16:31:455 0 sec: 0 operations; 
14/07/08 01:16:31 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/08 01:16:31 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/08 01:16:31 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/08 01:16:31 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/08 01:16:31 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/08 01:16:31 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/08 01:16:31 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/08 01:16:31 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/08 01:16:31 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/08 01:16:31 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/08 01:16:31 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/08 01:16:31 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/08 01:16:31 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/08 01:16:31 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/08 01:16:31 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/08 01:16:31 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x21415036, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/08 01:16:31 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x21415036 connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/08 01:16:31 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/08 01:16:31 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/08 01:16:31 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x1471505bcde000b, negotiated timeout = 90000
2014-07-08 01:16:41:457 10 sec: 258260 operations; 25820.84 current ops/sec; [INSERT AverageLatency(us)=395.72] 
2014-07-08 01:16:51:459 20 sec: 258260 operations; 0 current ops/sec;  
2014-07-08 01:17:01:460 30 sec: 258260 operations; 0 current ops/sec;  
2014-07-08 01:17:11:461 40 sec: 258260 operations; 0 current ops/sec;  
2014-07-08 01:17:21:462 50 sec: 258260 operations; 0 current ops/sec;  
2014-07-08 01:17:31:462 60 sec: 258260 operations; 0 current ops/sec;  
14/07/08 01:17:33 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2819 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=396, waitTime=2165, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10034 ms, replay 2819 ops.
14/07/08 01:17:33 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2832 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=396, waitTime=2165, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10004 ms, replay 2832 ops.
14/07/08 01:17:33 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2814 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=396, waitTime=2165, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 10033 ms, replay 2814 ops.
14/07/08 01:17:33 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2826 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=396, waitTime=2165, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10097 ms, replay 2826 ops.
14/07/08 01:17:33 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2861 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=396, waitTime=2165, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 10076 ms, replay 2861 ops.
14/07/08 01:17:33 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2868 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=396, waitTime=2165, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 10063 ms, replay 2868 ops.
14/07/08 01:17:33 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2879 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=396, waitTime=2165, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10081 ms, replay 2879 ops.
14/07/08 01:17:33 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2825 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=396, waitTime=2165, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 10068 ms, replay 2825 ops.
14/07/08 01:17:33 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2799 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=396, waitTime=2165, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10063 ms, replay 2799 ops.
14/07/08 01:17:33 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2849 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=396, waitTime=2165, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 10055 ms, replay 2849 ops.
14/07/08 01:17:33 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 2813 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=396, waitTime=2165, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10079 ms, replay 2813 ops.
14/07/08 01:17:33 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 2841 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=396, waitTime=2165, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 10091 ms, replay 2841 ops.
14/07/08 01:17:33 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2810 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=396, waitTime=2165, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10056 ms, replay 2810 ops.
14/07/08 01:17:33 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2839 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=396, waitTime=2165, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10076 ms, replay 2839 ops.
14/07/08 01:17:33 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2848 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=396, waitTime=2165, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10006 ms, replay 2848 ops.
14/07/08 01:17:33 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2806 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=396, waitTime=2165, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 10053 ms, replay 2806 ops.
14/07/08 01:17:33 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2810 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=396, waitTime=2165, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10041 ms, replay 2810 ops.
14/07/08 01:17:33 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2802 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=396, waitTime=2165, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10014 ms, replay 2802 ops.
14/07/08 01:17:33 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2791 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=396, waitTime=2165, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10011 ms, replay 2791 ops.
14/07/08 01:17:33 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2847 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=396, waitTime=2165, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10044 ms, replay 2847 ops.
14/07/08 01:17:33 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2857 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=396, waitTime=2165, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10079 ms, replay 2857 ops.
14/07/08 01:17:33 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2843 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=396, waitTime=2165, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10096 ms, replay 2843 ops.
14/07/08 01:17:33 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2831 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=396, waitTime=2165, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10084 ms, replay 2831 ops.
14/07/08 01:17:33 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2819 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=396, waitTime=2165, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10083 ms, replay 2819 ops.
14/07/08 01:17:34 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2816 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=420, waitTime=2093, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10080 ms, replay 2816 ops.
14/07/08 01:17:34 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2820 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=420, waitTime=2093, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10050 ms, replay 2820 ops.
14/07/08 01:17:34 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2850 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=420, waitTime=2093, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10064 ms, replay 2850 ops.
14/07/08 01:17:34 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2821 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=420, waitTime=2093, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 10046 ms, replay 2821 ops.
14/07/08 01:17:34 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2862 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=420, waitTime=2093, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:38 PDT 2014, retrying after 10065 ms, replay 2862 ops.
14/07/08 01:17:38 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 2840 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=427, waitTime=2265, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:40 PDT 2014, retrying after 10074 ms, replay 2840 ops.
14/07/08 01:17:38 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2813 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=427, waitTime=2265, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:40 PDT 2014, retrying after 10031 ms, replay 2813 ops.
14/07/08 01:17:38 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2904 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=427, waitTime=2265, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:40 PDT 2014, retrying after 10023 ms, replay 2904 ops.
14/07/08 01:17:38 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2806 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=427, waitTime=2265, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 10013 ms, replay 2806 ops.
14/07/08 01:17:38 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 2820 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=427, waitTime=2265, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:40 PDT 2014, retrying after 10005 ms, replay 2820 ops.
14/07/08 01:17:38 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2834 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=427, waitTime=2265, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:40 PDT 2014, retrying after 10042 ms, replay 2834 ops.
2014-07-08 01:17:41:463 70 sec: 258260 operations; 0 current ops/sec;  
14/07/08 01:17:46 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2802 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:59676 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10026 ms, replay 2802 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2791 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:59676 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10056 ms, replay 2791 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2832 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:59676 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10071 ms, replay 2832 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2848 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:59676 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10020 ms, replay 2848 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2819 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=439, waitTime=2156, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10075 ms, replay 2819 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2799 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=439, waitTime=2156, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10064 ms, replay 2799 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 2847 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=439, waitTime=2156, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10029 ms, replay 2847 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2819 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=439, waitTime=2156, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10049 ms, replay 2819 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 2816 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=439, waitTime=2156, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10035 ms, replay 2816 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2868 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=439, waitTime=2156, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 10046 ms, replay 2868 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2839 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=439, waitTime=2156, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10076 ms, replay 2839 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2831 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=439, waitTime=2156, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10073 ms, replay 2831 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 2813 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=439, waitTime=2156, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10056 ms, replay 2813 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 2879 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=439, waitTime=2156, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10058 ms, replay 2879 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2861 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=439, waitTime=2156, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 10079 ms, replay 2861 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2810 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=439, waitTime=2156, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10011 ms, replay 2810 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2814 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=439, waitTime=2156, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 10012 ms, replay 2814 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 2810 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=439, waitTime=2156, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10073 ms, replay 2810 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2843 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=439, waitTime=2156, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10017 ms, replay 2843 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2857 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=439, waitTime=2156, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10085 ms, replay 2857 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2849 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=439, waitTime=2156, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 10023 ms, replay 2849 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2820 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=439, waitTime=2156, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10039 ms, replay 2820 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 2821 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=439, waitTime=2156, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 10097 ms, replay 2821 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 2841 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=439, waitTime=2156, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 10094 ms, replay 2841 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 2826 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=439, waitTime=2156, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10041 ms, replay 2826 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 2806 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=439, waitTime=2156, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 10028 ms, replay 2806 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2850 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=439, waitTime=2156, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 10054 ms, replay 2850 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2862 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=439, waitTime=2156, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:38 PDT 2014, retrying after 10033 ms, replay 2862 ops.
14/07/08 01:17:46 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2825 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=439, waitTime=2156, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 10071 ms, replay 2825 ops.
14/07/08 01:17:48 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:40 PDT 2014
14/07/08 01:17:48 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:40 PDT 2014
14/07/08 01:17:49 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:40 PDT 2014
14/07/08 01:17:49 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:40 PDT 2014
14/07/08 01:17:49 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014
14/07/08 01:17:49 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:40 PDT 2014
2014-07-08 01:17:51:463 80 sec: 258260 operations; 0 current ops/sec;  
14/07/08 01:17:57 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014
14/07/08 01:17:58 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014
14/07/08 01:17:58 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014
14/07/08 01:17:58 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014
14/07/08 01:17:58 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 2826 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=476, waitTime=2036, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20140 ms, replay 2826 ops.
14/07/08 01:17:58 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 2849 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=476, waitTime=2036, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20095 ms, replay 2849 ops.
14/07/08 01:17:58 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 2820 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=476, waitTime=2036, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20142 ms, replay 2820 ops.
14/07/08 01:17:58 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 2814 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=476, waitTime=2036, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20178 ms, replay 2814 ops.
14/07/08 01:17:58 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 failed 2810 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=476, waitTime=2036, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20187 ms, replay 2810 ops.
14/07/08 01:17:58 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 2816 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=476, waitTime=2036, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20042 ms, replay 2816 ops.
14/07/08 01:17:58 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 failed 2806 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=476, waitTime=2036, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20182 ms, replay 2806 ops.
14/07/08 01:17:58 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 failed 2847 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=476, waitTime=2036, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20174 ms, replay 2847 ops.
14/07/08 01:17:58 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 2862 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=476, waitTime=2036, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:38 PDT 2014, retrying after 20022 ms, replay 2862 ops.
14/07/08 01:17:58 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 2843 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=476, waitTime=2036, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20131 ms, replay 2843 ops.
14/07/08 01:17:58 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 failed 2868 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=486, waitTime=2619, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20091 ms, replay 2868 ops.
14/07/08 01:17:58 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 2861 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=486, waitTime=2619, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20061 ms, replay 2861 ops.
14/07/08 01:17:58 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 failed 2799 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=486, waitTime=2619, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20197 ms, replay 2799 ops.
14/07/08 01:17:58 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 2819 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=486, waitTime=2619, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20113 ms, replay 2819 ops.
14/07/08 01:17:58 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 failed 2813 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=486, waitTime=2619, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20065 ms, replay 2813 ops.
14/07/08 01:17:58 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 failed 2857 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=486, waitTime=2619, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20113 ms, replay 2857 ops.
14/07/08 01:17:58 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 failed 2850 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=486, waitTime=2619, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20020 ms, replay 2850 ops.
14/07/08 01:17:58 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 failed 2841 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=486, waitTime=2619, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20187 ms, replay 2841 ops.
14/07/08 01:17:58 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2839 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=486, waitTime=2619, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20055 ms, replay 2839 ops.
14/07/08 01:17:58 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2831 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=486, waitTime=2619, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20086 ms, replay 2831 ops.
14/07/08 01:17:58 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 failed 2821 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=486, waitTime=2619, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20160 ms, replay 2821 ops.
14/07/08 01:17:58 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 failed 2879 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=486, waitTime=2619, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20096 ms, replay 2879 ops.
14/07/08 01:17:58 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 2819 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=486, waitTime=2619, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20189 ms, replay 2819 ops.
14/07/08 01:17:58 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 failed 2810 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=486, waitTime=2619, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20034 ms, replay 2810 ops.
14/07/08 01:17:58 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 2825 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=486, waitTime=2619, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20033 ms, replay 2825 ops.
2014-07-08 01:18:01:464 90 sec: 333396 operations; 7512.85 current ops/sec; [INSERT AverageLatency(us)=3414.16] 
2014-07-08 01:18:11:467 100 sec: 616006 operations; 28252.52 current ops/sec; [INSERT AverageLatency(us)=103.78] 
14/07/08 01:18:20 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 failed 2814 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=747, waitTime=2356, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20039 ms, replay 2814 ops.
14/07/08 01:18:20 INFO client.AsyncProcess: #5, table=usertable, attempt=13/35 failed 2806 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=747, waitTime=2356, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20136 ms, replay 2806 ops.
14/07/08 01:18:20 INFO client.AsyncProcess: #18, table=usertable, attempt=13/35 failed 2810 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=747, waitTime=2356, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20064 ms, replay 2810 ops.
14/07/08 01:18:20 INFO client.AsyncProcess: #12, table=usertable, attempt=13/35 failed 2847 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=747, waitTime=2356, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20173 ms, replay 2847 ops.
14/07/08 01:18:20 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 failed 2849 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=747, waitTime=2356, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20042 ms, replay 2849 ops.
14/07/08 01:18:20 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 failed 2826 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=747, waitTime=2356, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20055 ms, replay 2826 ops.
14/07/08 01:18:20 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 failed 2816 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=747, waitTime=2356, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20105 ms, replay 2816 ops.
14/07/08 01:18:20 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 failed 2820 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=747, waitTime=2356, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20176 ms, replay 2820 ops.
14/07/08 01:18:20 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 failed 2862 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=747, waitTime=2356, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:38 PDT 2014, retrying after 20023 ms, replay 2862 ops.
14/07/08 01:18:20 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 failed 2843 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=747, waitTime=2356, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20166 ms, replay 2843 ops.
14/07/08 01:18:21 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 failed 2839 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=760, waitTime=2151, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20193 ms, replay 2839 ops.
14/07/08 01:18:21 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 failed 2825 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=760, waitTime=2151, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20000 ms, replay 2825 ops.
14/07/08 01:18:21 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 failed 2861 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=760, waitTime=2151, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20043 ms, replay 2861 ops.
14/07/08 01:18:21 INFO client.AsyncProcess: #13, table=usertable, attempt=13/35 failed 2857 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=760, waitTime=2151, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20180 ms, replay 2857 ops.
14/07/08 01:18:21 INFO client.AsyncProcess: #18, table=usertable, attempt=13/35 failed 2868 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=760, waitTime=2151, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20192 ms, replay 2868 ops.
14/07/08 01:18:21 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 failed 2819 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=760, waitTime=2151, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20014 ms, replay 2819 ops.
14/07/08 01:18:21 INFO client.AsyncProcess: #5, table=usertable, attempt=13/35 failed 2810 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=760, waitTime=2151, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20180 ms, replay 2810 ops.
14/07/08 01:18:21 INFO client.AsyncProcess: #14, table=usertable, attempt=13/35 failed 2850 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=760, waitTime=2151, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20067 ms, replay 2850 ops.
14/07/08 01:18:21 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 failed 2831 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=760, waitTime=2151, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20141 ms, replay 2831 ops.
14/07/08 01:18:21 INFO client.AsyncProcess: #8, table=usertable, attempt=13/35 failed 2879 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=760, waitTime=2151, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20165 ms, replay 2879 ops.
14/07/08 01:18:21 INFO client.AsyncProcess: #12, table=usertable, attempt=13/35 failed 2821 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=760, waitTime=2151, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20036 ms, replay 2821 ops.
14/07/08 01:18:21 INFO client.AsyncProcess: #7, table=usertable, attempt=13/35 failed 2813 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=760, waitTime=2151, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20118 ms, replay 2813 ops.
14/07/08 01:18:21 INFO client.AsyncProcess: #16, table=usertable, attempt=13/35 failed 2799 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=772, waitTime=2199, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20074 ms, replay 2799 ops.
14/07/08 01:18:21 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 failed 2819 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=772, waitTime=2199, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20021 ms, replay 2819 ops.
14/07/08 01:18:21 INFO client.AsyncProcess: #7, table=usertable, attempt=13/35 failed 2841 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=772, waitTime=2199, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20180 ms, replay 2841 ops.
2014-07-08 01:18:21:468 110 sec: 845260 operations; 22923.11 current ops/sec; [INSERT AverageLatency(us)=106.8] 
2014-07-08 01:18:31:469 120 sec: 980087 operations; 13481.35 current ops/sec; [UPDATE AverageLatency(us)=837195.33] [INSERT AverageLatency(us)=167.89] [CLEANUP AverageLatency(us)=837545.67] 
2014-07-08 01:18:41:470 130 sec: 980087 operations; 0 current ops/sec;    
14/07/08 01:18:42 INFO client.AsyncProcess: #20, table=usertable, attempt=14/35 failed 2862 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:59959 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:38 PDT 2014, retrying after 20171 ms, replay 2862 ops.
14/07/08 01:18:42 INFO client.AsyncProcess: #18, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014
14/07/08 01:18:42 INFO client.AsyncProcess: #11, table=usertable, attempt=14/35 failed 2814 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=861, waitTime=2255, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20002 ms, replay 2814 ops.
14/07/08 01:18:42 INFO client.AsyncProcess: #10, table=usertable, attempt=14/35 failed 2849 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=861, waitTime=2255, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20082 ms, replay 2849 ops.
14/07/08 01:18:42 INFO client.AsyncProcess: #12, table=usertable, attempt=14/35 failed 2847 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=861, waitTime=2255, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20172 ms, replay 2847 ops.
14/07/08 01:18:42 INFO client.AsyncProcess: #5, table=usertable, attempt=14/35 failed 2806 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=861, waitTime=2255, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20005 ms, replay 2806 ops.
14/07/08 01:18:42 INFO client.AsyncProcess: #1, table=usertable, attempt=14/35 failed 2826 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=861, waitTime=2255, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20166 ms, replay 2826 ops.
14/07/08 01:18:42 INFO client.AsyncProcess: #10, table=usertable, attempt=14/35 failed 2843 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=861, waitTime=2255, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20022 ms, replay 2843 ops.
14/07/08 01:18:42 INFO client.AsyncProcess: #20, table=usertable, attempt=14/35 failed 2820 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=861, waitTime=2255, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20013 ms, replay 2820 ops.
14/07/08 01:18:42 INFO client.AsyncProcess: #4, table=usertable, attempt=14/35 failed 2816 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=861, waitTime=2255, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20063 ms, replay 2816 ops.
14/07/08 01:18:43 INFO client.AsyncProcess: #20, table=usertable, attempt=14/35 failed 2825 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=870, waitTime=2213, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20096 ms, replay 2825 ops.
14/07/08 01:18:43 INFO client.AsyncProcess: #12, table=usertable, attempt=14/35 failed 2821 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=870, waitTime=2213, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20124 ms, replay 2821 ops.
14/07/08 01:18:43 INFO client.AsyncProcess: #7, table=usertable, attempt=14/35 failed 2813 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=870, waitTime=2213, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20142 ms, replay 2813 ops.
14/07/08 01:18:43 INFO client.AsyncProcess: #13, table=usertable, attempt=14/35 failed 2857 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=870, waitTime=2213, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20108 ms, replay 2857 ops.
14/07/08 01:18:43 INFO client.AsyncProcess: #8, table=usertable, attempt=14/35 failed 2879 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=870, waitTime=2213, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20103 ms, replay 2879 ops.
14/07/08 01:18:43 INFO client.AsyncProcess: #18, table=usertable, attempt=14/35 failed 2868 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=870, waitTime=2213, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20117 ms, replay 2868 ops.
14/07/08 01:18:43 INFO client.AsyncProcess: #5, table=usertable, attempt=14/35 failed 2810 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=870, waitTime=2213, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20007 ms, replay 2810 ops.
14/07/08 01:18:43 INFO client.AsyncProcess: #9, table=usertable, attempt=14/35 failed 2861 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=870, waitTime=2213, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20167 ms, replay 2861 ops.
14/07/08 01:18:43 INFO client.AsyncProcess: #2, table=usertable, attempt=14/35 failed 2831 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=870, waitTime=2213, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20121 ms, replay 2831 ops.
14/07/08 01:18:43 INFO client.AsyncProcess: #14, table=usertable, attempt=14/35 failed 2850 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=870, waitTime=2213, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20140 ms, replay 2850 ops.
14/07/08 01:18:43 INFO client.AsyncProcess: #15, table=usertable, attempt=14/35 failed 2839 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=870, waitTime=2213, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20104 ms, replay 2839 ops.
14/07/08 01:18:43 INFO client.AsyncProcess: #9, table=usertable, attempt=14/35 failed 2819 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=870, waitTime=2213, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20105 ms, replay 2819 ops.
14/07/08 01:18:43 INFO client.AsyncProcess: #16, table=usertable, attempt=14/35 failed 2799 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=882, waitTime=2126, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20020 ms, replay 2799 ops.
14/07/08 01:18:43 INFO client.AsyncProcess: #6, table=usertable, attempt=14/35 failed 2819 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=882, waitTime=2126, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20136 ms, replay 2819 ops.
14/07/08 01:18:43 INFO client.AsyncProcess: #7, table=usertable, attempt=14/35 failed 2841 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=884, waitTime=2082, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20196 ms, replay 2841 ops.
2014-07-08 01:18:51:471 140 sec: 980087 operations; 0 current ops/sec;    
2014-07-08 01:19:01:471 150 sec: 980087 operations; 0 current ops/sec;    
14/07/08 01:19:04 INFO client.AsyncProcess: #11, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014
14/07/08 01:19:04 INFO client.AsyncProcess: #20, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:38 PDT 2014
14/07/08 01:19:04 INFO client.AsyncProcess: #5, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014
14/07/08 01:19:04 INFO client.AsyncProcess: #20, table=usertable, attempt=15/35 failed 2820 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=892, waitTime=2041, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20031 ms, replay 2820 ops.
14/07/08 01:19:04 INFO client.AsyncProcess: #10, table=usertable, attempt=15/35 failed 2843 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=892, waitTime=2041, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20179 ms, replay 2843 ops.
14/07/08 01:19:04 INFO client.AsyncProcess: #4, table=usertable, attempt=15/35 failed 2816 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=894, waitTime=2033, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20144 ms, replay 2816 ops.
14/07/08 01:19:04 INFO client.AsyncProcess: #10, table=usertable, attempt=15/35 failed 2849 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=894, waitTime=2033, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20044 ms, replay 2849 ops.
14/07/08 01:19:05 INFO client.AsyncProcess: #1, table=usertable, attempt=15/35 failed 2826 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=896, waitTime=2036, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20125 ms, replay 2826 ops.
14/07/08 01:19:05 INFO client.AsyncProcess: #12, table=usertable, attempt=15/35 failed 2847 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=896, waitTime=2036, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20068 ms, replay 2847 ops.
14/07/08 01:19:05 INFO client.AsyncProcess: #14, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014
14/07/08 01:19:05 INFO client.AsyncProcess: #5, table=usertable, attempt=15/35 failed 2810 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=898, waitTime=2212, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20006 ms, replay 2810 ops.
14/07/08 01:19:05 INFO client.AsyncProcess: #15, table=usertable, attempt=15/35 failed 2839 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=898, waitTime=2212, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20152 ms, replay 2839 ops.
14/07/08 01:19:05 INFO client.AsyncProcess: #2, table=usertable, attempt=15/35 failed 2831 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=898, waitTime=2212, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20119 ms, replay 2831 ops.
14/07/08 01:19:05 INFO client.AsyncProcess: #9, table=usertable, attempt=15/35 failed 2819 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=898, waitTime=2212, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20021 ms, replay 2819 ops.
14/07/08 01:19:05 INFO client.AsyncProcess: #12, table=usertable, attempt=15/35 failed 2821 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=898, waitTime=2212, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20063 ms, replay 2821 ops.
14/07/08 01:19:05 INFO client.AsyncProcess: #8, table=usertable, attempt=15/35 failed 2879 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=898, waitTime=2212, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20085 ms, replay 2879 ops.
14/07/08 01:19:05 INFO client.AsyncProcess: #9, table=usertable, attempt=15/35 failed 2861 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=898, waitTime=2212, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20137 ms, replay 2861 ops.
14/07/08 01:19:05 INFO client.AsyncProcess: #18, table=usertable, attempt=15/35 failed 2868 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=898, waitTime=2212, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20062 ms, replay 2868 ops.
14/07/08 01:19:05 INFO client.AsyncProcess: #7, table=usertable, attempt=15/35 failed 2813 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=898, waitTime=2212, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20101 ms, replay 2813 ops.
14/07/08 01:19:05 INFO client.AsyncProcess: #20, table=usertable, attempt=15/35 failed 2825 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=898, waitTime=2212, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20028 ms, replay 2825 ops.
14/07/08 01:19:05 INFO client.AsyncProcess: #13, table=usertable, attempt=15/35 failed 2857 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=898, waitTime=2212, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20074 ms, replay 2857 ops.
14/07/08 01:19:05 INFO client.AsyncProcess: #16, table=usertable, attempt=15/35 failed 2799 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=898, waitTime=2212, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20194 ms, replay 2799 ops.
14/07/08 01:19:05 INFO client.AsyncProcess: #6, table=usertable, attempt=15/35 failed 2819 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=911, waitTime=2039, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20171 ms, replay 2819 ops.
14/07/08 01:19:05 INFO client.AsyncProcess: #7, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014
2014-07-08 01:19:11:473 160 sec: 1135055 operations; 15493.7 current ops/sec;  [INSERT AverageLatency(us)=1982.97]  
2014-07-08 01:19:21:493 170 sec: 1366206 operations; 23068.96 current ops/sec;  [INSERT AverageLatency(us)=86]  
14/07/08 01:19:26 INFO client.AsyncProcess: #20, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014
14/07/08 01:19:26 INFO client.AsyncProcess: #10, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014
14/07/08 01:19:27 INFO client.AsyncProcess: #10, table=usertable, attempt=16/35 failed 2843 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1125, waitTime=2093, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20079 ms, replay 2843 ops.
14/07/08 01:19:27 INFO client.AsyncProcess: #12, table=usertable, attempt=16/35 failed 2847 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1125, waitTime=2093, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20176 ms, replay 2847 ops.
14/07/08 01:19:27 INFO client.AsyncProcess: #1, table=usertable, attempt=16/35 failed 2826 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1125, waitTime=2093, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20008 ms, replay 2826 ops.
14/07/08 01:19:27 INFO client.AsyncProcess: #4, table=usertable, attempt=16/35 failed 2816 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1125, waitTime=2093, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20111 ms, replay 2816 ops.
14/07/08 01:19:27 INFO client.AsyncProcess: #5, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014
14/07/08 01:19:27 INFO client.AsyncProcess: #9, table=usertable, attempt=16/35 failed 2819 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1130, waitTime=2266, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20183 ms, replay 2819 ops.
14/07/08 01:19:27 INFO client.AsyncProcess: #2, table=usertable, attempt=16/35 failed 2831 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1130, waitTime=2266, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20014 ms, replay 2831 ops.
14/07/08 01:19:27 INFO client.AsyncProcess: #18, table=usertable, attempt=16/35 failed 2868 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1130, waitTime=2266, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20054 ms, replay 2868 ops.
14/07/08 01:19:27 INFO client.AsyncProcess: #12, table=usertable, attempt=16/35 failed 2821 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1130, waitTime=2266, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20199 ms, replay 2821 ops.
14/07/08 01:19:27 INFO client.AsyncProcess: #8, table=usertable, attempt=16/35 failed 2879 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1130, waitTime=2266, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20067 ms, replay 2879 ops.
14/07/08 01:19:27 INFO client.AsyncProcess: #20, table=usertable, attempt=16/35 failed 2825 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1130, waitTime=2266, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20166 ms, replay 2825 ops.
14/07/08 01:19:27 INFO client.AsyncProcess: #9, table=usertable, attempt=16/35 failed 2861 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1130, waitTime=2266, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014, retrying after 20197 ms, replay 2861 ops.
14/07/08 01:19:27 INFO client.AsyncProcess: #15, table=usertable, attempt=16/35 failed 2839 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1130, waitTime=2266, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20168 ms, replay 2839 ops.
14/07/08 01:19:27 INFO client.AsyncProcess: #16, table=usertable, attempt=16/35 failed 2799 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1130, waitTime=2266, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20029 ms, replay 2799 ops.
14/07/08 01:19:27 INFO client.AsyncProcess: #7, table=usertable, attempt=16/35 failed 2813 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1130, waitTime=2266, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20151 ms, replay 2813 ops.
14/07/08 01:19:27 INFO client.AsyncProcess: #13, table=usertable, attempt=16/35 failed 2857 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1130, waitTime=2266, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20031 ms, replay 2857 ops.
14/07/08 01:19:27 INFO client.AsyncProcess: #6, table=usertable, attempt=16/35 failed 2819 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1130, waitTime=2266, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20160 ms, replay 2819 ops.
2014-07-08 01:19:31:493 180 sec: 1517657 operations; 15145.1 current ops/sec; [UPDATE AverageLatency(us)=695470.5] [INSERT AverageLatency(us)=1188.1] [CLEANUP AverageLatency(us)=695497.5] 
2014-07-08 01:19:41:495 190 sec: 1653841 operations; 13617.04 current ops/sec;  [INSERT AverageLatency(us)=69.58]  
14/07/08 01:19:47 INFO client.AsyncProcess: #1, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014
14/07/08 01:19:48 INFO client.AsyncProcess: #10, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014
14/07/08 01:19:48 INFO client.AsyncProcess: #4, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014
14/07/08 01:19:48 INFO client.AsyncProcess: #12, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014
14/07/08 01:19:49 INFO client.AsyncProcess: #2, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014
14/07/08 01:19:49 INFO client.AsyncProcess: #13, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014
14/07/08 01:19:49 INFO client.AsyncProcess: #16, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014
14/07/08 01:19:49 INFO client.AsyncProcess: #12, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014
14/07/08 01:19:49 INFO client.AsyncProcess: #8, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014
14/07/08 01:19:49 INFO client.AsyncProcess: #18, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014
14/07/08 01:19:49 INFO client.AsyncProcess: #20, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014
14/07/08 01:19:49 INFO client.AsyncProcess: #9, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:39 PDT 2014
14/07/08 01:19:50 INFO client.AsyncProcess: #15, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014
14/07/08 01:19:50 INFO client.AsyncProcess: #6, table=usertable, attempt=17/35 failed 2819 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1269, waitTime=2318, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20110 ms, replay 2819 ops.
14/07/08 01:19:50 INFO client.AsyncProcess: #7, table=usertable, attempt=17/35 failed 2813 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1269, waitTime=2318, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20061 ms, replay 2813 ops.
14/07/08 01:19:50 INFO client.AsyncProcess: #9, table=usertable, attempt=17/35 failed 2819 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1269, waitTime=2318, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014, retrying after 20082 ms, replay 2819 ops.
2014-07-08 01:19:51:495 200 sec: 1767658 operations; 11380.56 current ops/sec; [UPDATE AverageLatency(us)=462260] [INSERT AverageLatency(us)=18606.33] [CLEANUP AverageLatency(us)=462298] 
2014-07-08 01:20:01:496 210 sec: 1833402 operations; 6573.74 current ops/sec;  [INSERT AverageLatency(us)=701.36]  
2014-07-08 01:20:11:499 220 sec: 1932018 operations; 9858.64 current ops/sec;  [INSERT AverageLatency(us)=676.56]  
14/07/08 01:20:13 INFO client.AsyncProcess: #9, table=usertable, attempt=18/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014
14/07/08 01:20:13 INFO client.AsyncProcess: #7, table=usertable, attempt=18/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014
14/07/08 01:20:13 INFO client.AsyncProcess: #6, table=usertable, attempt=18/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:16:34 PDT 2014
2014-07-08 01:20:21:499 230 sec: 1978978 operations; 4696 current ops/sec;  [INSERT AverageLatency(us)=13777.33]  
2014-07-08 01:20:31:500 240 sec: 2054114 operations; 7512.85 current ops/sec;  [INSERT AverageLatency(us)=2941.88]  
2014-07-08 01:20:41:502 250 sec: 2194994 operations; 14086.59 current ops/sec;  [INSERT AverageLatency(us)=632.21]  
2014-07-08 01:20:51:502 260 sec: 2317090 operations; 12208.38 current ops/sec;  [INSERT AverageLatency(us)=660.23]  
14/07/08 01:20:55 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2885 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1947, waitTime=2100, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:03 PDT 2014, retrying after 10025 ms, replay 2885 ops.
14/07/08 01:20:55 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2806 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1947, waitTime=2100, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:03 PDT 2014, retrying after 10078 ms, replay 2806 ops.
14/07/08 01:20:58 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2842 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1985, waitTime=2766, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:03 PDT 2014, retrying after 10065 ms, replay 2842 ops.
14/07/08 01:20:58 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2861 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1985, waitTime=2766, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:06 PDT 2014, retrying after 10081 ms, replay 2861 ops.
14/07/08 01:20:58 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2867 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1985, waitTime=2766, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:03 PDT 2014, retrying after 10019 ms, replay 2867 ops.
14/07/08 01:20:58 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2789 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1985, waitTime=2766, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:04 PDT 2014, retrying after 10019 ms, replay 2789 ops.
14/07/08 01:20:58 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2826 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1985, waitTime=2766, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:03 PDT 2014, retrying after 10097 ms, replay 2826 ops.
14/07/08 01:20:58 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2815 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1985, waitTime=2766, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:04 PDT 2014, retrying after 10019 ms, replay 2815 ops.
14/07/08 01:20:58 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2799 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1985, waitTime=2766, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:04 PDT 2014, retrying after 10012 ms, replay 2799 ops.
2014-07-08 01:21:01:503 270 sec: 2461808 operations; 14470.35 current ops/sec;  [INSERT AverageLatency(us)=366.78]  
14/07/08 01:21:09 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 2806 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:59973 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:03 PDT 2014, retrying after 10041 ms, replay 2806 ops.
14/07/08 01:21:09 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2885 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:59973 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:03 PDT 2014, retrying after 10034 ms, replay 2885 ops.
14/07/08 01:21:10 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 2826 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:03 PDT 2014, retrying after 10009 ms, replay 2826 ops.
14/07/08 01:21:10 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2861 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:06 PDT 2014, retrying after 10040 ms, replay 2861 ops.
14/07/08 01:21:10 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2842 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:03 PDT 2014, retrying after 10025 ms, replay 2842 ops.
14/07/08 01:21:10 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2815 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:04 PDT 2014, retrying after 10001 ms, replay 2815 ops.
14/07/08 01:21:10 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 2789 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:04 PDT 2014, retrying after 10052 ms, replay 2789 ops.
14/07/08 01:21:10 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2867 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:03 PDT 2014, retrying after 10016 ms, replay 2867 ops.
14/07/08 01:21:10 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2799 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:04 PDT 2014, retrying after 10028 ms, replay 2799 ops.
2014-07-08 01:21:11:504 280 sec: 2533106 operations; 7129.09 current ops/sec;  [INSERT AverageLatency(us)=454.38]  
14/07/08 01:21:19 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 2885 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:60353 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:03 PDT 2014, retrying after 20031 ms, replay 2885 ops.
14/07/08 01:21:19 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 2806 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:60353 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:03 PDT 2014, retrying after 20095 ms, replay 2806 ops.
2014-07-08 01:21:21:505 290 sec: 2533106 operations; 0 current ops/sec;    
14/07/08 01:21:22 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 2826 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:60354 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:03 PDT 2014, retrying after 20130 ms, replay 2826 ops.
14/07/08 01:21:22 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 2789 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:04 PDT 2014, retrying after 20126 ms, replay 2789 ops.
14/07/08 01:21:22 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2799 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:04 PDT 2014, retrying after 20174 ms, replay 2799 ops.
14/07/08 01:21:22 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 2867 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:03 PDT 2014, retrying after 20026 ms, replay 2867 ops.
14/07/08 01:21:22 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2861 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:06 PDT 2014, retrying after 20177 ms, replay 2861 ops.
14/07/08 01:21:22 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 2842 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:03 PDT 2014, retrying after 20027 ms, replay 2842 ops.
14/07/08 01:21:22 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 2815 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:60354 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:04 PDT 2014, retrying after 20192 ms, replay 2815 ops.
2014-07-08 01:21:31:505 300 sec: 2551890 operations; 1878.4 current ops/sec;  [INSERT AverageLatency(us)=1970.61]  
14/07/08 01:21:40 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:03 PDT 2014
14/07/08 01:21:40 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:03 PDT 2014
2014-07-08 01:21:41:506 310 sec: 2890689 operations; 33876.51 current ops/sec;  [INSERT AverageLatency(us)=1099.73]  
14/07/08 01:21:43 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:03 PDT 2014
14/07/08 01:21:43 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:06 PDT 2014
14/07/08 01:21:43 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:04 PDT 2014
14/07/08 01:21:44 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:03 PDT 2014
14/07/08 01:21:44 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 failed 2789 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2441, waitTime=2150, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:04 PDT 2014, retrying after 20148 ms, replay 2789 ops.
14/07/08 01:21:44 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 failed 2842 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2441, waitTime=2150, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:03 PDT 2014, retrying after 20138 ms, replay 2842 ops.
14/07/08 01:21:45 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 failed 2815 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2448, waitTime=2217, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:04 PDT 2014, retrying after 20185 ms, replay 2815 ops.
2014-07-08 01:21:51:507 320 sec: 3209330 operations; 31860.91 current ops/sec;  [INSERT AverageLatency(us)=881.03]  
2014-07-08 01:22:01:508 330 sec: 3223418 operations; 1408.66 current ops/sec;  [INSERT AverageLatency(us)=846.42]  
14/07/08 01:22:06 INFO client.AsyncProcess: #1, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:04 PDT 2014
14/07/08 01:22:06 INFO client.AsyncProcess: #10, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:03 PDT 2014
14/07/08 01:22:07 INFO client.AsyncProcess: #20, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404807003873, tracking started Tue Jul 08 01:20:04 PDT 2014
2014-07-08 01:22:11:509 340 sec: 3523962 operations; 30051.39 current ops/sec;  [INSERT AverageLatency(us)=2012.62]  
2014-07-08 01:22:21:510 350 sec: 3698827 operations; 17484.75 current ops/sec; [UPDATE AverageLatency(us)=2823593] [INSERT AverageLatency(us)=539.46] [CLEANUP AverageLatency(us)=2823626] 
2014-07-08 01:22:31:511 360 sec: 4068018 operations; 36915.41 current ops/sec;  [INSERT AverageLatency(us)=437.82]  
2014-07-08 01:22:41:512 370 sec: 4122580 operations; 5455.65 current ops/sec;  [INSERT AverageLatency(us)=224.54]  
14/07/08 01:22:44 INFO client.AsyncProcess: #13, waiting for some tasks to finish. Expected max=0, tasksSent=193, tasksDone=188, currentTasksDone=188, retries=85 hasError=false, tableName=usertable
2014-07-08 01:22:51:513 380 sec: 4122580 operations; 0 current ops/sec;    
14/07/08 01:22:58 INFO client.AsyncProcess: #13, waiting for some tasks to finish. Expected max=0, tasksSent=206, tasksDone=201, currentTasksDone=201, retries=98 hasError=false, tableName=usertable
2014-07-08 01:23:01:513 390 sec: 4155452 operations; 3286.87 current ops/sec; [UPDATE AverageLatency(us)=26729083] [INSERT AverageLatency(us)=893.9] [CLEANUP AverageLatency(us)=26729110] 
2014-07-08 01:23:11:514 400 sec: 4375920 operations; 22044.6 current ops/sec; [UPDATE AverageLatency(us)=1546010.33] [INSERT AverageLatency(us)=1984.16] [CLEANUP AverageLatency(us)=1546039.33] 
2014-07-08 01:23:21:515 410 sec: 4729384 operations; 35342.87 current ops/sec; [UPDATE AverageLatency(us)=1220982.4] [INSERT AverageLatency(us)=164.29] [CLEANUP AverageLatency(us)=1221014.2] 
2014-07-08 01:23:31:516 420 sec: 4994191 operations; 26478.05 current ops/sec; [UPDATE AverageLatency(us)=596734.67] [INSERT AverageLatency(us)=127.69] [CLEANUP AverageLatency(us)=596759] 
2014-07-08 01:23:32:181 420 sec: 5000000 operations; 8748.49 current ops/sec; [UPDATE AverageLatency(us)=324413] [INSERT AverageLatency(us)=88.1] [CLEANUP AverageLatency(us)=324435] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404807813
1404807813
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo 'random read...'
random read...
+ echo 'starting time: '
starting time: 
++ date +%s
+ echo 1404807823
1404807823
++ echo /home/hadoop/git/physical_design/caseresult/case30/random_read_1.dat
+ ./random_read 5000000 20 /home/hadoop/git/physical_design/caseresult/case30/random_read_1.dat
Loading workload...
Starting test.
2014-07-08 01:23:46:642 0 sec: 0 operations; 
14/07/08 01:23:48 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/08 01:23:48 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/08 01:23:48 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/08 01:23:48 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/08 01:23:48 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/08 01:23:48 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/08 01:23:48 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/08 01:23:48 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/08 01:23:48 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/08 01:23:48 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/08 01:23:48 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/08 01:23:48 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/08 01:23:48 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/08 01:23:48 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/08 01:23:48 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/08 01:23:48 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x4ef888ea, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/08 01:23:49 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x4ef888ea connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/08 01:23:49 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/08 01:23:49 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/08 01:23:49 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x1471505bcde000c, negotiated timeout = 90000
2014-07-08 01:23:56:658 10 sec: 24755 operations; 2471.55 current ops/sec; [READ AverageLatency(us)=7818.04] 
2014-07-08 01:24:06:660 20 sec: 136628 operations; 11185.06 current ops/sec; [READ AverageLatency(us)=1781.85] 
2014-07-08 01:24:16:662 30 sec: 261040 operations; 12439.96 current ops/sec; [READ AverageLatency(us)=1602.13] 
2014-07-08 01:24:26:663 40 sec: 389353 operations; 12828.73 current ops/sec; [READ AverageLatency(us)=1553.41] 
2014-07-08 01:24:36:672 50 sec: 524587 operations; 13511.24 current ops/sec; [READ AverageLatency(us)=1475.1] 
2014-07-08 01:24:46:673 60 sec: 657960 operations; 13335.97 current ops/sec; [READ AverageLatency(us)=1494.47] 
2014-07-08 01:24:56:673 70 sec: 813747 operations; 15578.7 current ops/sec; [READ AverageLatency(us)=1279.02] 
2014-07-08 01:25:06:674 80 sec: 968840 operations; 15507.75 current ops/sec; [READ AverageLatency(us)=1284.68] 
2014-07-08 01:25:16:675 90 sec: 1111047 operations; 14219.28 current ops/sec; [READ AverageLatency(us)=1401.43] 
2014-07-08 01:25:26:675 100 sec: 1263343 operations; 15229.6 current ops/sec; [READ AverageLatency(us)=1308.34] 
2014-07-08 01:25:36:685 110 sec: 1416012 operations; 15251.65 current ops/sec; [READ AverageLatency(us)=1306.13] 
2014-07-08 01:25:46:685 120 sec: 1561771 operations; 14575.9 current ops/sec; [READ AverageLatency(us)=1367.04] 
2014-07-08 01:25:56:686 130 sec: 1714402 operations; 15261.57 current ops/sec; [READ AverageLatency(us)=1305.56] 
2014-07-08 01:26:06:687 140 sec: 1874961 operations; 16054.29 current ops/sec; [READ AverageLatency(us)=1240.77] 
2014-07-08 01:26:16:687 150 sec: 2018150 operations; 14318.9 current ops/sec; [READ AverageLatency(us)=1391.89] 
2014-07-08 01:26:26:688 160 sec: 2171837 operations; 15367.16 current ops/sec; [READ AverageLatency(us)=1296.48] 
2014-07-08 01:26:36:689 170 sec: 2328140 operations; 15628.74 current ops/sec; [READ AverageLatency(us)=1274.7] 
2014-07-08 01:26:46:690 180 sec: 2474710 operations; 14657 current ops/sec; [READ AverageLatency(us)=1284.28] 
2014-07-08 01:26:56:690 190 sec: 2623695 operations; 14897.01 current ops/sec; [READ AverageLatency(us)=1411.58] 
2014-07-08 01:27:06:691 200 sec: 2780779 operations; 15706.83 current ops/sec; [READ AverageLatency(us)=1268.27] 
2014-07-08 01:27:16:693 210 sec: 2934877 operations; 15406.72 current ops/sec; [READ AverageLatency(us)=1289.39] 
2014-07-08 01:27:26:694 220 sec: 3074147 operations; 13925.61 current ops/sec; [READ AverageLatency(us)=1435.05] 
2014-07-08 01:27:36:695 230 sec: 3228819 operations; 15465.65 current ops/sec; [READ AverageLatency(us)=1288.29] 
2014-07-08 01:27:46:696 240 sec: 3386057 operations; 15722.23 current ops/sec; [READ AverageLatency(us)=1267.02] 
2014-07-08 01:27:56:697 250 sec: 3525538 operations; 13946.71 current ops/sec; [READ AverageLatency(us)=1429.01] 
2014-07-08 01:28:06:698 260 sec: 3682498 operations; 15694.43 current ops/sec; [READ AverageLatency(us)=1269.37] 
2014-07-08 01:28:16:699 270 sec: 3836133 operations; 15361.96 current ops/sec; [READ AverageLatency(us)=1296.79] 
2014-07-08 01:28:26:699 280 sec: 3976391 operations; 14025.8 current ops/sec; [READ AverageLatency(us)=1420.73] 
2014-07-08 01:28:36:702 290 sec: 4129918 operations; 15349.63 current ops/sec; [READ AverageLatency(us)=1297.93] 
2014-07-08 01:28:46:703 300 sec: 4283049 operations; 15310.04 current ops/sec; [READ AverageLatency(us)=1301.09] 
2014-07-08 01:28:56:704 310 sec: 4429935 operations; 14687.13 current ops/sec; [READ AverageLatency(us)=1287.11] 
2014-07-08 01:29:06:704 320 sec: 4577161 operations; 14722.6 current ops/sec; [READ AverageLatency(us)=1422.87] 
2014-07-08 01:29:16:705 330 sec: 4730102 operations; 15292.57 current ops/sec; [READ AverageLatency(us)=1302.68] 
2014-07-08 01:29:26:706 340 sec: 4882586 operations; 15246.88 current ops/sec; [READ AverageLatency(us)=1306.24] 
2014-07-08 01:29:35:113 348 sec: 5000000 operations; 13966.22 current ops/sec; [UPDATE AverageLatency(us)=16.45] [READ AverageLatency(us)=1348.87] [CLEANUP AverageLatency(us)=655.2] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404808175
1404808175
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo workloada...
workloada...
+ echo 'start time: '
start time: 
++ date +%s
+ echo 1404808185
1404808185
++ echo /home/hadoop/git/physical_design/caseresult/case30/workloada_1.dat
+ ./workloada 5000000 20 /home/hadoop/git/physical_design/caseresult/case30/workloada_1.dat
Loading workload...
Starting test.
2014-07-08 01:29:47:068 0 sec: 0 operations; 
14/07/08 01:29:47 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/08 01:29:47 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/08 01:29:47 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/08 01:29:47 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/08 01:29:47 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/08 01:29:47 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/08 01:29:47 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/08 01:29:47 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/08 01:29:47 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/08 01:29:47 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/08 01:29:47 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/08 01:29:47 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/08 01:29:47 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/08 01:29:47 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/08 01:29:47 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/08 01:29:47 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x3cfbef54, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/08 01:29:47 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x3cfbef54 connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/08 01:29:47 INFO zookeeper.ClientCnxn: Opening socket connection to server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/08 01:29:47 INFO zookeeper.ClientCnxn: Socket connection established to sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, initiating session
14/07/08 01:29:47 INFO zookeeper.ClientCnxn: Session establishment complete on server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, sessionid = 0x471505bf59000d, negotiated timeout = 90000
2014-07-08 01:29:57:072 10 sec: 42470 operations; 4244.88 current ops/sec; [INSERT AverageLatency(us)=838.75] [READ AverageLatency(us)=3395.46] 
2014-07-08 01:30:07:074 20 sec: 152292 operations; 10980 current ops/sec; [INSERT AverageLatency(us)=23.67] [READ AverageLatency(us)=1909.81] 
2014-07-08 01:30:17:075 30 sec: 269072 operations; 11676.83 current ops/sec; [INSERT AverageLatency(us)=28.7] [READ AverageLatency(us)=1900.76] 
2014-07-08 01:30:27:083 40 sec: 391471 operations; 12230.12 current ops/sec; [INSERT AverageLatency(us)=15.48] [READ AverageLatency(us)=1797.38] 
2014-07-08 01:30:37:084 50 sec: 507963 operations; 11648.04 current ops/sec; [INSERT AverageLatency(us)=15.62] [READ AverageLatency(us)=1885.3] 
2014-07-08 01:30:47:085 60 sec: 622879 operations; 11490.45 current ops/sec; [INSERT AverageLatency(us)=16.07] [READ AverageLatency(us)=1917.8] 
2014-07-08 01:30:57:086 70 sec: 747158 operations; 12427.9 current ops/sec; [INSERT AverageLatency(us)=49.91] [READ AverageLatency(us)=1773.33] 
2014-07-08 01:31:07:086 80 sec: 833233 operations; 8606.64 current ops/sec; [INSERT AverageLatency(us)=16.64] [READ AverageLatency(us)=2571.85] 
2014-07-08 01:31:17:087 90 sec: 933100 operations; 9985.7 current ops/sec; [INSERT AverageLatency(us)=47.78] [READ AverageLatency(us)=2213.34] 
2014-07-08 01:31:27:088 100 sec: 1042677 operations; 10956.6 current ops/sec; [INSERT AverageLatency(us)=33.16] [READ AverageLatency(us)=1923.22] 
2014-07-08 01:31:37:088 110 sec: 1175781 operations; 13310.4 current ops/sec; [INSERT AverageLatency(us)=16.65] [READ AverageLatency(us)=1734.45] 
2014-07-08 01:31:47:089 120 sec: 1308954 operations; 13315.97 current ops/sec; [INSERT AverageLatency(us)=15.96] [READ AverageLatency(us)=1659.67] 
2014-07-08 01:31:57:090 130 sec: 1464348 operations; 15539.4 current ops/sec; [INSERT AverageLatency(us)=18.79] [READ AverageLatency(us)=1419.7] 
2014-07-08 01:32:07:090 140 sec: 1615356 operations; 15099.29 current ops/sec; [INSERT AverageLatency(us)=15] [READ AverageLatency(us)=1460.4] 
2014-07-08 01:32:17:123 150 sec: 1763708 operations; 14786.4 current ops/sec; [INSERT AverageLatency(us)=15.14] [READ AverageLatency(us)=1486.52] 
2014-07-08 01:32:27:124 160 sec: 1887948 operations; 12424 current ops/sec; [INSERT AverageLatency(us)=38.75] [READ AverageLatency(us)=1703.5] 
2014-07-08 01:32:37:124 170 sec: 2024776 operations; 13681.43 current ops/sec; [INSERT AverageLatency(us)=26.84] [READ AverageLatency(us)=1680.13] 
2014-07-08 01:32:47:125 180 sec: 2149738 operations; 12494.95 current ops/sec; [INSERT AverageLatency(us)=16.59] [READ AverageLatency(us)=1765.23] 
2014-07-08 01:32:57:125 190 sec: 2302548 operations; 15281 current ops/sec; [INSERT AverageLatency(us)=16.46] [READ AverageLatency(us)=1444.12] 
2014-07-08 01:33:07:126 200 sec: 2452912 operations; 15034.9 current ops/sec; [INSERT AverageLatency(us)=15.51] [READ AverageLatency(us)=1467.36] 
2014-07-08 01:33:17:127 210 sec: 2604783 operations; 15185.58 current ops/sec; [INSERT AverageLatency(us)=16.49] [READ AverageLatency(us)=1454.93] 
2014-07-08 01:33:27:127 220 sec: 2754794 operations; 15001.1 current ops/sec; [INSERT AverageLatency(us)=15.75] [READ AverageLatency(us)=1445.16] 
2014-07-08 01:33:37:128 230 sec: 2861130 operations; 10632.54 current ops/sec; [INSERT AverageLatency(us)=34.73] [READ AverageLatency(us)=2041.22] 
2014-07-08 01:33:47:129 240 sec: 2961304 operations; 10016.4 current ops/sec; [INSERT AverageLatency(us)=20.06] [READ AverageLatency(us)=2291.51] 
2014-07-08 01:33:57:130 250 sec: 3107198 operations; 14587.94 current ops/sec; [INSERT AverageLatency(us)=16.94] [READ AverageLatency(us)=1516.14] 
2014-07-08 01:34:07:130 260 sec: 3264661 operations; 15746.3 current ops/sec; [INSERT AverageLatency(us)=15.85] [READ AverageLatency(us)=1400.12] 
2014-07-08 01:34:17:131 270 sec: 3412925 operations; 14824.92 current ops/sec; [INSERT AverageLatency(us)=15.38] [READ AverageLatency(us)=1490.32] 
2014-07-08 01:34:27:132 280 sec: 3567360 operations; 15441.96 current ops/sec; [INSERT AverageLatency(us)=15.82] [READ AverageLatency(us)=1431.28] 
2014-07-08 01:34:37:132 290 sec: 3717454 operations; 15009.4 current ops/sec; [INSERT AverageLatency(us)=17.25] [READ AverageLatency(us)=1468.62] 
2014-07-08 01:34:47:133 300 sec: 3829303 operations; 11183.78 current ops/sec; [INSERT AverageLatency(us)=45.45] [READ AverageLatency(us)=1981.46] 
2014-07-08 01:34:57:134 310 sec: 3951048 operations; 12173.28 current ops/sec; [INSERT AverageLatency(us)=15.2] [READ AverageLatency(us)=1817.46] 
2014-07-08 01:35:07:135 320 sec: 4074999 operations; 12393.86 current ops/sec; [INSERT AverageLatency(us)=15.71] [READ AverageLatency(us)=1783.57] 
2014-07-08 01:35:17:135 330 sec: 4235384 operations; 16038.5 current ops/sec; [INSERT AverageLatency(us)=15.96] [READ AverageLatency(us)=1378.08] 
2014-07-08 01:35:27:136 340 sec: 4388004 operations; 15260.47 current ops/sec; [INSERT AverageLatency(us)=16.66] [READ AverageLatency(us)=1395.78] 
2014-07-08 01:35:37:137 350 sec: 4528281 operations; 14026.3 current ops/sec; [INSERT AverageLatency(us)=15.28] [READ AverageLatency(us)=1630.16] 
2014-07-08 01:35:47:137 360 sec: 4676700 operations; 14841.9 current ops/sec; [INSERT AverageLatency(us)=21.92] [READ AverageLatency(us)=1482.69] 
2014-07-08 01:35:57:138 370 sec: 4765112 operations; 8840.32 current ops/sec; [INSERT AverageLatency(us)=30.91] [READ AverageLatency(us)=2211.43] 
2014-07-08 01:36:07:139 380 sec: 4866520 operations; 10139.79 current ops/sec; [INSERT AverageLatency(us)=22.17] [READ AverageLatency(us)=2306.69] 
2014-07-08 01:36:17:140 390 sec: 4998871 operations; 13235.1 current ops/sec; [UPDATE AverageLatency(us)=128557.69] [INSERT AverageLatency(us)=15.24] [READ AverageLatency(us)=1666.86] [CLEANUP AverageLatency(us)=128963.19] 
2014-07-08 01:36:17:977 390 sec: 5000000 operations; 1347.26 current ops/sec; [UPDATE AverageLatency(us)=110570.25] [INSERT AverageLatency(us)=12.49] [READ AverageLatency(us)=1050.81] [CLEANUP AverageLatency(us)=110583] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404808578
1404808578
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo workloadb...
workloadb...
+ echo 'start time: '
start time: 
++ date +%s
+ echo 1404808589
1404808589
++ echo /home/hadoop/git/physical_design/caseresult/case30/workloadb_1.dat
+ ./workloadb 5000000 20 /home/hadoop/git/physical_design/caseresult/case30/workloadb_1.dat
Loading workload...
Starting test.
2014-07-08 01:36:30:279 0 sec: 0 operations; 
14/07/08 01:36:30 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/08 01:36:30 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/08 01:36:30 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/08 01:36:30 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/08 01:36:30 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/08 01:36:30 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/08 01:36:30 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/08 01:36:30 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/08 01:36:30 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/08 01:36:30 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/08 01:36:30 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/08 01:36:30 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/08 01:36:30 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/08 01:36:30 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/08 01:36:30 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/08 01:36:30 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x21934d9d, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/08 01:36:30 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x21934d9d connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/08 01:36:30 INFO zookeeper.ClientCnxn: Opening socket connection to server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/08 01:36:30 INFO zookeeper.ClientCnxn: Socket connection established to sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, initiating session
14/07/08 01:36:30 INFO zookeeper.ClientCnxn: Session establishment complete on server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, sessionid = 0x471505bf59000e, negotiated timeout = 90000
2014-07-08 01:36:40:282 10 sec: 28987 operations; 2897.83 current ops/sec; [INSERT AverageLatency(us)=959.26] [READ AverageLatency(us)=4142.95] 
2014-07-08 01:36:50:284 20 sec: 205346 operations; 17632.37 current ops/sec; [INSERT AverageLatency(us)=15.95] [READ AverageLatency(us)=1960.22] 
2014-07-08 01:37:00:285 30 sec: 372080 operations; 16671.73 current ops/sec; [INSERT AverageLatency(us)=24.64] [READ AverageLatency(us)=2323.16] 
2014-07-08 01:37:10:286 40 sec: 518749 operations; 14665.43 current ops/sec; [INSERT AverageLatency(us)=19.48] [READ AverageLatency(us)=2688.45] 
2014-07-08 01:37:20:287 50 sec: 711059 operations; 19229.08 current ops/sec; [INSERT AverageLatency(us)=15.88] [READ AverageLatency(us)=2044.19] 
2014-07-08 01:37:30:287 60 sec: 877114 operations; 16605.5 current ops/sec; [INSERT AverageLatency(us)=16.68] [READ AverageLatency(us)=2316.25] 
2014-07-08 01:37:40:288 70 sec: 945747 operations; 6862.61 current ops/sec; [INSERT AverageLatency(us)=16.66] [READ AverageLatency(us)=2556.55] 
2014-07-08 01:37:50:289 80 sec: 945747 operations; 0 current ops/sec;   
2014-07-08 01:38:00:289 90 sec: 945747 operations; 0 current ops/sec;   
2014-07-08 01:38:10:290 100 sec: 945747 operations; 0 current ops/sec;   
2014-07-08 01:38:20:291 110 sec: 945747 operations; 0 current ops/sec;   
2014-07-08 01:38:30:291 120 sec: 945747 operations; 0 current ops/sec;   
2014-07-08 01:38:40:292 130 sec: 975085 operations; 2933.51 current ops/sec; [INSERT AverageLatency(us)=30.71] [READ AverageLatency(us)=89292.48] 
2014-07-08 01:38:50:292 140 sec: 1045972 operations; 7088.7 current ops/sec; [INSERT AverageLatency(us)=28.23] [READ AverageLatency(us)=5581.72] 
2014-07-08 01:39:00:293 150 sec: 1140343 operations; 9436.16 current ops/sec; [INSERT AverageLatency(us)=35.83] [READ AverageLatency(us)=4185.67] 
2014-07-08 01:39:10:318 160 sec: 1257416 operations; 11678.1 current ops/sec; [INSERT AverageLatency(us)=17.5] [READ AverageLatency(us)=3384.58] 
2014-07-08 01:39:20:336 170 sec: 1328044 operations; 7050.11 current ops/sec; [INSERT AverageLatency(us)=24.99] [READ AverageLatency(us)=5619.99] 
2014-07-08 01:39:30:372 180 sec: 1416445 operations; 8808.39 current ops/sec; [INSERT AverageLatency(us)=23.55] [READ AverageLatency(us)=4581.07] 
2014-07-08 01:39:40:385 190 sec: 1519868 operations; 10328.87 current ops/sec; [INSERT AverageLatency(us)=17.17] [READ AverageLatency(us)=3842.5] 
2014-07-08 01:39:50:409 200 sec: 1645591 operations; 12542.2 current ops/sec; [INSERT AverageLatency(us)=14.32] [READ AverageLatency(us)=3162.04] 
2014-07-08 01:40:00:410 210 sec: 1765669 operations; 12006.6 current ops/sec; [INSERT AverageLatency(us)=17.53] [READ AverageLatency(us)=3309.94] 
2014-07-08 01:40:10:434 220 sec: 1878533 operations; 11259.38 current ops/sec; [INSERT AverageLatency(us)=22.98] [READ AverageLatency(us)=3532.22] 
2014-07-08 01:40:20:443 230 sec: 1951249 operations; 7265.06 current ops/sec; [INSERT AverageLatency(us)=14.95] [READ AverageLatency(us)=5470.39] 
2014-07-08 01:40:30:485 240 sec: 2028223 operations; 7665.21 current ops/sec; [INSERT AverageLatency(us)=15.67] [READ AverageLatency(us)=5154.06] 
2014-07-08 01:40:40:487 250 sec: 2158671 operations; 13042.19 current ops/sec; [INSERT AverageLatency(us)=18.2] [READ AverageLatency(us)=3084.29] 
2014-07-08 01:40:50:510 260 sec: 2268835 operations; 10991.12 current ops/sec; [INSERT AverageLatency(us)=15.03] [READ AverageLatency(us)=3615.29] 
2014-07-08 01:41:00:589 270 sec: 2408264 operations; 13833.61 current ops/sec; [INSERT AverageLatency(us)=14.69] [READ AverageLatency(us)=2827.89] 
2014-07-08 01:41:10:595 280 sec: 2521774 operations; 11344.19 current ops/sec; [INSERT AverageLatency(us)=18.24] [READ AverageLatency(us)=3528.86] 
2014-07-08 01:41:20:604 290 sec: 2620758 operations; 9889.5 current ops/sec; [INSERT AverageLatency(us)=15.57] [READ AverageLatency(us)=4004.8] 
2014-07-08 01:41:30:605 300 sec: 2734733 operations; 11396.36 current ops/sec; [INSERT AverageLatency(us)=18.45] [READ AverageLatency(us)=3484.42] 
2014-07-08 01:41:40:677 310 sec: 2841197 operations; 10570.29 current ops/sec; [INSERT AverageLatency(us)=20.11] [READ AverageLatency(us)=3634.17] 
2014-07-08 01:41:50:678 320 sec: 2928265 operations; 8705.93 current ops/sec; [INSERT AverageLatency(us)=18.5] [READ AverageLatency(us)=4700.8] 
2014-07-08 01:42:00:680 330 sec: 3000165 operations; 7188.56 current ops/sec; [INSERT AverageLatency(us)=15.98] [READ AverageLatency(us)=5514.75] 
2014-07-08 01:42:10:680 340 sec: 3106861 operations; 10669.6 current ops/sec; [INSERT AverageLatency(us)=16.44] [READ AverageLatency(us)=3721.94] 
2014-07-08 01:42:20:696 350 sec: 3202173 operations; 9515.97 current ops/sec; [INSERT AverageLatency(us)=16.99] [READ AverageLatency(us)=4062.22] 
2014-07-08 01:42:30:704 360 sec: 3295699 operations; 9345.12 current ops/sec; [INSERT AverageLatency(us)=19.43] [READ AverageLatency(us)=4358.92] 
2014-07-08 01:42:40:707 370 sec: 3371268 operations; 7554.63 current ops/sec; [INSERT AverageLatency(us)=36.96] [READ AverageLatency(us)=4162.19] 
2014-07-08 01:42:50:724 380 sec: 3452961 operations; 8156.25 current ops/sec; [INSERT AverageLatency(us)=19.84] [READ AverageLatency(us)=5835.35] 
2014-07-08 01:43:00:739 390 sec: 3527404 operations; 7432.41 current ops/sec; [INSERT AverageLatency(us)=18.98] [READ AverageLatency(us)=5329.81] 
2014-07-08 01:43:10:783 400 sec: 3609713 operations; 8194.84 current ops/sec; [INSERT AverageLatency(us)=20.16] [READ AverageLatency(us)=4829.24] 
2014-07-08 01:43:20:784 410 sec: 3702909 operations; 9318.67 current ops/sec; [INSERT AverageLatency(us)=16.46] [READ AverageLatency(us)=4270.63] 
2014-07-08 01:43:30:801 420 sec: 3809244 operations; 10615.45 current ops/sec; [INSERT AverageLatency(us)=19.81] [READ AverageLatency(us)=3752.88] 
2014-07-08 01:43:40:803 430 sec: 3887239 operations; 7797.94 current ops/sec; [INSERT AverageLatency(us)=17.69] [READ AverageLatency(us)=5070.14] 
2014-07-08 01:43:50:804 440 sec: 3954895 operations; 6764.92 current ops/sec; [INSERT AverageLatency(us)=26.48] [READ AverageLatency(us)=5852.64] 
2014-07-08 01:44:00:805 450 sec: 4044253 operations; 8934.91 current ops/sec; [INSERT AverageLatency(us)=17.51] [READ AverageLatency(us)=4210.8] 
2014-07-08 01:44:10:815 460 sec: 4117388 operations; 7306.19 current ops/sec; [INSERT AverageLatency(us)=33.71] [READ AverageLatency(us)=5670.49] 
2014-07-08 01:44:20:816 470 sec: 4188905 operations; 7150.98 current ops/sec; [INSERT AverageLatency(us)=23.08] [READ AverageLatency(us)=5554.08] 
2014-07-08 01:44:30:844 480 sec: 4279703 operations; 9054.45 current ops/sec; [INSERT AverageLatency(us)=24.13] [READ AverageLatency(us)=4383.77] 
2014-07-08 01:44:40:857 490 sec: 4321175 operations; 4141.82 current ops/sec; [INSERT AverageLatency(us)=15.84] [READ AverageLatency(us)=9647.75] 
2014-07-08 01:44:50:858 500 sec: 4388023 operations; 6684.8 current ops/sec; [INSERT AverageLatency(us)=21.65] [READ AverageLatency(us)=5936.67] 
2014-07-08 01:45:00:858 510 sec: 4425167 operations; 3714.03 current ops/sec; [INSERT AverageLatency(us)=15.37] [READ AverageLatency(us)=10661.5] 
2014-07-08 01:45:10:859 520 sec: 4442353 operations; 1718.43 current ops/sec; [INSERT AverageLatency(us)=17.01] [READ AverageLatency(us)=23495.96] 
2014-07-08 01:45:20:860 530 sec: 4473347 operations; 3099.09 current ops/sec; [INSERT AverageLatency(us)=21.56] [READ AverageLatency(us)=12827.55] 
2014-07-08 01:45:30:861 540 sec: 4541915 operations; 6856.8 current ops/sec; [INSERT AverageLatency(us)=18.57] [READ AverageLatency(us)=5766.66] 
2014-07-08 01:45:40:861 550 sec: 4622959 operations; 8103.59 current ops/sec; [INSERT AverageLatency(us)=19.36] [READ AverageLatency(us)=4891.14] 
2014-07-08 01:45:50:862 560 sec: 4630570 operations; 761.02 current ops/sec; [INSERT AverageLatency(us)=17] [READ AverageLatency(us)=53010.89] 
2014-07-08 01:46:00:868 570 sec: 4685596 operations; 5499.3 current ops/sec; [INSERT AverageLatency(us)=17.97] [READ AverageLatency(us)=4125.32] 
2014-07-08 01:46:10:872 580 sec: 4737560 operations; 5194.32 current ops/sec; [INSERT AverageLatency(us)=22.78] [READ AverageLatency(us)=10859.64] 
2014-07-08 01:46:20:896 590 sec: 4818135 operations; 8038.21 current ops/sec; [INSERT AverageLatency(us)=25.22] [READ AverageLatency(us)=4948.78] 
2014-07-08 01:46:30:909 600 sec: 4886960 operations; 6873.56 current ops/sec; [INSERT AverageLatency(us)=30.1] [READ AverageLatency(us)=5777.4] 
2014-07-08 01:46:40:921 610 sec: 4955995 operations; 6895.23 current ops/sec; [UPDATE AverageLatency(us)=195333] [INSERT AverageLatency(us)=31.25] [READ AverageLatency(us)=5607.19] [CLEANUP AverageLatency(us)=212582] 
2014-07-08 01:46:50:945 620 sec: 4998882 operations; 4278.43 current ops/sec; [UPDATE AverageLatency(us)=330788.24] [INSERT AverageLatency(us)=25.35] [READ AverageLatency(us)=5663.08] [CLEANUP AverageLatency(us)=331389.06] 
2014-07-08 01:46:53:290 623 sec: 5000000 operations; 476.76 current ops/sec; [UPDATE AverageLatency(us)=162767.5] [INSERT AverageLatency(us)=10.48] [READ AverageLatency(us)=7516.14] [CLEANUP AverageLatency(us)=162785.5] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404809214
1404809214
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo workloadc...
workloadc...
+ echo 'start time: '
start time: 
++ date +%s
+ echo 1404809224
1404809224
++ echo /home/hadoop/git/physical_design/caseresult/case30/workloadc_1.dat
+ ./workloadc 5000000 20 /home/hadoop/git/physical_design/caseresult/case30/workloadc_1.dat
Loading workload...
Starting test.
2014-07-08 01:47:06:800 0 sec: 0 operations; 
14/07/08 01:47:07 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/08 01:47:07 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/08 01:47:07 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/08 01:47:07 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/08 01:47:07 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/08 01:47:07 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/08 01:47:07 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/08 01:47:07 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/08 01:47:07 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/08 01:47:07 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/08 01:47:07 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/08 01:47:07 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/08 01:47:07 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/08 01:47:07 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/08 01:47:07 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/08 01:47:07 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0xc2c915f, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/08 01:47:07 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0xc2c915f connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/08 01:47:07 INFO zookeeper.ClientCnxn: Opening socket connection to server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/08 01:47:07 INFO zookeeper.ClientCnxn: Socket connection established to sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, initiating session
14/07/08 01:47:07 INFO zookeeper.ClientCnxn: Session establishment complete on server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, sessionid = 0x471505bf59000f, negotiated timeout = 90000
2014-07-08 01:47:16:803 10 sec: 144767 operations; 14472.36 current ops/sec; [INSERT AverageLatency(us)=225.79] [READ AverageLatency(us)=9527.27] 
2014-07-08 01:47:26:806 20 sec: 304910 operations; 16009.5 current ops/sec; [INSERT AverageLatency(us)=26.58] [READ AverageLatency(us)=12295.22] 
2014-07-08 01:47:36:807 30 sec: 424866 operations; 11994.4 current ops/sec; [INSERT AverageLatency(us)=46.4] [READ AverageLatency(us)=15755.95] 
2014-07-08 01:47:46:809 40 sec: 551202 operations; 12632.34 current ops/sec; [INSERT AverageLatency(us)=19.02] [READ AverageLatency(us)=15580.64] 
2014-07-08 01:47:56:809 50 sec: 646847 operations; 9563.54 current ops/sec; [INSERT AverageLatency(us)=28.23] [READ AverageLatency(us)=16648.01] 
2014-07-08 01:48:06:810 60 sec: 646847 operations; 0 current ops/sec;   
2014-07-08 01:48:16:811 70 sec: 646847 operations; 0 current ops/sec;   
2014-07-08 01:48:26:812 80 sec: 646847 operations; 0 current ops/sec;   
2014-07-08 01:48:36:813 90 sec: 709396 operations; 6254.9 current ops/sec; [INSERT AverageLatency(us)=14.14] [READ AverageLatency(us)=136663.15] 
2014-07-08 01:48:46:813 100 sec: 830304 operations; 12089.59 current ops/sec; [INSERT AverageLatency(us)=22.09] [READ AverageLatency(us)=16620.08] 
2014-07-08 01:48:56:818 110 sec: 945486 operations; 11513.59 current ops/sec; [INSERT AverageLatency(us)=20.2] [READ AverageLatency(us)=16990.02] 
2014-07-08 01:49:06:819 120 sec: 1067685 operations; 12218.68 current ops/sec; [INSERT AverageLatency(us)=15.99] [READ AverageLatency(us)=16421.01] 
2014-07-08 01:49:16:820 130 sec: 1158723 operations; 9101.98 current ops/sec; [INSERT AverageLatency(us)=13.86] [READ AverageLatency(us)=20604.79] 
2014-07-08 01:49:26:821 140 sec: 1276831 operations; 11809.62 current ops/sec; [INSERT AverageLatency(us)=14.45] [READ AverageLatency(us)=17618.42] 
2014-07-08 01:49:36:821 150 sec: 1423304 operations; 14647.3 current ops/sec; [INSERT AverageLatency(us)=14.82] [READ AverageLatency(us)=13615.25] 
2014-07-08 01:49:46:822 160 sec: 1554535 operations; 13121.79 current ops/sec; [INSERT AverageLatency(us)=16.15] [READ AverageLatency(us)=15062.58] 
2014-07-08 01:49:56:823 170 sec: 1682025 operations; 12747.73 current ops/sec; [INSERT AverageLatency(us)=18.96] [READ AverageLatency(us)=15363] 
2014-07-08 01:50:06:834 180 sec: 1808409 operations; 12624.51 current ops/sec; [INSERT AverageLatency(us)=20.97] [READ AverageLatency(us)=15713.56] 
2014-07-08 01:50:16:837 190 sec: 1949843 operations; 14139.16 current ops/sec; [INSERT AverageLatency(us)=25.05] [READ AverageLatency(us)=13937.02] 
2014-07-08 01:50:26:853 200 sec: 2107203 operations; 15710.86 current ops/sec; [INSERT AverageLatency(us)=17.9] [READ AverageLatency(us)=12391.96] 
2014-07-08 01:50:36:859 210 sec: 2238696 operations; 13141.42 current ops/sec; [INSERT AverageLatency(us)=20.68] [READ AverageLatency(us)=14949.23] 
2014-07-08 01:50:46:867 220 sec: 2347462 operations; 10867.91 current ops/sec; [INSERT AverageLatency(us)=35.08] [READ AverageLatency(us)=18355.4] 
2014-07-08 01:50:56:869 230 sec: 2452755 operations; 10527.19 current ops/sec; [INSERT AverageLatency(us)=22.08] [READ AverageLatency(us)=18767.6] 
2014-07-08 01:51:06:871 240 sec: 2558384 operations; 10560.79 current ops/sec; [INSERT AverageLatency(us)=26.15] [READ AverageLatency(us)=18731.14] 
2014-07-08 01:51:16:874 250 sec: 2622817 operations; 6441.37 current ops/sec; [INSERT AverageLatency(us)=15.87] [READ AverageLatency(us)=30614.78] 
2014-07-08 01:51:26:911 260 sec: 2701136 operations; 7803.03 current ops/sec; [INSERT AverageLatency(us)=23.88] [READ AverageLatency(us)=24716.48] 
2014-07-08 01:51:36:934 270 sec: 2770352 operations; 6905.72 current ops/sec; [INSERT AverageLatency(us)=15.46] [READ AverageLatency(us)=26648.17] 
2014-07-08 01:51:46:936 280 sec: 2858312 operations; 8794.24 current ops/sec; [INSERT AverageLatency(us)=18.88] [READ AverageLatency(us)=24107.02] 
2014-07-08 01:51:56:960 290 sec: 2943348 operations; 8483.24 current ops/sec; [INSERT AverageLatency(us)=28.26] [READ AverageLatency(us)=23338.58] 
2014-07-08 01:52:06:971 300 sec: 3028639 operations; 8519.73 current ops/sec; [INSERT AverageLatency(us)=14.29] [READ AverageLatency(us)=21102.04] 
2014-07-08 01:52:17:008 310 sec: 3128139 operations; 9913.32 current ops/sec; [INSERT AverageLatency(us)=17.32] [READ AverageLatency(us)=21509.29] 
2014-07-08 01:52:27:073 320 sec: 3211648 operations; 8296.97 current ops/sec; [INSERT AverageLatency(us)=15.35] [READ AverageLatency(us)=21332.09] 
2014-07-08 01:52:37:080 330 sec: 3306767 operations; 9505.25 current ops/sec; [INSERT AverageLatency(us)=18.96] [READ AverageLatency(us)=23186.36] 
2014-07-08 01:52:47:116 340 sec: 3387163 operations; 8010.76 current ops/sec; [INSERT AverageLatency(us)=24.02] [READ AverageLatency(us)=24625.71] 
2014-07-08 01:52:57:231 350 sec: 3445639 operations; 5781.12 current ops/sec; [INSERT AverageLatency(us)=22.09] [READ AverageLatency(us)=33919.39] 
2014-07-08 01:53:07:234 360 sec: 3537163 operations; 9149.66 current ops/sec; [INSERT AverageLatency(us)=16.5] [READ AverageLatency(us)=21975.51] 
2014-07-08 01:53:17:235 370 sec: 3637365 operations; 10019.2 current ops/sec; [INSERT AverageLatency(us)=16.97] [READ AverageLatency(us)=19916.99] 
2014-07-08 01:53:27:236 380 sec: 3754319 operations; 11694.23 current ops/sec; [INSERT AverageLatency(us)=16.26] [READ AverageLatency(us)=16994.81] 
2014-07-08 01:53:37:245 390 sec: 3894943 operations; 14049.76 current ops/sec; [INSERT AverageLatency(us)=15.9] [READ AverageLatency(us)=13856.74] 
2014-07-08 01:53:47:268 400 sec: 4012965 operations; 11775.12 current ops/sec; [INSERT AverageLatency(us)=18.86] [READ AverageLatency(us)=16603.91] 
2014-07-08 01:53:57:271 410 sec: 4157196 operations; 14418.77 current ops/sec; [INSERT AverageLatency(us)=18.49] [READ AverageLatency(us)=13671.13] 
2014-07-08 01:54:07:274 420 sec: 4294618 operations; 13738.08 current ops/sec; [INSERT AverageLatency(us)=14.29] [READ AverageLatency(us)=14340.47] 
2014-07-08 01:54:17:274 430 sec: 4418327 operations; 12370.9 current ops/sec; [INSERT AverageLatency(us)=17.64] [READ AverageLatency(us)=15952.71] 
2014-07-08 01:54:27:275 440 sec: 4544252 operations; 12591.24 current ops/sec; [INSERT AverageLatency(us)=21.08] [READ AverageLatency(us)=15633.9] 
2014-07-08 01:54:37:276 450 sec: 4684983 operations; 14071.69 current ops/sec; [INSERT AverageLatency(us)=17.61] [READ AverageLatency(us)=14080.37] 
2014-07-08 01:54:47:276 460 sec: 4800859 operations; 11587.6 current ops/sec; [INSERT AverageLatency(us)=17.82] [READ AverageLatency(us)=16339.42] 
2014-07-08 01:54:57:277 470 sec: 4924454 operations; 12358.26 current ops/sec; [UPDATE AverageLatency(us)=871009.67] [INSERT AverageLatency(us)=14.73] [READ AverageLatency(us)=16289.37] [CLEANUP AverageLatency(us)=881833] 
2014-07-08 01:55:07:278 480 sec: 4990297 operations; 6583.64 current ops/sec; [UPDATE AverageLatency(us)=786442.82] [INSERT AverageLatency(us)=16.73] [READ AverageLatency(us)=17222.34] [CLEANUP AverageLatency(us)=786467.09] 
2014-07-08 01:55:11:921 485 sec: 5000000 operations; 2089.81 current ops/sec; [UPDATE AverageLatency(us)=392223.17] [INSERT AverageLatency(us)=16.26] [READ AverageLatency(us)=14109.09] [CLEANUP AverageLatency(us)=392249] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404809713
1404809713
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ let counter=1+1
+ read line
+ set +x
